### ISSUE TITLE
NHSE stops responding after attempting to save.

### ISSUE THREAD

**Issue by rafpoop** [kwsch/NHSE#10]
https://gbatemp.net/threads/animal-crossing-new-horizons-reverse-engineering-glitches-bugs-etc-thread.560199/page-64#post-8992511

I and this person are having similar issues with the newest version: 
#20200329.11 Update text_item_en.txt
on kwsch.NHSE

**Comment by kwsch** [comment]
Thanks :)

There aren't many while (true) loops so it was ez to find!
