### ISSUE TITLE
more of a question than a issue: How can I help with the translation? 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#102]
I wanna help with the translation from English to Italian but I dont really know how to do it to code level

**Comment by fc-dev** [comment]
Before i speak i'm gonna specify one thing: **I'm not a contributor of the project so anything i say could be wrong.**
@GamerKarl I gave a quick look to the project and it doesn't seems like it has a system for dynamic string loading for the components or messages, so...
At the current state there's no way of translating it.
It's possible and not too hard to implement it but...
The real problem would be the items' names.
I don't know if there's some kind of translation sheet for the item names, but translating them by hand would be crazy and most of the times you won't get the right name.
If you find some kind of translation sheet for that then i could do a pull request implementing a language system.

**Comment by swablueme** [comment]
> Before i speak i'm gonna specify one thing: **I'm not a contributor of the project so anything i say could be wrong.**
> @GamerKarl I gave a quick look to the project and it doesn't seems like it has a system for dynamic string loading for the components or messages, so...
> At the current state there's no way of translating it.
> It's possible and not too hard to implement it but...
> The real problem would be the items' names.
> I don't know if there's some kind of translation sheet for the item names, but translating them by hand would be crazy and most of the times you won't get the right name.
> If you find some kind of translation sheet for that then i could do a pull request implementing a language system.
imthe666st seems to have gotten them out of the bcsvs https://github.com/imthe666st/ACNH/tree/master/item_ids

**Comment by GamerKarl** [comment]
> > Before i speak i'm gonna specify one thing: **I'm not a contributor of the project so anything i say could be wrong.**
> > @GamerKarl I gave a quick look to the project and it doesn't seems like it has a system for dynamic string loading for the components or messages, so...
> > At the current state there's no way of translating it.
> > It's possible and not too hard to implement it but...
> > The real problem would be the items' names.
> > I don't know if there's some kind of translation sheet for the item names, but translating them by hand would be crazy and most of the times you won't get the right name.
> > If you find some kind of translation sheet for that then i could do a pull request implementing a language system.
> 
> imthe666st seems to have gotten them out of the bcsvs https://github.com/imthe666st/ACNH/tree/master/item_ids

OH damn yeah I see there is already the italian language, honestly that's a shame i would have liked to help, i am a student trying to learn computer science so this could have been a good excersize for me

**Comment by fc-dev** [comment]
> imthe666st seems to have gotten them out of the bcsvs https://github.com/imthe666st/ACNH/tree/master/item_ids

Cool, guess it is possible without too many problems then!

**Comment by fc-dev** [comment]
@GamerKarl do you have discord?

**Comment by GamerKarl** [comment]
> @GamerKarl do you have discord?

Ye I do just add #2041 to my nickname

**Comment by GamerKarl** [comment]
> @GamerKarl do you have discord?

GamerKarl#2041

**Comment by kwsch** [comment]
The NHSE.Parsing project has a way to dump the resource for all item names -- refer to `GameMSBTDumper.GetItemListResource`. Feed it the path to your language's text folder (`String_USen` for English) and it'll return what NHSE uses for strings.

I don't know what languages would be wanted by the community. There's a total of 14 localizations:
![image](https://user-images.githubusercontent.com/6393368/80119525-ab804c00-853e-11ea-9ca8-94ba0714821f.png)

EUes might be the same as USes, EUfr might be the same as USfr; not sure if CNzh is the same as TWzh.

**Comment by kwsch** [comment]
Added resources for item names for multiple languages.

Please let me know if there's anything else you need help with. You can translate `MessageStrings_it.txt` and `lang_it.txt` if you wish to localize the Italian translation files.
