### ISSUE TITLE
Inventory Editor no longer works on New Horizons patch 1.2

### ISSUE THREAD

**Issue by Primeey** [kwsch/NHSE#103]
1.2 recently came out and you can no longer inject items into the game. When you click read or write it says FailValidate

**Comment by kwsch** [comment]
Gee, if only the Wiki has a description for RAM editing...

**Comment by Primeey** [comment]
There's no need to be dick about it. I looked on the Wiki, I'm using the correct Offsets, I have Validate Data unchecked yet nothing works since 1.2.

**Comment by kwsch** [comment]
NHSE only does read/writes to the specified offset.

Assuming you have the correct offset, the issue is with whatever is handling the read/write requests (aka your sys-botbase that is running on the console), not NHSE. Troubleshoot accordingly.
