### ISSUE TITLE
two questions

### ISSUE THREAD

**Issue by prestonbilt** [kwsch/NHSE#105]
1. so i think you already answered this, but i just wanted to bring it up again to see if you had any advice: the reason i was asking to edit all flags is because i cant find how to expand my inventory- i added a value of 1 to give 40 spaces, but the spaces cant be used in game although i can see them. 

2. in the field items editor, can you add the terrain in the background so i can see where im playing trees and stuff? sorry if this is out of your control i dont know how any of this works. thank you so much for the editor

**Comment by kwsch** [comment]
1. play the game enough to unlock it. Nobody has figured out how to unlock it.
2. blending complex editors is nice to have, but will take a lot of time to implement. The terrain editor is slow (using individual controls for each tile), and the Field Item Editor doesn't refer to the terrain tiles at all -- it'd have to be handled in the image drawing. It's on my radar, but priorities have it pretty low.
