### ISSUE TITLE
Resizing Terrain Editor Window

### ISSUE THREAD

**Issue by LtJayda** [kwsch/NHSE#106]
Would it be possible to allow resizing of the Terrain Editor Window? Whenever I open the editor, the window is too big to fit on the screen (for reference I have a 1366 x 768 resolution). The bottom part of window gets cut off and the bottom buttons end up behind other buttons, and as such, I have no idea what they do.

**Comment by kwsch** [comment]
Use a bigger monitor / different resolution; there is no way to re-scale the UI at this time.
