### ISSUE TITLE
Can't load Modified Savegame in 1.2.0

### ISSUE THREAD

**Issue by RealDekkia** [kwsch/NHSE#108]
After modifying the savegame and restoring it with JKSV the game tells me that the save data is damaged.

Steps to reproduce:

1. Dump Savegame with JKSV
2. Change the location of Nooks Cranny
3. Import Savegame with JKSV
4. Profit?

This isn't an issue with JKSV because importing the unmodified savegame worked fine.
I tested this with build #20200423.21 (https://dev.azure.com/project-pokemon/NHSE/_build/results?buildId=1471&view=results)

**Comment by kwsch** [comment]
Change other aspects and see if it works. The game might not like where you've placed Nook's Cranny.

**Comment by RealDekkia** [comment]
thanks for the anser.
I moved it on top of an item.
