### ISSUE TITLE
MOving out villagers to show boxes

### ISSUE THREAD

**Issue by Faratlz** [kwsch/NHSE#109]
![image](https://user-images.githubusercontent.com/64229913/80150295-2a4ca780-8586-11ea-9a87-5fb9f773f44a.png)

I have loaded this villager from a post and dom shows but when I check the box. It does not show her packed up. It worked before the update? Is there something that I am not doing right?

**Comment by kwsch** [comment]
Gee, if only there was a pop-up message telling you what to do in addition to ticking the box.

**Comment by Faratlz** [comment]
I did that btw and that did not work

**Comment by Faratlz** [comment]
Gee
