### ISSUE TITLE
Language setting "German" has no effect

### ISSUE THREAD

**Issue by Conan179** [kwsch/NHSE#110]
Hi!
I have download this version
https://dev.azure.com/project-pokemon/NHSE/_build/results?buildId=1472&view=results
And wanted to briefly let you know that the language setting "German" does not work, it just remains English.

GReetz

**Comment by kwsch** [comment]
> does not work

No, it totally works.

![image](https://user-images.githubusercontent.com/6393368/80153451-65dd7680-8572-11ea-917f-86a69e1e0647.png)

Nobody has bothered submitting a translation for any language besides Spanish.

https://github.com/kwsch/NHSE/blob/master/NHSE.WinForms/Resources/text/lang_de.txt

Feel free to submit a pull request, or reply with an updated translation file.
