### ISSUE TITLE
Can not edit storage in V1.2.0

### ISSUE THREAD

**Issue by btcioner** [kwsch/NHSE#111]
Can not edit storage in V1.2.0

**Comment by kwsch** [comment]
Assuming you are injecting your items directly into RAM, refer to the Wiki. Offsets are different for different patches.

> Pocket Item Offsets: Use the corresponding offset for the version of the game you are playing.

**Comment by btcioner** [comment]
I am not injecting memory, but modifying the archive file with no modification effect.
