### ISSUE TITLE
Wallpaper and flooring issue

### ISSUE THREAD

**Issue by Daveyoger** [kwsch/NHSE#112]
Hey friend, so I used this to change all my villagers right? Well one of them was moving out and my friend wanted it so they came over to my island and spoke with them till the villager asked to move to theit island. Only problem is once they got to my friend island they didn't have their wallpaper or flooring. So I think what happened is when I changed the original villager into the new villager it like, didn't change the house data from the original villager's? Or it could be something else entirely

**Comment by kwsch** [comment]
House data is separate from villager data.
