### ISSUE TITLE
Add support for USB-Botbase

### ISSUE THREAD

**Issue by datiecher** [kwsch/NHSE#114]
It would be great for those of us that have a flaky wireless connection to be able to use the memory tools available in the app over a USB cable, instead of having to go through Wi-Fi.

For that reason, adding support for [USB-Botbase](https://github.com/fishguy6564/USB-Botbase) would be great since it's basically fork of sys-botbase that communicates over a wired connection.

**Comment by datiecher** [comment]
Another scenario such a feature might be useful is during local play, since the Switch would be using its own ad-hoc connection at that point and therefore would not be on the same Wi-Fi network as the PC running NHSE.

**Comment by kwsch** [comment]
There aren't any open source implementations of a USB-Botbase client in C# to reference/reuse in NHSE. The one that NHSE uses to interface with sys-botbase was developed for [other](https://github.com/architdate/PKHeX-Plugins) [projects](https://github.com/kwsch/SysBot.NET) and was copied (with permission) to here.

If someone creates a usb client in C#, I'll be happy to merge it in and provide the options to switch between wired/wireless botbase communication modes, but I myself won't develop it :\
