### ISSUE TITLE
Paint brush tool / image import for terrain

### ISSUE THREAD

**Issue by mm04926412** [kwsch/NHSE#115]
my apologies if this exists and I've missed it but I can see the terrain editing being made vastly easier by either

1. Allow images of the correct dimensions to be parsed as terrain so that standard image editors can be used to draw an island

2. Add paint brush tools and other free hand tools for a more intuitive island editing experience.

**Comment by mm04926412** [comment]
https://eugeneration.github.io/HappyIslandDesigner/

My suggestion would be to make the output of happy island designer readable

**Comment by kwsch** [comment]
1. A pixel cannot represent all properties of a terrain tile. There are multiple types of cliffs, rivers, etc; [at least 250](https://github.com/kwsch/NHSE/blob/56f48be173914aa2fcecb8e7df7a71aa2a53b70c/NHSE.Core/Structures/Acres/Terrain/TerrainUnitModel.cs), not including rotation/variation.

2. There are hotkeys to quick read/write individual tiles. You can control-click a slew of tiles to set each tile with a single click of the mouse.

3. HID doesn't do anything for cliff/river/etc tiles, or angle/variation.

3. NHSE imports/exports terrain data. People can write separate programs to edit the terrain, or write separate programs to convert HID's output into something importable by NHSE.

**Comment by mm04926412** [comment]
While I was unaware of the ctrl click functionality (thanks for pointing that out) an area of effect brush / rectnagular select and fill tool would greatly improve usability!
