### ISSUE TITLE
View/Edit items as hexadecimal or binary, or alternative mode for flower plant data.

### ISSUE THREAD

**Issue by Atrius97** [kwsch/NHSE#117]
**Is your feature request related to a problem? Please describe.**
Currently in the item editor, with the way the item data is interpreted, it's extremely difficult to assign specific values to items in certain cases. Obtaining the correct value currently requires technical knowledge of how NHSE reads the 8-byte item structure, or trying to find the item manually in a hex editor to assign this value properly.

As an example, Flower Plants require a specific hex/binary value to be set that modifies their color, and behavior when cross breeding with other flowers. 

A Blue Rose plant will always require the value "RRYYwwss/11111100/fc" to behave properly, and without this value, they will generate the wrong species when crossbreeding and behave wrong. Simply generating a Blue Rose plant item without this extra data will have it behave like White Rose plant with the genotype "rryyWWss/00000000/00".

**Describe the solution you'd like**
The ability to view and directly edit an item as raw binary or hexadecimal values, as they appear before being interpreted by NHSE. This would allow users to manually enter the values needed in situations like this.

**Describe alternatives you've considered**
Alternatively, when viewing a flower plant, buds, or sprouts in the item editor, the UI could allow users to enter the genotype of the plant manually, similar to how DIY recipes are already handled handled. 

**Additional context**
See these documents for how these values are handled: 

Genetics overview:
https://docs.google.com/document/d/1ARIQCUc5YVEd01D7jtJT9EEJF45m07NXhAm4fOpNvCs/

List of flags and values for all possible flower genotypes:
https://docs.google.com/spreadsheets/d/11pRCX8G0xGizSYWgVhoUSu7pE-MV7AOprBcgSY1whB4/

Spreadsheet containing genotype value for store-bought seed origin red roses, vs what NHSE currently displays.
![Capture](https://user-images.githubusercontent.com/39707481/80276290-02079a80-86a5-11ea-88cd-f33f871d77e5.PNG)
![Capture2](https://user-images.githubusercontent.com/39707481/80276291-02a03100-86a5-11ea-8f84-c548e5f6f82b.PNG)

**Comment by bpear** [comment]
Hey, I might be doing something wrong, but for specific flower bags, I am not seeing a way to add more than 1 in a stack. I can add multiplies and stack them in-game up to 10. However, the editor does not show a "Count:" option when a colored flower bag is selected. 

Thank you for your continued development and suppor!

**Comment by kwsch** [comment]
@bpear what does the item look like in the item grid? (with the other items)

https://github.com/kwsch/NHSE/blob/beb4e8111a5601582ab60a5ab536d42b03152dbb/NHSE.Core/Structures/Item/Item.cs#L24-L28

Maybe you can send a dump of the items so I can manually inspect where they're holding Count for these gene-items.
