### ISSUE TITLE
Offset error after 1.2.0 and new build of NHSE 

### ISSUE THREAD

**Issue by arjiq** [kwsch/NHSE#118]
When using the newest build of NHSE, I try to open my main.dat file but still getting the offset error.

**Comment by kwsch** [comment]
"offset error" is too vague. Please elaborate.

**Comment by arjiq** [comment]
![1Capture](https://user-images.githubusercontent.com/64316544/80302315-26737d80-875e-11ea-9a61-963e04c4ecca.PNG)

After trying to open my save file using the main.dat as well as drag & drop the folder itself, this  is the error I am getting every single time

**Comment by kwsch** [comment]
Did you use a bad cheat code to change $$$ or nook miles? The program sanity checks itself whenever it decrypts a `EncryptedInt32`; any invalid value will cause the program to not load.
