### ISSUE TITLE
Given items returns as only 1 item

### ISSUE THREAD

**Issue by tugakit** [kwsch/NHSE#120]
I can give me in items and storage the items like 30 wood but in the game i will only have 1 instead of 30.
Kinda new to GitHub and don't know how can i help you further

**Comment by Atrius97** [comment]
Item count begins at 0 = 1. If you want a stack of 30 items, input 29 for the count in NHSE. Note: some items do not stack and use Count/Uses values for other data, and some items will stack to different amounts like 10, 100, etc.

**Comment by kwsch** [comment]
Read the wiki. It exists for a reason.
![image](https://user-images.githubusercontent.com/6393368/80293614-7e39c680-8715-11ea-8023-672ffa111ad7.png)
