### ISSUE TITLE
Item injection results in all items being replaced with empty presents.

### ISSUE THREAD

**Issue by dazzaXx** [kwsch/NHSE#121]
When attempting to item inject a diy recipe for the iron fence, upon opening the inventory, it replaces all items it can with a bugged present. Have i set something wrong within the program? Thanks.

**Comment by kwsch** [comment]
Read the wiki.

https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection

**Comment by dazzaXx** [comment]
I have read through the entire wiki and the offset is already set to v1.2 which I am running, yet the problem persists no matter what item I attempt to inject, after which I get the "FailValidate" when try a manual read after the error occurs.

**Comment by Atrius97** [comment]
Some cheat overlays like Edizon/Tesla need to be disabled as they conflict with this. Restart your switch and try removing/disabling overlays before trying live injection.

**Comment by dazzaXx** [comment]
Odd, i've ran and used the item injector many times before with Tesla and such enabled without issues. I will try that.
