### ISSUE TITLE
Terrain Editor All Tiles Bug

### ISSUE THREAD

**Issue by Cynthdivide** [kwsch/NHSE#122]
Hi All,

  The terrain editor seems to impact non-editable tiles like River rocks when you the Set All Tiles using... button. This causes River rock areas to glitch out. Can those non-editable areas like that be omitted? 

Thanks!

**Comment by kwsch** [comment]
It's only really supposed to be used for resetting all tiles back to "None"; any other usage can result in these weird behaviors.

Until someone catalogs the un-editable tiles of every acre, I can't implement anything into the program as a safeguard.

**Comment by Cynthdivide** [comment]
Hey Kurt


  It's really only seeming to impact those River Stones. Is there a way I
can help with this? I dont know how to program minus web based stuff but if
I can help from within NHSE, I'm all ears.

Thanks for the response!
