### ISSUE TITLE
NHSE memory inject failed while other tool works

### ISSUE THREAD

**Issue by mickeyandkaka** [kwsch/NHSE#124]
**Is your feature request related to a problem? Please describe.**
No, I've try [anchpoker](https://github.com/KingLycosa/acnhpoker), and that tool works for me.

**Describe the solution you'd like**
Memory Inject should work.
My version is 1.2.0, used lastest NHSE. I've confirmed that my atmosphere close th cheats,  which I  set dmnt_cheats_enabled_by_default = u8!0x0, and reboot my switch.

**Describe alternatives you've considered**
None

**Additional context**
I have used Edison before, however it can not use for achn. Then I delete all the file related to Edison. I have close the cheats & reboot &  hold L button into the game, still not working.
So I use anchpoker instead. I hope I can use memory inject the DIY recipe

**Comment by kwsch** [comment]
You've likely corrupted the part of your save file that NHSE is trying to validate.

NHSE's validator requires the 32bit value right after the expansion-pocket data to be <= 20. If you used a previous version of the program / another program with the wrong offset, and wrote misaligned data, then you've screwed up something that can only be fixed (currently) by editing the RAM manually via the RAM editor.

**Comment by mickeyandkaka** [comment]
Yes, previously I use NHSE trying to inject DIY recipe , but with wrong numbers, I thought this is the problem

**Comment by mickeyandkaka** [comment]
I will try to restore another clean save file.
