### ISSUE TITLE
Field editor: automatic extension tiles

### ISSUE THREAD

**Issue by fc-dev** [kwsch/NHSE#127]
I'm not sure if I'm missing something obvious, but at the current state to leave an item on the ground you need to:
-know it's ItemType
-know it's ExtensionItem
-lots of other things
-set it to a square
-set its 3 extension tiles

That's a pretty difficult process, that makes putting lots of item on the ground basically impossible.

It would be way easier if there was a combobox for selecting the item you need to put on a square (like the one for the inventory editor), and if the extension tiles where set accordingly.

**Comment by kwsch** [comment]
> extension tiles where set accordingly.

need a dataset of each item's placed dimensions

**Comment by fc-dev** [comment]
it could already be done for item left on the ground (not placed) as they always have only 3 extension tiles
