### ISSUE TITLE
Maybe knowing what an unknown value equates to?

### ISSUE THREAD

**Issue by thelistenersfury** [kwsch/NHSE#129]
I'm not at all familiar with how to do anything about this information, but in the terrain editor, I've noticed that the value in the unknown 6 box and unknown A under the misc header seems to be not zero on squares that I've placed paths in my town. The number also changes slightly on tiles that are the edge of paths, center, corners, or rounded. In it's current form the editor doesn't let me try some values to see if I can make changes and verify the information. 

for example here's a picture of the numbers on some squares I drew up real quick: https://imgur.com/a/JqFSMbP

I don't know anything about coding or I'd try and figure it out, but since I don't I figured I'd try and see if someone with more knowledge could.  

edit: Figured out how to change values, I'm gonna test that now

**Comment by geoah** [comment]
@thelistenersfury was looking for this as well.
This is the terrain I get from a weirdly shaped stone path.

![image](https://user-images.githubusercontent.com/88447/80397236-becc4800-88ad-11ea-9aa2-ba67d0064b7a.png)
