### ISSUE TITLE
import/export custom designs

### ISSUE THREAD

**Issue by serenatake** [kwsch/NHSE#13]
**Is your feature request related to a problem? Please describe.**
When you do not have access to a NSO subscription you can not import custom designs.

**Describe the solution you'd like**
A way to import/export .acnl files from https://acpatterns.com/. 

**Additional context**
I looked into the main.dat file and it seems like they are saved in the same format as new leaf. So this should be possible.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/NHSE/commit/4943bb07ad6e30e412e91a3a7144b3b003703a87

`.acnl` is for new leaf; the format is different. The website would probably need to update their export formats, as the new format allows for custom color choices (0-255/0-255/0-255 RGB values).
