### ISSUE TITLE
A button that will automatically set flowers to watered

### ISSUE THREAD

**Issue by kingraijun** [kwsch/NHSE#130]
**Is your feature request related to a problem? Please describe.**

I know some players would want to break the norm and just set the code to have hybrid flowers ready in their inventory but some would want a little "challenge" or sense of accomplishment along the way. I felt the latter when I can see the new flower sprout as result of constant watering the flower fields every single day. But it's a bit of frustrating to have acres of flowers and water them with the watering can. I was thinking if it's possible to just tweak the tool to automatically set the flowers as watered.

**Describe the solution you'd like**

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

It is good-to-have a button that instantly set flowers to be watered perhaps in the Map > Edit Field Items > Set flowers watered (?). It could be per acre or the whole island (same as holding Shift key).

**Describe alternatives you've considered**

**Additional context**

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
