### ISSUE TITLE
About terrain editor

### ISSUE THREAD

**Issue by Delsinhaha** [kwsch/NHSE#131]
I got only 15X16 in terrain editor, but it supposed to be 16X16 idk.
![屏幕截图(54)](https://user-images.githubusercontent.com/31792063/80396179-dc69d380-88e6-11ea-968a-a75a3b5194dd.png)

**Comment by kwsch** [comment]
Is your operating system Display Scaling not 100%? I assume that a 125% scaling would make them them appear incorrectly.

They should be squares, not tall rectangles.

**Comment by Delsinhaha** [comment]
Thx for your time but my scaling is 100% and I tried different values still 15X16,I know it should be square.

**Comment by Delsinhaha** [comment]
And it seems that I am not the only one.
![ed84efd1f703918f1da948a2463d269758eec487](https://user-images.githubusercontent.com/31792063/80398982-0f15cb00-88eb-11ea-85e4-88853502df3d.png)
This pic is downloaded from a forum, He got the same problem here.

**Comment by nickyo1011** [comment]
I cant even see the save or cancel button at the bottom

**Comment by kwsch** [comment]
The Field Item Editor can now edit both Building position and the underlying terrain tiles, all with a smaller window.

Hopefully this alternative presentation is sufficient :)

**Comment by kwsch** [comment]
The [Terrain Editor] is now deprecated in favor of the [Field Item Editor]. I'm leaving the existing [Terrain Editor] window in the program for now so that ppl may still use it if they wish.

**Comment by Delsinhaha** [comment]
> The [Terrain Editor] is now deprecated in favor of the [Field Item Editor]. I'm leaving the existing [Terrain Editor] window in the program for now so that ppl may still use it if they wish.

THX for your work！UR da best！
