### ISSUE TITLE
Editing doesn't apply in game.

### ISSUE THREAD

**Issue by stangwsn** [kwsch/NHSE#132]
Hello!
When using the program, the editing doesn't apply correctly in the game.
In deep: I use JKSV, and everything is fine doing the process: I extract the files, I edit them in the program, I inject the edited file, but then, in game, the changes don't appear. Furthermore, when I reedit the edited file which i injected previously, the changes (in the program) appear.
For example: if I add 2NMTs to my save, in game they don't appear, but they do when editing in the program.
I hope you guys can help me, thanks. ~

**Comment by kwsch** [comment]
If they show up in the program but not on the console, then you aren't restoring the data correctly.

Data doesn't behave one way on the console, and another way on the PC.

**Comment by stangwsn** [comment]
thank you!!!
