### ISSUE TITLE
Pier (Jetty) missing

### ISSUE THREAD

**Issue by Possum80** [kwsch/NHSE#134]
Tried searching thread and on terrain and map editor, as well buildings.  The jetty/pier is not listed anywhere.  Is this feature missing or could you point me to the right area?  Thanks

**Comment by kwsch** [comment]
Refer to the Acre editor. It's an onion of acres, with 3 layers:

1. Inner acres that are fully customizeable (00)
2. Beach acres that are limited for customization
3. Ocean acres that cannot be customized (or even accessed in-game).

The pier is fixed within its own acre.
