### ISSUE TITLE
Have the squares for buildings cover all the space they do in game

### ISSUE THREAD

**Issue by thelistenersfury** [kwsch/NHSE#135]
**Is your feature request related to a problem? Please describe.**
It's a lot of trial an error to know exactly where the buildings are being placed.
**Describe the solution you'd like**
I'd like it if on the edit buildings page the little yellow square for the buildings could be sized according to the in game size
Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by thelistenersfury** [comment]
Oh and maybe if the buildings could show up in the field items and terrain editor that would be amazing

**Comment by kwsch** [comment]
#85
