### ISSUE TITLE
On importing .nhi files to house storage.

### ISSUE THREAD

**Issue by toyomitsu** [kwsch/NHSE#143]
It would be nice if, when you load .nhi files in the villager's storage editor, the items get inserted in the next spaces with nothing (a.k.a. "None") instead of just replacing page 1's first slots.

**A bit more context**
I figured out how .nhi works and generated a file with some items, but when I load them, I wanted them to just replace the blanks. So that's why I'm asking.
This is probably not intended at all since .nhi is originally a dump of an entire inventory, but if you consider it, it would be nice. A checkbox to enable this would be probably ok!

**Comment by kwsch** [comment]
You shouldn't be mixing Villager storage items with Player/Storage items; only swap out with other files of the same size for villagers.

Villager items are 0x2C bytes/item with extra data attached; regular items are 0x8 bytes/item.

**Comment by toyomitsu** [comment]
I know you've closed this, but I think you misunderstood my issue?
I'm talking about regular items. yes, 0x8 bytes (4 bytes little endian ID, 4 bytes little endian quantity).
By saying villager, I meant the player.

I was just suggesting it'd be neat if loading .nhi items would fill the items in the "None" boxes instead of starting in index 0.
