### ISSUE TITLE
Pocket is full

### ISSUE THREAD

**Issue by cacao2010** [kwsch/NHSE#145]
Thank You for your gui tool, but i have problem, i cant buy anything for the Nooks miles, its say the pocket is full for premium content, but its not full. I search the same problem here, You write find PocketStorage 30-40, but i cant find it anywhere in flags or items or achivments. Thank You for your reply

**Comment by kwsch** [comment]
Pocket count is regulated by the two counts in the player editor, and two flags in the player flags.

Keep in mind that ordered items are shipped the next day; the game caps how many you can order, as the buffer that stores ordered items is a fixed size.
