### ISSUE TITLE
Flags to trigger Redd, Celeste and Shooting stars 

### ISSUE THREAD

**Issue by defelper** [kwsch/NHSE#146]
Is there any way to enable flags to trigger these events?

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
