### ISSUE TITLE
edit map with mouse clicks

### ISSUE THREAD

**Issue by lennurs** [kwsch/NHSE#149]
maybe something like mario maker where you can rise/lower a floor by clicking on a button on a little dashboard to the left of the map. basically an easier way to add items on the ground and move buildings by just dragging  them instead of having to move them by code. would make editing maps way easier!

**Comment by kwsch** [comment]
Buildings can already be moved with the directional arrows in the building editor.

The  Field Item Editor is only for manipulating placed items. Doing fancy drag logic would take a lot of time, and time would be better spent in other areas for other editors -- users can already move stuff in-game. The program is open source, so anyone can contribute code if they really want a feature.
