### ISSUE TITLE
May Day Ticket Item id?

### ISSUE THREAD

**Issue by XargonWan** [kwsch/NHSE#150]
Sorry, I know that this is not a proper software issue but is it possible to have the May Day ticket number?
I cannot find it on the list...

Thanks in advance and sorry again.

**Comment by Conan179** [comment]
You dont add this at you poket.
The ticket is deposited by tom nook directly at the airport.
You have NO way to get there.

**Comment by XargonWan** [comment]
So is it a flag to add?

**Comment by Conan179** [comment]
https://gbatemp.net/threads/noob-friendly-guide-ac-nh-easter-event-manual-unlock.561530/
read this

**Comment by XargonWan** [comment]
Thanks!

**Comment by MirayXS** [comment]
"May Day Ticket" isn't a item
