### ISSUE TITLE
Field Editor: better item selection

### ISSUE THREAD

**Issue by labihi97** [kwsch/NHSE#151]
**Is your feature request related to a problem? Please describe.**
It gets tiring having to look at the items id sheets to place an item on the ground.

**Describe the solution you'd like**
It would be nice if there was a ComboBox in the Field Editor like the one in the Inventory Editor

**Comment by Possum80** [comment]
Useful, but do realise the items list is very, very long.  I'm not sure adding it to the program will be useful - you still end up scrolling through an extensive list to select the item you want

**Comment by MirayXS** [comment]
you can actually write in the search box the item name you want, press SEND and set in your inventory.

**Comment by fc-dev** [comment]
> Useful, but do realise the items list is very, very long. I'm not sure adding it to the program will be useful - you still end up scrolling through an extensive list to select the item you want

The same stuff it's already done in the Inventory Editor with autocomplete, so it would be useful.
