### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by nickyo1011** [kwsch/NHSE#152]
1. The terrain editor needs to be able to be resized, I can not see the bottom.
2. You should add a scaling guide so people know what their island size will be

**Comment by kwsch** [comment]
1. https://github.com/kwsch/NHSE/issues/131
2. I don't understand what you're asking for. The island size can't be changed.

**Comment by nickyo1011** [comment]
I am talking about making it so you can tell what size it will be. Im running into a situation where I can not tell how big the space i make will be, for example rivers, how big will three squares be? That kind of scaling guide!

**Comment by kwsch** [comment]
The general guideline is to just refer to your current savedata's layout, in order to get an understanding of how big things are.
