### ISSUE TITLE
item models in storage/inventory editor

### ISSUE THREAD

**Issue by stangwsn** [kwsch/NHSE#153]
hello!
in the storage/inventory editor, for editing the model of certain item (f/e: rattan armchair) shall i use the flag0 option and then try to adjust it between values of 0 and the max models the item has? (in this example, between 0 and 5, since there are 6 different color options for this item)
idk if i've explained myself correctly.
thanks!! :)

**Comment by kwsch** [comment]
[Refer to the wiki -- yes, it is item flags](https://github.com/kwsch/NHSE/wiki/Item-Editing); it is recommended to use the Item Injection feature (with sys-botbase) to test out different variations on the fly.

You're on the right track, but I'm not sure that the variant values would be sequential / gapless. Just experiment for now :)

**Comment by stangwsn** [comment]
cool, i'll do so, thanks!
