### ISSUE TITLE
Edit Received Items List enhancement

### ISSUE THREAD

**Issue by theiconrichie** [kwsch/NHSE#154]
Hi,

Just wanted to report is you choose "Unlocked All items" this will break your nook miles to unlock things you are missing. ie. 

I was missing Custom Designs and Ultimate Pocket. These are both nook miles items that have to be done from the nook miles store.

Please remove these items to unlock.

thanks!

**Comment by kwsch** [comment]
Please list the items that need to be skipped.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
