### ISSUE TITLE
adding diy items into pockets instead of the recipes app?

### ISSUE THREAD

**Issue by Skyrainsprings** [kwsch/NHSE#155]
hi, im not sure if this question has been answered but is there a way to make an item a diy recipe, if at all applicable to said item, like an ironwood chair? it probably has been answered already or theres not a way to do so, but if there is may i please know how for future reference? thank you in advance (also keep up the good work with the editor owo)

**Comment by kwsch** [comment]
Did you even bother using the item editor for a DIY recipe?

**Comment by Skyrainsprings** [comment]
oop my bad i figured it out lol, sorry
