### ISSUE TITLE
About Translation

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/NHSE#157]
using System.Collections.Generic;

namespace NHSE.Core
{
    public static class LifeSupportAchievement
    {
        private const string Unknown = "???";

        private static readonly IReadOnlyDictionary<int, string> Dictionary = new Dictionary<int, string>
        {
            {1,"目标是成为垂钓高手"}, // サカナを釣った
            {2,"迈向虫类猎人之路"}, // ムシを捕まえた
            {3,"能成为传说中的垂钓者吗？！"}, // 連続で釣りを成功させた回数の最高記録
            {4,"成为鱼类博士吧"}, // サカナ図鑑を埋めた
            {5,"能成为虫类博士吗？！"}, // ムシ図鑑を埋めた
            {6,"目标，成为气球猎人！"}, // ふうせんを撃ち落とした
            {7,"享受园艺的乐趣吧！"}, // 花の種を植えた
            {8,"水果乐园"}, // 6種類のフルーツを植えた
            {9,"给岛上增添绿色！植树挑战！"}, // 木の苗を植えた
            {10,"大头菜东家独享优惠里数"}, // カブを買った
            {11,"迈向大头菜梦想家之路"}, // カブで得た累計利益
            {12,"购物带动经济狸！"}, // これまでの買い物総額
            {13,"感谢你的购物！"}, // まめきちの店で買い物した
            {14,"闲置品收购！"}, // まめきちの店で売った
            {15,"改造家具次数"}, // リメイクをした
            {16,"目录充实，生活也充实♪"}, // カタログの項目数
            {17,"尽情网购"}, // 通販を利用した
            {18,"享受现场演唱会吧♪"}, // とたけけのライブを観た
            {19,"流浪的旅行者！"}, // よその島へのおでかけした
            {20,"增加岛上游客大作战"}, // 島にフレンドを招いた
            {22,"在岛上的宝贵时光"}, // 活動日数
            {24,"浇浇花，有花相伴的生活"}, // 水やりをした
            {25,"旧伤未愈又添新伤"}, // ハチに刺された
            {26,"得到夏日的回忆"}, // セミのぬけがらを取った
            {27,"抓住跳蚤吧！"}, // ノミを取ってあげた
            {28,"注意危险的虫子！"}, // こわいムシで気絶した
            {32,"用反应让沟通更丰富多彩"}, // リアクションを覚えた
            {33,"净化大海与河川"}, // ゴミを釣った
            {34,"移居费用里数返还"}, // 移住費用を支払った
            {35,"祝贺你！还清贷款狸！"}, // ローンを完済した	
            {36,"要试着做一下“我的设计”吗？"}, // マイデザインを使った
            {37,"专业设计师初次登场！"}, // マイデザインPROを使った
            {38,"招募除草志愿者"}, // 雑草を引き取ってもらった
            {40,"金光闪闪的道具是一流的证明"}, // 6種類の金の道具を集めた
            {41,"建造房间的高手"}, // HHAでSを取った
            {42,"乐享！钓鱼大赛"}, // 釣り大会に春夏秋冬参加した
            {43,"忙碌♪捕虫大赛"}, // ムシとり大会に6～9月参加した
            {44,"值得信赖的救生员"}, // ジョニーを助けた
            {45,"在岛上看到的东西是秘密狸！"}, // ゆうたろうを助けた
            {46,"雪人专家"}, // 最高のゆきだるまを作った
            {47,"生日快乐！"}, // 誕生日を迎えた
            {48,"祝贺生日吧！"}, // 村民の誕生日を祝ってあげた
            {49,"跨年倒计时吧！"}, // カウントダウンに参加した
            {50,"道具粉碎机"}, // 道具を壊した
            {51,"笔耕不辍"}, // 手紙を送った
            {52,"恶作剧头目"}, // 落とし穴を作った
            {53,"落入陷阱狸！"}, // 落とし穴に落ちた
            {54,"欢迎来到X岛(移民)"}, // 島に移住した
            {55,"相亲相爱！"}, // どうぶつとなかよしになった
            {56,"增加DIY的手册吧！"}, // 集めたレシピの数
            {57,"智能手机生活(+)"}, // スマホを起動した(上級)	智能手机生活
            {58,"敲击岩石的专家"}, // コイン岩を8連打した
            {59,"集里游+让你里数也+"}, // 村活クエストを達成した
            {60,"亲切是很重要的狸！"}, // どうぶつのお願いを聞いた
            {61,"神秘宝藏......？！"}, // ベルを掘り出した	神秘宝藏
            {62,"化石发掘队员认证！"}, // 化石を掘り出した
            {63,"什么样的化石啊？！"}, // 化石を鑑定した
            {64,"挑战捡贝壳"}, // 潮干狩りをした
            {65,"加强岛上景观的活动"}, // 外に家具を置いた
            {68,"森林伐木工"}, // 木からもくざいを出した
            {69,"打招呼是一切的基础！"}, // 村民全員とあいさつをした
            {70,"捡贝壳高手"}, // 貝殻を売った
            {71,"享受采摘水果的乐趣吧！"}, // フルーツを売った
            {72,"捉黄蜂名人"}, // ハチを5連続捕まえた
            {73,"日常生活从制作道具开始"}, // 道具をDIYした
            {74,"手工制作的家具让生活更丰富"}, // 家具をDIYした
            {76,"将回忆留在照片上"}, // カメラで写真を撮った
            {77,"智能手机生活"}, // スマホを起動した(初級)
            {78,"收纳专家就是生活的专家"}, // 家の倉庫に収納したアイテムの数
            {79,"让装饰丰富生活！"}, // 家に飾っている家具の数
            {80,"藏在树叶里......？！"}, // 木を揺すって家具（葉っぱ）を落とした回数
            {81,"水障碍"}, // 風船のプレゼントを撃ち水の中に落とした
            {82,"建造房间的高手"}, // マイホームをリフォームした
            {83,"梦寐以求的家！"}, // マイホームを増築した
            {84,"在布告栏交流！"}, // 自分の島の掲示板に書き込む
            {85,"衣柜里的时尚秀"}, // クローゼットで着替える
            {86,"向流星许愿"}, // 流れ星に祈る
            {87,"岛的象征"}, // 島の旗、島メロを変える
            {88,"别忘了更新护照"}, // パスポートを更新した
            {89,"用“岛屿创作家”设计岛屿"}, // 各地形造成をやってみた
            {90,"要用栅栏围出庭院吗？"}, // 柵を置くハチを5連続捕まえた
        };

        public static string GetName(int index, uint count)
        {
            var dict = Dictionary;
            if (dict.TryGetValue(index, out var val))
                return $"{index:00} - {val} = {count}";
            return $"{index:00} - {Unknown} = {count}";
        }
    }
}

I sent you an email before, but it seems that you didn’t see it.

**Comment by kwsch** [comment]
I've added the translation files for all languages so that you can localize / or improve their description :)

I'll be happy to merge a pull request :)
