### ISSUE TITLE
Changing villagers fills mailbox up?

### ISSUE THREAD

**Issue by klavicegavin** [kwsch/NHSE#16]
If you change any of your village and then write a letter or get something in the mail, it duplicates the first letter you get 299 times until your mailbox is full.

I'd personally love this issue fixed soon as it's kinda frustrating to change an unwanted villager and then try to write to them, only to have your mailbox completely full by the next day. I'd also like to note, this also happens when you get stuff in the mail. It also crashes your game if you open certain duplicate letters.

There IS a workaround to clearing your mailbox at least as I've stated on GBATemp which is open one letter then save immediately. Even so, I just want to write to my villagers.

**Comment by kwsch** [comment]
What commit/build are you using? Builds prior to https://github.com/kwsch/NHSE/commit/65fca3cbba03ccd0891ac3e711ce7464e73f7634 and https://github.com/kwsch/NHSE/commit/7391be7e56fb2bf71095920c4ac736047c9f2c07wouldn't update all references; current commits shouldn't have this issue.

**Comment by klavicegavin** [comment]
I'm using the latest version. And I tried seeing if it was due to leaving my Switch in CFW mode but I changed the day and stilll got it.

**Comment by klavicegavin** [comment]
Update: I deleted all the prior cheats on Atmosphere, and "reset" my village by switching my villagers with a blank one, and then re-
![2020040706555400-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/12589985/78422693-00066a80-7616-11ea-8047-6d32ae7f12c8.jpg)
adding them, but not only is my mailbox full of letters from the same villager, but my fifth villager is now vacant land! What on earth can I do to fix this? It doesn't help that it's almost like it reset my progress for the campground and now there's a camper who I don't recognize there!

**Comment by kwsch** [comment]
Strange how nobody else has reported having this issue.

I'd recommend restoring a backup save file, using the latest version, and not changing villagers manually until more research has been done into the structure of the save file (so that all required values are updated).
