### ISSUE TITLE
EventFlag original string list?

### ISSUE THREAD

**Issue by littlecxm** [kwsch/NHSE#160]
![image](https://user-images.githubusercontent.com/16154023/80934089-2a0ba200-8df9-11ea-8d31-7df790f3fe71.png)
has any exists event flaglist like `.csv`?
if has original japanese list would be help to translate
thanks a lot

**Comment by kwsch** [comment]
If you dump the bcsv files, you can see that the csv contains columns for the 2 things you've screenshotted. I just had the dump spit out the english string and the japanese string; there's really nothing else to help.

**Comment by littlecxm** [comment]
got it. thanks for answer :)
