### ISSUE TITLE
Placing field items (Stone)

### ISSUE THREAD

**Issue by ACmolly** [kwsch/NHSE#162]
I'm trying to use the NHSE to place my stone is specific locations instead of the random 6 locations it has been spawned in. I copied the 4 cells of a current stone, set it into my desired location and reset the stone i copied from. The stone appears fine when i launch the game but it does not work as intended. My shovel goes right through it instead of hitting it. Is it possible there's a current glitch with this function?

**Comment by kwsch** [comment]
"Copied" how? Stones use the Count value to indicate certain things, so if you didn't copy that value, that might be why it didn't work.

The game might be storing collision coordinates for the day somewhere unknown. Could you report back if the new location works the following day? 

I wasn't able to find anything related to Rock/Stone (or an array of "6" objects indicating clangable coordinates). 
https://github.com/Treeki/CylindricalEarth/blob/d120acb8749860f52807325b896f0ab56ef90810/savefile/save_schema_131080_131078_pseudoC.h

Can't really know how to implement any mitigation in NHSE if the mechanics of rock movement aren't known.

**Comment by ACmolly** [comment]
Hi, sorry for using such layman terms. When I mentioned copy, I actually meant using the same exact values of a current stone, set the same 4 pixels onto my desired location, and reset the current stone location so that I will only always have 6 stones on my island. But by doing so, the one that I've set (which contains the same exact values of a current stone) will be glitched in a sense that my shovel will go right through it when I try to hit it. I'm not sure if this is the correct way to move or set the stone. Will get back to you tomorrow to see if it works.

**Comment by ACmolly** [comment]
Hi, just to get back but the stones are still glitched. Not sure if you’ll see this comment though. Would you mind just trying to move the stones around and see if it works?

**Comment by kwsch** [comment]
You'd have to get someone else willing to help; I don't test stuff on my save file :P

**Comment by ACmolly** [comment]
I see. Someone on reddit mentioned it worked for him. Thing is I don’t know the issue or any details regarding how it worked for him only knowing that we did the exact same steps... But thanks anyway!

**Comment by Possum80** [comment]
Using latest build.  No issues duplicating (view, write new stone, and resetting old stone).  Stones works in new location.  However, game will re-spawn the moved stone randomly on map.  Suggesting there's a flag somewhere still to be discovered.  As a result, I've got more than 5 working stones.

**Comment by ACmolly** [comment]
> Using latest build. No issues duplicating (view, write new stone, and resetting old stone). Stones works in new location. However, game will re-spawn the moved stone randomly on map. Suggesting there's a flag somewhere still to be discovered. As a result, I've got more than 5 working stones.

I've managed to find out the issue to this. Placing stones according to the lighter grey grids in the field item editor would cause the stones to be bugged, while placing them in the darker grey grids worked out fine. Gotta check tomorrow to see if an additional stone spawn, not sure if I will encounter what you're currently encountering.
