### ISSUE TITLE
Change starting conditions

### ISSUE THREAD

**Issue by kaolincash** [kwsch/NHSE#164]
It would be brilliant if we could change all starting conditions (except island layout, of course).

What I mean by this is the player's birthday, the starting fruit, the starting flowers, etc.

Specifically I want to change my birthday and fruit, as I reset a lot to get roses on a good island layout but input the wrong birthday, and having played enough of the island to want to keep going it's REALLY bothering me that my birthday is wrong and I don't have the fruit I wanted.

I realise this is a pretty low-priority edge case, but if you have the wherewithal to implement the option, that would be fantastic.

**Comment by kwsch** [comment]
fruit, flowers:
https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_131080_131078_pseudoC.h#L1520-L1527
birthday
https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_131080_131078_pseudoC.h#L306-L314

**Comment by inferno771** [comment]
Was the starting flower setting ever added? I'm not seeing it in the editor.

I was also wondering if it was possible to change the sister fruit and possibly the specialty flower along with village flower when it is added.
