### ISSUE TITLE
Option to edit reactions (ADD - REMOVE) | Edit Player

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#167]
# Option To Modify (Add-Remove) Emotes
### If you need a list of all the reactions: [HERE](https://docs.google.com/spreadsheets/d/13d_LAJPlxMa_DubPTuirkIV4DERBMXbrWQsmSh8ReK4/edit#gid=1275423323)

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by MirayXS** [comment]
damn

**Comment by kwsch** [comment]
Try changing `FillReactionList` in the Achievement editor (line ~31)

**Comment by MirayXS** [comment]
didn't work

**Comment by MirayXS** [comment]
> didn't work, changed the value to 44( all emotes )
> But it edited the value for the nook miles app.

**Comment by MirayXS** [comment]
Thank you so much!!
