### ISSUE TITLE
Hash verification prompts 0x1D6E70: (0x1D6E74-0x4FAD30) after importing a villager's house

### ISSUE THREAD

**Issue by pharo3** [kwsch/NHSE#169]
Hi, as the title says I'm experiencing issues when importing villager houses. Namely the prompt `0x1D6E70: (0x1D6E74-0x4FAD30)` after performing a hash verification.

These are the steps I take in case you want to replicate the error:

1. I load my save on NHSE as usual.
2. After that, I go to the "Villagers" tab and load a villager file (.nhv)
3. The prompt "Imported data did not originate from Villager0 (X)'s data. Update values?" shows up. I select "Yes".
4. Once the villager has loaded, I go to "File" > "Save" [as per this guide on GBAtemp](https://gbatemp.net/threads/tutorial-on-how-to-use-the-nhse-house-editor-for-perfect-villager-injection.563202/).
5. Then I go to "Edit House", click on the first empty house ("???'s house") and change the value within the NPC1 row according to my villager's index number (in this case, "0").
6. The name of the house owner is now displayed properly, so I load its respective house file (.nhvh) and save changes.
7. I perform a hash verification that prompts the following result: `0x1D6E70: (0x1D6E74-0x4FAD30)`.

Is there a way to fix this problem?

**Comment by kwsch** [comment]
Hashes aren't updated until you save changes to all save data.

The option only exists so that you can check a newly loaded save file.
