### ISSUE TITLE
If I change the beach Acres to wipe airport rocks, the sea become static without the waves.

### ISSUE THREAD

**Issue by nokhzz** [kwsch/NHSE#171]
I've changed the two airport acres (left and right) to the 61 or 68 acre id, getting the beach almost perfect without rocks and perfect centering the airport. But then my sea just don't have the waves movement, just the water reflection animation. Already tested with other acres. If I swap the airport ones, the animation is gone too.

Is this a solvable issue? Thanks in advance.

**Comment by kwsch** [comment]
Some acres might not connect well together. All NHSE edits is which acres are where on the map; there isn't anything else to tweak how acres synchronize together.

The game stores an array of acres, and the template that populated those acres. Nothing else :\
https://github.com/Treeki/CylindricalEarth/blob/d120acb8749860f52807325b896f0ab56ef90810/savefile/save_schema_131080_131078_pseudoC.h#L999-L1001
