### ISSUE TITLE
map item editor

### ISSUE THREAD

**Issue by M37R01D** [kwsch/NHSE#172]
the past few updates, when going to map and item editor, the field changed from green where the grass is to all white, and its insanely difficult to see whats going on 
is their a way to change it back to the colors before?

Also is it possible for the inventory and storage, to add a "Set All" button 

Thank you for all the hard work!!

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/NHSE/commit/a9810c7d032b628feb34c2bd748524194517ff0f
