### ISSUE TITLE
Present Box Live Item Injection Issue

### ISSUE THREAD

**Issue by lludu** [kwsch/NHSE#174]
**Is your feature request related to a problem? Please describe.**
When injecting items directly into the game using the "injection" button with the last couple of releases 5/3/2020 +   the items do not inject right and instead i get an inventory full of empty Present Boxes

**Comment by kwsch** [comment]
Leave the Validate checkbox checked, and double check your offset that you're writing to.

Read the wiki.

**Comment by lludu** [comment]
It is checked

**Comment by kwsch** [comment]
> Read the wiki.
