### ISSUE TITLE
Auto upate

### ISSUE THREAD

**Issue by Possum80** [kwsch/NHSE#175]
**Is your feature request related to a problem? Please describe.**
There's frequent updates due to active enhancement and changes.  Users using older version will encounter errors.

**Describe the solution you'd like**
Option to check and download latest version at startup

**Comment by kwsch** [comment]
I'll let someone else develop that functionality and submit a pull request. I'm not interested in implementing that myself.

**Comment by FezVrasta** [comment]
@kwsch could you provide an URL to always download the latest version? That would help to write a small script to automatically update the app at least. Thanks!

**Comment by berichan** [comment]
You can make an Azure API request in the same way [GetNHSE](https://berichan.github.io/GetNHSE/) does it. Source is available here: https://github.com/berichan/GetNHSE/blob/master/scripts.js

**Comment by FezVrasta** [comment]
I wanted to automate it with bash, so having a `/latest` URL would really simplify the script.
