### ISSUE TITLE
How to change the capacity of depot?

### ISSUE THREAD

**Issue by Jennal** [kwsch/NHSE#177]
I have tried to change the Lv of House to Lv.7. Yes, the house become bigger, plenty of rooms. But, the capacity of depot is still 80. How to change the capacity of depot?

Sorry, I mistaken add the label. But I don't know how to remove it..

**Comment by kwsch** [comment]
Storage capacity is already shown in the main window.

**Comment by Jennal** [comment]
@kwsch But I still can't find it in the main window.. I can only change pocket capacity in main window, but not depot capacity in house.
