### ISSUE TITLE
Option to change / edit island star evaluation (1-5 stars)

### ISSUE THREAD

**Issue by OrangePeaches-ARCH12** [kwsch/NHSE#178]
## Can you add the feature to change island's star evaluation? and maybe the options to remove warns (if you could) like when isabelle says "there are too many objects"?

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
