### ISSUE TITLE
Pattern Design Loading

### ISSUE THREAD

**Issue by Zephiriex** [kwsch/NHSE#18]
This is my first time writing stuff on Github, apologies for using preset issue/feature request templates.

**Is your feature request related to a problem? Please describe.**
The issue with importing designs is that on sites like acpatterns.com, files download in .acnl (presumably Animal Crossing: New Leaf?) files.

**Describe the solution you'd like**
Some solutions to this problem are:
A. Have an in-program converter from .acnl to .acnh (probably the harder workaround)
B. Make it so the "Load Design" button in the "Designs" tab also loads .acnl (I tried, it refuses.)
If my 200iq guess as to acnl = animal crossing new leaf is correct, there is an on-website save editor that allows design uploads for new leaf. I'm sure with permission you could ask for the code for that feature.

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/13
