### ISSUE TITLE
Where’s image edit?

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#182]
## I saw that you added image passport edit, but I can’t find the option to change it. Could you tell me how and where I can change?!

**Comment by kwsch** [comment]
Read the [commit message](https://github.com/kwsch/NHSE/commit/60f3fa84a32b53e069b594a6c90ffb357963c093).

> Not allowing people to import a jpeg.

It's prone to abuse if people import images from outside-the-game, and can stand out if someone audited your profile data.

**Comment by MirayXS** [comment]
oh ok thanks for the info!

**Comment by MirayXS** [comment]
I’ll try to load my game with the “made village” stop, I’ll update you
