### ISSUE TITLE
Passport Color Edit

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#185]
# Passport Color Edit
## Passports have different colors. For example, i only know orange and blue, there are other colors too. I only want to ask if you could add an editor to change this value / color.

**Comment by kwsch** [comment]
https://github.com/Treeki/CylindricalEarth/blob/d120acb8749860f52807325b896f0ab56ef90810/savefile/save_schema_131080_131078_pseudoC.h#L541-L557

Can't see anything that sets color.

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by sneedfeedseed** [comment]
I'm pretty sure your Passport's color is supposed to be matched with your zodiac/birthday

https://animalcrossing.fandom.com/wiki/Zodiac_star_fragment

Like for example if my birthday was July 23rd which is Leo that'd make my passport Light Green and if my birthday was December 15th which would be Sagittarius my passport would be Light Blue I could be wrong, but to test out try setting your birthday to a different date and see if the color changes

**Comment by MirayXS** [comment]
You right! My sign is Capricorn so my star fragment is a red-orange so is my passport color red-orange? Yes! Thanks for the info
