### ISSUE TITLE
CJK chars in Player Name or Town Name appeared as square  in Linux mono

### ISSUE THREAD

**Issue by freefrank** [kwsch/NHSE#187]
**Is your feature request related to a problem? Please describe.**
CJK chars in Player Name or Town Name appeared as square  in Linux mono.
But the island name on title bar displays correctly.

**Describe the solution you'd like**
Could be different font used in Player Name and Town name section that is not present under Linux.
In windows all fields are displayed correctly.
The characters are displayed as square not unreadable code could mean that its font issue, where its not fallback correctly to CJK compatible font as im using English locale linux. 

**Describe alternatives you've considered**
Nothing yet. May try to install windows fonts later if its not solved.

Once more, the Edit Items section are not displayed currectly neither.

![nhse_bug2](https://user-images.githubusercontent.com/726115/81490694-7a905e80-9242-11ea-8853-b733b46395a6.png)
![nhse_bug](https://user-images.githubusercontent.com/726115/81490697-7cf2b880-9242-11ea-9b53-f3c649d73e8c.png)

**Comment by kwsch** [comment]
NHSE doesn't use any special fonts, only the built-in ones with Windows Forms. I'm assuming this is a Mono specific configuration issue when loading the `Microsoft Sans Serif, 8.25pt` font data for certain glyphs.

It's not really a NHSE issue. I don't think that providing a special font file would be the right fix -- it's a compatibility/configuration quirk with mono that I don't know how to solve on your end besides [random stackoverflow suggestions](https://stackoverflow.com/questions/17391758/mono-winforms-and-unicode-characters). You can try copypasting the text to an external editor and pasting it back in, but besides that idk :\
