### ISSUE TITLE
House Dump erroneous file size

### ISSUE THREAD

**Issue by CecilFF4** [kwsch/NHSE#188]
Running commit 000da2c on 1.2.0 ACNH main.dat. Dumped house data from "Villager House Editor" and got a file of size 0x26400. When trying to import, either that very dump or an altered one, it says:

> Cancelling:
> The size of the imported file (0x26400) does not match the required size (0x1D4).

**Comment by kwsch** [comment]
Player Houses are 0x26400, Villager Houses are 0x1D4. Don't mix the two files.

**Comment by CecilFF4** [comment]
> Player Houses are 0x26400, Villager Houses are 0x1D4. The two house types can't be used interchangeably 

There is no option to select where to load the dumped file into. Selecting a player house and then clicking to load that same player house's dump creates that error. Not a closed issue, but maybe a GUI one because there isn't an option to specify where to load the file?

**Comment by CecilFF4** [comment]
Thanks! Tested and seems to work great now. Awesome work!
