### ISSUE TITLE
Editing Catchphrase Won't Work

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#189]
# Editing Catchphrase Won't Work

**Comment by kwsch** [comment]
Probably requires an amount of friendship, otherwise it falls back to the default.

If the data doesn't have the old catchphrase, then there's nothing that NHSE can do (with the current amount of research).

**Comment by MirayXS** [comment]
Oh yeah, nhse shows blank catchphrase for every villager

**Comment by MirayXS** [comment]
Hey, this is an update about this issue
I updated the edited villagers catchphrases by talking to Isabelle. Now the catchphrase of the villagers are the "perfect" catchphrase (es. Octavian said something like "Aloha" now he says "Perdindi" wich is his catchphrase) just saying i fixed :D
