### ISSUE TITLE
Overwritten tailor designs are still being copied by villagers

### ISSUE THREAD

**Issue by Azulyter** [kwsch/NHSE#191]
This is a continuation of issue #184. I had saved custom designs inside Able Sisters, without realising villagers wear the designs placed there. I tried overwriting these custom designs with the default ones, by dumping and restoring them from an old save file. However, villagers are still copying my custom designs even though they're no longer in the tailor's.

**Comment by kwsch** [comment]
Villager data caches a copy of whatever design they are are wearing so that the source data may be changed.

https://github.com/Treeki/CylindricalEarth/blob/d120acb8749860f52807325b896f0ab56ef90810/savefile/save_schema_131080_131078_pseudoC.h#L951-L976

**Comment by Azulyter** [comment]
Complaining to Isabelle clears this doesn't it? My villagers are getting the custom designs again even after complaining.

**Comment by Azulyter** [comment]
I replaced the designs saved in the villagers' data with blank patterns and this seems to have solved the issue. I guess complaining to Isabelle _doesn't_ reset the saved patterns, but this wouldn't make sense as complaining is meant to reset all clothing to default. Maybe this is an oversight from the devs?
