### ISSUE TITLE
Reset clothing/furniture for villagers to default

### ISSUE THREAD

**Issue by Azulyter** [kwsch/NHSE#192]
**Is your feature request related to a problem? Please describe.**
Continuation of #191. To summarise, I've been trying to remove clothes that villagers obtained via patterns at Able Sisters. Complaining to Isabelle at Resident Services failed to do this. Using the save editor to overwrite designs saved to villager data causes them to wear the blank designs.

**Describe the solution you'd like**
An option in the save editor to clear any extra clothing options from villagers, and potentially furniture.

**Describe alternatives you've considered**
I've tried using features added in response to prior reports, such as resetting the tailor patterns and overwriting the designs cached in villager data. Neither of these stopped villagers from using custom patterns altogether.

**Comment by kwsch** [comment]
> An option in the save editor to clear any extra clothing options from villagers, and potentially furniture.

How exactly will this be implemented? What data needs to be changed?

From the issue template:

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by Azulyter** [comment]
I was thinking something along the lines of a "clear all" button that deletes any additional clothing options. I'm assuming there's a flag which causes villagers to wear custom designs. Since I'm fairly inexperienced when it comes to coding I'm not sure how to find what's causing the problem specifically.

**Comment by kwsch** [comment]
Again, things that *require research* are not Feature Requests. I'm not an all-seeing oracle with complete understanding of all game mechanics and how the game uses the saved data.

Until someone figures out how to accomplish what you want to do, nothing can be implemented in the program.

https://github.com/Treeki/CylindricalEarth/blob/d120acb8749860f52807325b896f0ab56ef90810/savefile/save_schema_131080_131078_pseudoC.h#L951-L992

The game has tons of things that can be adjusted. I don't have the time to research every single request, so I only work on things that are either fleshed out by the community or things that actually interest me.

**Comment by Azulyter** [comment]
I have 2 villagers on my island. One of them is wearing a custom design and I want to get rid of it. The other villager isn't wearing one. The villager _without_ the custom pattern has a blank design when trying to view it via the save editor. I backed this up, then restored it on the villager _with_ the custom pattern. Instead of them losing the ability to wear custom designs, the villager is now wearing the blank design as a shirt.

**Comment by Azulyter** [comment]
I just realised I could get backups of my villagers from a date before I added the custom designs, and that should solve my issue. Thanks for your help.
