### ISSUE TITLE
Item Injection

### ISSUE THREAD

**Issue by stangwsn** [kwsch/NHSE#194]
Hello! I'd just like to know if there's any wiki link for injecting items tutorial, since the one I've found in there I can't understand it.
Thanks!

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection

You're expected to install sys-botbase and get your console's IP address. Then you can follow the tutorial on the wiki.

Similar to how dumping a save file is irrelevant to NHSE operation, installing sysmodules is irrelevant as well.
