### ISSUE TITLE
Town Hall Can't move

### ISSUE THREAD

**Issue by Chaos192** [kwsch/NHSE#195]
So my save was broken and unable to advance so a friend gave me their save which I used to fix it. I overwrote my island with theirs via importing it, setting all flags etc to what they had in their save etc. Now the town plaza that is below the town hall is in the original location it was on my island and there is no way to move it in the save editor. Is there potentially a way to update the save editor so that when you export out the terrain etc data it also saves that and loads it when importing? Or add a feature to manually move that ?

**Comment by kwsch** [comment]
Already exists. Change the Plaza Location.

![image](https://user-images.githubusercontent.com/6393368/81585501-1ddb9380-9369-11ea-8e67-a19031694709.png)

Buildings, Terrain, Acres, and Field Item layers are all separate from the 2 plaza coordinate values. All of the raw dumps for NHSE are just subsections of the save file -- nothing custom.
