### ISSUE TITLE
Clarification on Inventory Editor

### ISSUE THREAD

**Issue by dinosaw** [kwsch/NHSE#196]
Thanks for your work so far on this.

I was curious on how exactly the Inventory Editor works. For example, I'm a bit confused because the items do not appear to be sorted in any manner that I can determine. It doesn't appear to be alphabetical, or by type/group considered by the game itself. Additionally, it's not in the order visually of how it is seen in-game (opposite of how the pockets in NHSE do visually show themselves as such in-game). How exactly is this sorted? I ask because, for example, when I load up a save, I have multiple stacks of wood that show up side by side in-game, however in the Inventory Editor, they appear randomly and not next to each other.

I am also curious if the Inventory Editor should be limited to 1,600 slots since that is the most you can have in the game. It looks like currently, there are 5,000(?) slots I can add items to. Does that mean I can actually add up to 5,000 items via NHSE and they will show up in-game as well? Or will it only show up to 1,600?

Thanks!

**Comment by MirayXS** [comment]
I don’t understand what you mean. I don’t have any problems with the item editor.

**Comment by MirayXS** [comment]
You mean the pockets?

**Comment by MirayXS** [comment]
If you mean pockets, there are more pockets slots you can unlock in future..

**Comment by dinosaw** [comment]
I wouldn't say it's a *problem* as it works fine, but no, I mean the *Inventory Editor*. You open it by going to Edit Player -> Edit Storage.

This image is an example of how I cannot determine the sorting. As you can see, there are two stacks of clay and two stacks of stone, however they aren't side by side but appear randomly in slots.

![img](https://i.imgur.com/WFkMoUY.png)

**Comment by MirayXS** [comment]
OHH you mean the STORAGE, well I think it’s normal and it won’t affect ur game ( the sorting I mean)

**Comment by dinosaw** [comment]
I'm not concerned about it affecting the game, as I stated, it works fine. Let's allow the developer to provide their input.

**Comment by kwsch** [comment]
The game auto-sorts when displaying in-game, but stores the data by order of deposit or something.

**Comment by dinosaw** [comment]
Ah understood. Thanks for confirming. Additionally, do you know if when storing more than 1,600 items in your inventory via the save editor if those items beyond the 1,600 mark are loaded?

**Comment by kwsch** [comment]
The game caps out per the Storage Count saved in the save file.

If the game does not increase above 1600, they still can in future patches expand to 5,000 per what the save file allows.

**Comment by dinosaw** [comment]
Awesome, thank you for clarifying. I'll go ahead and close this out, but it would still be cool to see if you could implement the same sorting in the save editor that the game does on load. If not, that's fine too, just happy to have an editor.
