### ISSUE TITLE
Can't see Item Sprites / Images

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#197]
# Can't see Item Sprites / Images
## I'am Using the latest NHSE version
![image](https://user-images.githubusercontent.com/55494819/81593951-77bb7800-93c0-11ea-86e8-e4bba8ae2e44.png)
![image](https://user-images.githubusercontent.com/55494819/81593974-81dd7680-93c0-11ea-9147-78c3c0777bc9.png)

**Comment by kwsch** [comment]
You have to provide images yourself in the corresponding folder.

**Comment by MirayXS** [comment]
Ohhh could you tell me which name should I name the folder ??

**Comment by MirayXS** [comment]
Like some examples if you don’t mind

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/wiki/Item-Editing
