### ISSUE TITLE
How do this work ?

### ISSUE THREAD

**Issue by LunaryUStyle** [kwsch/NHSE#2]
Hello, I just don't understand how do this work, it's on the switch or on the computer ? And how do i launch it ? Can you do a release ?

**Comment by architdate** [comment]
You can download the release from the azure devops CI (click the green checkmark)
This is done on the computer, you would need to extract your save file using JKSV and then edit it via NHSE

**Comment by LunaryUStyle** [comment]
azure devops CI ?

**Comment by architdate** [comment]
Look at the top of the repo (the description)

**Comment by MirayXS** [comment]
@berichan made a website (#343) that pulls the latest build from Azure DevOps using the Azure REST API.
It's a easy way to download the latest NHSE version.

<a href="https://berichan.github.io/GetNHSE">Page that links a direct download of the latest commit</a>
