### ISSUE TITLE
Change critterpedia information.

### ISSUE THREAD

**Issue by agbgt** [kwsch/NHSE#20]
This isn't related to any problem, it's more of a suggestion. I'm sure you've thought of this, but it'd be really useful to be able to edit the critterpedia of a villager since spawning in the fish/bugs doesn't fill in the critterpedia at all.

**Comment by kwsch** [comment]
Use the **Edit Received Items** button.

**Comment by agbgt** [comment]
> Use the **Edit Received Items** button.

That's not a button that exists in the save editor. When I open the editor, I only have the "Edit Items" button.

**Comment by kwsch** [comment]
Stop using outdated builds.
