### ISSUE TITLE
#20200512.7 unhandled exception when loading a .nhvh

### ISSUE THREAD

**Issue by MZ-4** [kwsch/NHSE#201]
As the subject says, when I try to load a .nhvh file to adapt a changed villager's house (Edit House ->Load) it throws an unhandled exception. Tried 3 different villager/houses (both matching of course) to confirm.
My last download 20200511-1 is good.

**Comment by sneedfeedseed** [comment]
I get this problem too, however it seems to work no problem with the older versions of NHSE.

**Comment by MZ-4** [comment]
Seams to be introduced with 0512-2.
0512-1 is good.

**Comment by GamerKarl** [comment]
i confirm there is a problem

**Comment by kwsch** [comment]
closed by https://github.com/kwsch/NHSE/commit/755a7d773b22d5e4a946140b527029ac32392386
