### ISSUE TITLE
Flowers have properties of placed items - Field Editor

### ISSUE THREAD

**Issue by GenjiTheAssassin1** [kwsch/NHSE#205]
When you place flowers down using the Field Items setting, the flowers have the same properties as items. They can not be dug up or damaged by the player.

**Comment by kwsch** [comment]
Are they hacked flowers?

Could be that you don't have the correct Flag0/Flag1 values, which prevents pickup.

**Comment by GenjiTheAssassin1** [comment]
Yes, they are hacked flowers placed via the field items editor. I've crossed checked them with legit flowers and the flags match up. However, the flowers still behave like objects, I'll try to remove the flowers and try again. Thanks for the help.

**Comment by GenjiTheAssassin1** [comment]
update: I have tried adding flowers with different settings applied. All turned out the same, behaving like placed furniture. The flags from the legit flowers are the same as the hacked ones, so I do not understand what can be going wrong. To add on, this problem was not present in previous builds of NHSE.

**Comment by kwsch** [comment]
I'm assuming this is related to https://github.com/kwsch/NHSE/issues/162

Not sure if it's due to editing a save and resuming it for a date-change (save on monday, edit, inject & play on tuesday), or if it's related to not-a-date-change (save and edit and play on same day).

**Comment by GenjiTheAssassin1** [comment]
I've looked into issue #162, however, I do not believe the two are related. I think I have saved on Monday and resumed on Tuesday at like 12. Do you believe that is the problem and if so, are there any fixes?

**Comment by kwsch** [comment]
No idea, tbh.

**Comment by ACmolly** [comment]
I've managed to make the stones work (referring to #162 ). I realized that you'd have to place the items in certain grids. For eg, when editing field items, in the grid there's a darker grey and a lighter grey colored lines. For stones, it only works if you use the grids according to the darker grey lines, placing stones worked perfectly fine like this. However, if I were to place the stones according to the lighter grey lines, it bugs out and I can't damage it. Try looking at your flowers (how it is placed originally, according to dark or light grid) and then place accordingly. It should work fine.

**Comment by GenjiTheAssassin1** [comment]
Thank you very much, I'll try it.

**Comment by GenjiTheAssassin1** [comment]
Ok, that seemed to do the trick, thank you guys so much for the help!

**Comment by kwsch** [comment]
Thanks for reporting back :)

Think of the map view as a 16x16 grid with half coordinates, for a total of 32x32. The darker lines indicate the 16x16 grid, while the lighter lines indicate the 32x32 grid. Keep the field items inside the 16x16 grid, rather than at the half-coordinate spots.

**Comment by GenjiTheAssassin1** [comment]
Ok, I'll keep that in mind. Thank you!
