### ISSUE TITLE
Restored save not recognized after replacing villager and home

### ISSUE THREAD

**Issue by biddoof** [kwsch/NHSE#206]
I've been trying for 2 days to make this work but when I launch the game at the end of the process, the game starts at the beginning as though there were no save, asking me to create a new character.

I use JKSV to extract the save (tried both atmosphere/emuMMC as well as cfw/SYS) edit it in NHSE exactly as the guide says, then use JKSV to restore the edited save - but the game doesn't recognize a save. No error messages, just starts from the beginning.

I'm running the current version of the game, ofw, etc., most recent version of NHSE (I wondered if this was part of it - maybe NHSE is now bugged - and I'm not seeing others with the same issue)

My test is to replace a villager (Blaire, slot 7) with a villager from the dump file (and house). I'm testing with Raymond (obviously).

I've also tried to just switch the villager through the interface to see if maybe the dump files were the problem, but the same thing happens.

I've made other non-villager edits using this process (JKSV to backup and restore, NHSE to edit) with no issues. Game recognizes edited save, and the edits came through (items).

One weird thing - I can load the save on pc emulator (ryujinx) - it complains that the save data is from a new user and asks if I want to restart or use the new player. It resets all friend data but the save loads.  If I then save the game in the emulator, I can get it to load on the switch (cfw/sys). The game complains again that the save data is from a new user etc.. I can launch the game but all my friend data is removed.

All tests have been done with no wifi + airplane.

I've spent so many hours trying things I figured I'd just ask. I asked on the gbatemp also but no responses so far.

**Comment by kwsch** [comment]
Unrelated to NHSE.

Be sure you're importing the correct files (encrypted save file, not decrypted dumps) with the correct names (no renaming or bak files present).

**Comment by biddoof** [comment]
Files are direct from JKSV into NHSE and back, no file names changed. I assume NHSE saves are encrypted, I don't decrypt or do anything unusual. I'm trying the simplest possible version to figure out the problem. If NHSE save is correct, then it must be in the transfer, but I'm not doing anything unusual there either. I don't use ftp to transfer - just windows and an sd reader - copy paste into clean folders. 

Thanks anyway for the response, appreciate the tool, it's awesome. Back to the brick wall.
