### ISSUE TITLE
Field Item toggle

### ISSUE THREAD

**Issue by Possum80** [kwsch/NHSE#207]
**Is your feature request related to a problem? Please describe.**
Need to reset a field item before I can set a new field item.  If I want to change rows of flowers or trees, I need to reset each one, then set each and every one again, involving a load of right mouse clicks.

**Describe the solution you'd like**
A toggle to change cursor to read (view), write (set) or erase (reset), thereby single left mouse click to erase or write the field item.

**Describe alternatives you've considered**
Write (Set) will overwrite field item, and thereby reducing one set of clicks to erase (reset) items.

**Comment by kwsch** [comment]
Per the wiki: 

![image](https://user-images.githubusercontent.com/6393368/81769906-99d1fa80-9493-11ea-89d5-4b56925cb9c3.png)

You can just control/shift/alt left-click to single-click tiles.

You can also turn off the `Prevent Writing Occupied Item Tiles` if you want to overwrite an item with a same-sized variant.
