### ISSUE TITLE
Change birthday

### ISSUE THREAD

**Issue by VegaTF** [kwsch/NHSE#21]
Not a Issue but, can you pls add a "change birthday" option? People who is playing Ryujinx emulator need to use a save file to play and only need to change the birthday hahaha (sorry)

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by SolderSoldi3r** [comment]
I hope this feature will come soon.

Thank you for your hard work
