### ISSUE TITLE
Changing villager problems

### ISSUE THREAD

**Issue by boodeebuddy** [kwsch/NHSE#211]
When I try to change villagers, they still have the same outfit and home as the old villager. I can change the outfit by talking to Isabelle, but i can't find any solution for the house issue, tried moving the villager using the help of tom nook's service but still the same old house.. haven't tried changing the roof, wall, door, interior, etc manually because I don't know what is what

**Comment by boodeebuddy** [comment]
for example when I change Audie to Raymond, Raymond will wear Audie's outfit and live in the same house exterior and interior as Audie

also tried changing the villager when they about to move in to a plot, also didn't work for fixing the house issue

**Comment by kwsch** [comment]
Be sure that you're using the latest build. The NPC1 value of the villager house must indicate which villager inhabits it. NHSE automatically updates the value to match the previously present house's value.

**Comment by boodeebuddy** [comment]
thank you for the response! the NPC1 value is already correct and they inhabit the "correct" house. what I'm having problem is changing the houses exterior looks because each villager have a unique house to their own

for example,

this is what Audie's exterior looks like
![animal-crossing-new-horizons-guide-villager-house-exterior-audie-trim-305x318](https://user-images.githubusercontent.com/65295726/81828137-091b1d80-956c-11ea-9288-3f82e8ecc79d.png)

and if you change Audie to Ankha, the house exterior and interior will still be the same as Audie's when Ankha's house exterior looks like this 

![animal-crossing-new-horizons-guide-villager-house-exterior-ankha-trim-305x313](https://user-images.githubusercontent.com/65295726/81828360-4d0e2280-956c-11ea-98a6-56a63b5b3c82.png)

sorry if I'm bugging you, thanks for the amazing save editor so far!

**Comment by boodeebuddy** [comment]
in the NHSE it refers to WallUniqueID, RoofUniqueID, and DoorUniqueID
