### ISSUE TITLE
Field Item Editor - Remove from View Holding shift

### ISSUE THREAD

**Issue by jedl1012** [kwsch/NHSE#212]
**Is your feature request related to a problem? 
The remove from view option is not working on the field item editor.

**Describe the solution you'd like**
you can delete an item by cliking it on the map holding the shift button to set none on the field.

**Comment by kwsch** [comment]
Already exists; use the correct hotkey/modifier [per the wiki](https://github.com/kwsch/NHSE/wiki/Field-Item-Editor):

![image](https://user-images.githubusercontent.com/6393368/81843216-21eee900-9502-11ea-8080-c5fc8c16e4f6.png)

CTRL: View
SHIFT: Set
ALT: Delete

**Comment by jedl1012** [comment]
thank you.
