### ISSUE TITLE
Problem with storage layout

### ISSUE THREAD

**Issue by justpassingby2** [kwsch/NHSE#219]
![image](https://user-images.githubusercontent.com/65371532/81989927-ba20c700-9603-11ea-8ab9-d12ea19f62e0.png)

The layout in previous builds used to show the correct items in the storage. But it now shows random stuff. It doesn't show up real items.

**Comment by kwsch** [comment]
Your save file was damaged by a bad RAM write (cheat code).

**Comment by justpassingby2** [comment]
I don't think that's the case. I've deleted the FULL game, all saves, and started a new game, used that one and still doesn't work. I still have the build from May 4 and that one works perfectly fine.  I saved the game with JKSV

**Comment by kwsch** [comment]
Thanks for reporting! Not many people are still using the release version of the game, so I never bothered checking the older versions.

**Comment by justpassingby2** [comment]
> Thanks for reporting! Not many people are still using the release version of the game, so I never bothered checking the older versions.

I solved the issue. The game has to be updated. If it isn't, it will corrupt their data. That's why it worked with a previous version of NHSE and not the new one.

**Comment by kwsch** [comment]
No, it was NHSE not reading from the right offset for v1.0 games. I fixed the offset read, and the old v1.0 save files read fine now.

**Comment by justpassingby2** [comment]
Oh. Nice. By the way, awesome job with NHSE.
