### ISSUE TITLE
Adding Fish dont count to milestones. 

### ISSUE THREAD

**Issue by defelper** [kwsch/NHSE#22]
I added a StringFish to my inventory and sets this to the critterpedia but it didn't count to milestones. Is there any option?

**Comment by kwsch** [comment]
Milestone modification is undocumented.

**Comment by defelper** [comment]
Hi @kwsch . Thanks for the hard word programming this editor. I don't know if this help but I managed to found and edit my save to get the milestone by your dump tool. I giving the position of Fish Milestone, you may have seen it, but here we go: 

![image](https://user-images.githubusercontent.com/3076570/78102043-ac9adf00-73bf-11ea-9f03-4d10c2b72485.png)

**Comment by kwsch** [comment]
@defelper refer to latest commit :) https://github.com/kwsch/NHSE/commit/98a98f5cf47b9964551a98e1fe719b319f511bb0

should provide a gui to match.

the activities should match these: 
[EventFlagsPlayerActivityParam.zip](https://github.com/kwsch/NHSE/files/4413248/EventFlagsPlayerActivityParam.zip)
