### ISSUE TITLE
Edit save file date 

### ISSUE THREAD

**Issue by ChaoticKnight** [kwsch/NHSE#220]
**Is your feature request related to a problem? Please describe.**
So I changed SD cards and notice too late that my switch was on march 2018 and saved. Would it be possible to edit the save date of the file so I can go back to the future without the consequences of weeds, angry villagers and nooks cranny upgrading? 

**Describe the solution you'd like**
Edit the time of the save file so it doesn't notice the time travel. 

**Describe alternatives you've considered**
If not that maybe it would be possible to change a flag in the villagers and nooks cranny to prevent the consequences of time traveling. 

**Additional context**
-

**Comment by kwsch** [comment]
The program uses the LastSavedTime in the program title.

You can dump your decrypted save and hex edit at 0xACE9F8 to change the date.

YY YY MM DD HH MM SS (all in hex).

**Comment by ChaoticKnight** [comment]
I tried that, the program indeed tells me the new date, but after restoring the file the villagers still say it's been 2 years and there are too many weeds

**Comment by kwsch** [comment]
If that didn't work, then I dunno how it can be edited to make the game recognize it.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by ChaoticKnight** [comment]
OK I'll have to go back the hard way, thank you so much for taking the time to answer
