### ISSUE TITLE
Change island flower?

### ISSUE THREAD

**Issue by Soorily** [kwsch/NHSE#221]
Hi! I was wondering if changing the island flower could potentially be added to the save editor. The island flower affects what type of flower seeds are available in the shop all the time. My friends and I don't have anyone who has lily flower seeds available in the shop. They aren't comfortable asking me to give them seeds all the time and would prefer being able to buy the seeds themselves if possible. Thank you!

**Comment by kwsch** [comment]
Already exists in NHSE.

Edit Map... -> Field Goods.

**Comment by Soorily** [comment]
Thanks for guiding me to that section of the save editor. Unfortunately I don't quite understand how the values correlate to what specific flower/fruit I'm trying to set as the native one. I'm also confused by the terms 'specialty' vs 'village' vs 'sister'. Is there somewhere that would have that information?

**Comment by Soorily** [comment]
Thanks for guiding me to that section of the save editor. Unfortunately I don't quite understand how the values correlate to what specific flower I'm trying to set as the native one. I'm also confused by the terms 'specialty' vs 'village'. Is there somewhere that would have that information? I was able to find information about how to set the native fruit but not the native flower :(

**Comment by Soorily** [comment]
I tried modifying the "SpecialtyFruit" value in my save editor and it had no effect. It did save, but the game doesn't register a change. Does changing the native fruit not affect the passport or store? I also tried changing the numbers for the 'VillageFlower' and 'SpecialtyFlower' as well just to see if I could guess what number I needed but changing those values also had no effect in the shop.

**Comment by kwsch** [comment]
Shop inventory is likely set in stone for the entire week; you might want to try timetraveling to the next week (starts on Sunday).

**Comment by Soorily** [comment]
Ohh okay! Thank you. I will try the time travel.

**Comment by Soorily** [comment]
I tried the time travel and the change for the flowers worked! Thank you :) However, the fruit still remained. I did see that it changed from the native fruit though because the normal buy price of 400 went to 2,000 when I tried to change the fruit. I guess the fruit is stuck in the shop!
