### ISSUE TITLE
Color to Variation Name

### ISSUE THREAD

**Issue by alymcmurray** [kwsch/NHSE#223]
When selecting an item, now we see the color and corresponding flag/count to use to obtain it (which I am very thankful for now). However, for some items, the colors are identical and it is "impossible" to know which one is which without visiting an outside source. I propose changing the colors to the variation name, as found in the ACNH spreadsheet project. 
https://tinyurl.com/acnh-sheet

If there is some way I can assist with this, I would gladly help. 
I do not know c# specifically but I am a programmer so if you point me to the file that this information is found, I can update it and do a pull request.

**Comment by kwsch** [comment]
Notes: Would likely need localization for the supported languages --

Body Part Name: STR_Remake_BodyParts.msbt
Body Part Color: STR_Remake_BodyColor.msbt

Fabric Part Name: STR_Remake_FabricParts.msbt
Fabric Part Color: STR_Remake_FabricColor.msbt
