### ISSUE TITLE
Allow multi select tiles on map editor

### ISSUE THREAD

**Issue by Darkaim63** [kwsch/NHSE#224]
**Is your feature request related to a problem? Please describe.**
I think it would definitely be a quality of life improvement for people who want to do bulk map editing

**Describe the solution you'd like**
Make it so you can hold a key and drag or use arrow keys to multi select tiles to allow for bulk editing

**Comment by kwsch** [comment]
You can already use hotkeys to view / set / delete an item with a single mouse click; I'm not aiming to make a Decorating Editor emulator...

If someone makes a pull request with these advanced features, then I'll consider it; otherwise, I don't think it'd be much value added vs my-time.

**Comment by Darkaim63** [comment]
> You can already use hotkeys to view / set / delete an item with a single mouse click; I'm not aiming to make a Decorating Editor emulator...
> 
> If someone makes a pull request with these advanced features, then I'll consider it; otherwise, I don't think it'd be much value added vs my-time.

How do you set up the hotkeys?
