### ISSUE TITLE
Villagers' houses

### ISSUE THREAD

**Issue by EllairJulie** [kwsch/NHSE#225]
I don't know if it's just me, but it's very confusing for me to change the exterior of the villagers' houses. I never change in the right way.

Is it possible to include a preview of the changes made outside the villagers' houses? Or a guide that illustrates the options?

**Comment by kwsch** [comment]
I'm not going to collate an imageset of what each option looks like. NHSE exposes the options for editing; including house images would bloat the executable size dramatically.

**Comment by EllairJulie** [comment]
Ok... no problem :(
But if there is a way to identify which code corresponds to which wall/roof, please let me know.

Sorry for my english... google helped me
