### ISSUE TITLE
Display flower details directly on the field item map

### ISSUE THREAD

**Issue by Thealexbarney** [kwsch/NHSE#226]
**Is your feature request related to a problem? Please describe.**
In the field item editor viewing the layout and genes of flower fields requires clicking separately on each individual flower, making it difficult to get an overview of how flower breeding is going and spot mistakes

**Describe the solution you'd like**
An option to display flower genes and maybe color and type in the main field editor view

**Additional context**
My specific use case is viewing the genes in my flower fields to monitor breeding progress.

**Comment by Thealexbarney** [comment]
Could you also use the 3 extension squares to have more display space?

**Comment by kwsch** [comment]
Solid: Both Genes
Semi-Solid: Single Gene
Empty: No Gene

Image of what it looks like:
![image](https://user-images.githubusercontent.com/6393368/82241222-9950be00-98f0-11ea-8bdd-97912d7beaf1.png)

**Comment by Thealexbarney** [comment]
Looks great. Thanks!
