### ISSUE TITLE
Count changes variation instead of flag, which wiki says.

### ISSUE THREAD

**Issue by YoshiFan501** [kwsch/NHSE#227]
No clue if this is a wording or coding error. But for items like a rattan table that have different colors, you set them by increasing the count instead of the flag dials. So let's say a count of 0 was black. I set it to 3 and it was white.

**Comment by kwsch** [comment]
The Wiki has been updated to state that the "Count" NumericUpDown control determines the variation rather than "Flags".

Thanks for reporting :)
