### ISSUE TITLE
How can I edit visitors on the island?

### ISSUE THREAD

**Issue by amo0725** [kwsch/NHSE#228]
I cant understand those array...pls help and thx for the editor :)

**Comment by MirayXS** [comment]
what u need help with

**Comment by amo0725** [comment]
I don’t know how to edit the visitor, which array should I edit? If I want flick to come now.....

**Comment by MirayXS** [comment]
Ohh idk same, wait for the developer to answer..

**Comment by MirayXS** [comment]
I would also want to know how to get Redd through the editor

**Comment by amo0725** [comment]
Haha everyone has the same problem😂

**Comment by kwsch** [comment]
The game stores an entire week's worth of visitors. Index 0 is Sunday.

Change the `VisitorNPC[] Array`.
