### ISSUE TITLE
Villager House Editor Error

### ISSUE THREAD

**Issue by DrakanShadow** [kwsch/NHSE#229]
![Villager House Editor Error](https://user-images.githubusercontent.com/65447859/82118028-4547ad00-9729-11ea-8803-988d18700d40.png)
Started happening recently when trying to load villager House. I get error now even on older saves that use to not get error.

**Comment by kwsch** [comment]
Was fixed days ago.

https://github.com/kwsch/NHSE/issues/201

**Comment by DrakanShadow** [comment]
Thanks, guess I missed it.  Tried browsing through first seeing if it was fixed. Again thanks for all the work you do.
