### ISSUE TITLE
Villager files

### ISSUE THREAD

**Issue by agbgt** [kwsch/NHSE#23]
I think it might be useful if you could offer a repository of all the villager files so we could load them up in the save editor. I'm not sure, but that might fix the house bug.

**Comment by kwsch** [comment]
Curation of files is unrelated to the development of the program; other parties are free to create and curate their own lists of downloadable data.

Supporting databases are not a [core concern](https://en.wikipedia.org/wiki/Core_concern) of this program, as they are not required for the program to function.
