### ISSUE TITLE
Program Crash when trying to set a rock 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#232]
literally what's written in the tilte, the program stop working after trying to put a stone/rock in the map

**Comment by kwsch** [comment]
Unable to replicate; please list the steps/illustrate how to produce said error.

**Comment by MirayXS** [comment]
what? i tried earlier making the "rock garden" (?trend?) and it worked fine

**Comment by Possum80** [comment]
Make sure you copy and place rock on the dark larger squares.  Earlier builds had a bug where if the rock was set off the large square, it would just show in game but is not interactable (cannot hit it)

**Comment by GamerKarl** [comment]
> what? i tried earlier making the "rock garden" (?trend?) with the editor and it worked fine

I literally try doing it and the program just stop working :c 


> Make sure you copy and place rock on the dark larger squares. Earlier builds had a bug where if the rock was set off the large square, it would just show in game but is not interactable (cannot hit it)

can you show me how to do it?

**Comment by Possum80** [comment]
View the rock you want to move, go to the location you want the rock to be, right click and use set command.  Just got to make sure the rock is in a darker 4x4 grid space, and not offset by a square in either up or down.  Earlier builds had a bug where if the rocks are not in the dark 4x4 grid, it becomes inactive.
