### ISSUE TITLE
Town and name change for Japanese treats player as newcomer using editor version #20200521.3

### ISSUE THREAD

**Issue by Darkaim63** [kwsch/NHSE#237]
![unnamed (1)](https://user-images.githubusercontent.com/13300875/82536252-089afd80-9afd-11ea-8cf9-ffcfb3880ee0.jpg)

"Hey, what's your name? ... I see, so you say your name is Koki"

This is after town AND name change, I'm thinking changing the town name is what messed it up.

**Comment by Possum80** [comment]
Changing name of island will make you a 'villager'
