### ISSUE TITLE
Feature Request: Island designer permit editing

### ISSUE THREAD

**Issue by SquirrelKiev** [kwsch/NHSE#24]
Hi, 
I don't know how difficult this would be, but the ability to unlock permits through the save editor would be really nice, as for some reason the ability to buy them isn't in my nook miles stop, even though I have the app. Hope this can be done.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
