### ISSUE TITLE
View/Edit Weekly Weather

### ISSUE THREAD

**Issue by brettsmods** [kwsch/NHSE#240]
Is it possible to view or edit the weekly weather (specifically when it is going to rain)? I know this data is generated on a Sunday along with the rest of the weekly data and follows a schedule for the week (as the TV channel can forecast the next day's weather and if you time travel to the same time, it will always have the same weather).

I'm not sure how it's stored in the save but this would be a great feature!

**Comment by kwsch** [comment]
https://github.com/Treeki/CylindricalEarth/blob/685a2b7f24816eb8da871736250399fc27e012af/savefile/save_schema_131080_131078_pseudoC.h#L862-L878

It doesn't appear to be generated weekly.

There's too many unknown magic numbers for weather pattern for it to be implemented at this time.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
