### ISSUE TITLE
Replacing creator of island by second account

### ISSUE THREAD

**Issue by dimidrollko** [kwsch/NHSE#241]
Is it possible to make second created villager as creator of island, so events that start everyday will start on it?

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/28

**Comment by Hassiopeia** [comment]
Hey @dimidrollko , sorry for replying to an old issue, but I just found that Player Flag 45 is responsible for setting the in-game Resident Representative. I'm sure there are other Player Flags that would also need switched if you're truly changing Representative from one player to another. I'm working on doing that now, but in the end I think I may just dump the Player Flags for my two villagers and then just swap them when I load them back in.
