### ISSUE TITLE
Posters Items Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#242]
# Posters Items Editor

## Attachment of this section

![image](https://user-images.githubusercontent.com/55494819/82674984-5ff7b580-9c44-11ea-90cf-b74419a19aab.png)

**Comment by kwsch** [comment]
The Items are already obtainable via the item editor.

![image](https://user-images.githubusercontent.com/6393368/82682674-7bdb6700-9c04-11ea-9454-70d890a49285.png)

**Comment by MirayXS** [comment]
I know, but they don’t get added to this special section.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
