### ISSUE TITLE
Add a button to add every kk song to the music player inside Animal crossing 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#243]
Add a button to add every kk song to the music player inside Animal crossing,
i am completely ignorant if it is possible but it would be more helpful

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Just inject the items and register them manually.
