### ISSUE TITLE
Swapping Villagers - House, Clothes, Etc. Does not Change

### ISSUE THREAD

**Issue by gibsonfan2332** [kwsch/NHSE#25]
When editing a character and changing them to another more desired villager, the only thing that seems to change is the villager them self. It would be great if it also changed everything to be the new villagers things/house as if they moved in naturally. 

I hope this will be a feature in the future as only changing the person does not look or feel right.

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/17
