### ISSUE TITLE
Dodo Airlines Mystery Island Hemisphere Edit

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#250]
### A feature to change dodo airlines' mystery island hemisphere. 

> If you change this with the hemisphere editor feature (Souther-Northern) it doesn't change. 

> I had a southern hemisphere island, changed it to northern, but the dodo airlines mystery island was still the same color as the southern hemisphere (autumn ATM)

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by MirayXS** [comment]
Well that's ok. i can hadle that, it looks like i'am traveling to another whole new island :D
