### ISSUE TITLE
When moving buildings, placed items move differently than the rest of the map

### ISSUE THREAD

**Issue by Corgano** [kwsch/NHSE#253]
I have encountered that when i go to move buildings, if i use the arrows next to x and y to move them one unit at a time, any items on the map move differently than the map itself. 

I also noticed that "align items to grid" option on edit field items doesn't seem to work - I can still place items not aligned to the grid. IT worked fine in an older version of NHSE, so these two problems might be related.

**Comment by kwsch** [comment]
Snapping "Field Items" only applies to Field Items, not regular items.

Field Items are item IDs >= 60,000, which can only be placed along the major gridlines. Regular items can be pushed to the minor gridlines, hence no restriction.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/NHSE/commit/0d64fa65d8e6e7027c9859ab15e519be15d5aba6
