### ISSUE TITLE
Change nickname villagers give you

### ISSUE THREAD

**Issue by Corgano** [kwsch/NHSE#254]
Villagers in the game can give you a nickname when they like you enough, like superfan. It would be cool if we could get an option to change this in the editor.

**Comment by Corgano** [comment]
I love how quick you get everything done

**Comment by Corgano** [comment]
I see this issue being closed, but i don't see where you edit it.

**Comment by AlcremieSurprise** [comment]
> I see this issue being closed, but i don't see where you edit it.

It is in the program actually. Make sure to be on the latest commit, then open the main.dat file in the editor. Then go to the "Villagers" tab, the "Edit Villager..." button, then "Edit Player Memories", then make sure "21 - InputNickname" has 1 as the value, then go to the "Misc" tab and change/add the nickname. Hope this helps.

**Comment by Corgano** [comment]
OHH there was a "Misc" tab added to villager -> edit villager -> player memories. I see it now

Does each villager use it's own nickname? OR is it shared between all villagers? I have seen multiple villagers call me the same nickname so IDK how it's stored.

IF it's a single value for all villagers, it should really be on the player page, but if it's seperate it makes sense to be in the seperate per villager pages.
