### ISSUE TITLE
enum localization?

### ISSUE THREAD

**Issue by littlecxm** [kwsch/NHSE#257]
![image](https://user-images.githubusercontent.com/16154023/82857361-596a8600-9f43-11ea-9c79-99f10cebce35.png)
![image](https://user-images.githubusercontent.com/16154023/82857366-5cfe0d00-9f43-11ea-905e-65c0a43ea917.png)

thanks for your hard work on feature update 😄 
only a request,could you help to export enum string for localization?

**Comment by MirayXS** [comment]
oh yeah that would be amazing 👍💯

**Comment by berichan** [comment]
I am closing this issue as stale. There doesn't seem like there's enough interest in this for anyone to have taken on the work over the years.
