### ISSUE TITLE
include dump save for viewing purposes?

### ISSUE THREAD

**Issue by s-icidal** [kwsch/NHSE#26]
Not necessarily an issue, but I was wondering if you could include an empty dumped save in your files. I don't currently have an unpatched switch (ones being shipped) and I was interested in seeing what this looked like. Since I cant get a backup save to put into the editor, I can't get past the "open folder" screen. I'd like to see what is and is not included in this save editor before looking more into JKSV and save dumps. Thanks! :)

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/23

**Comment by s-icidal** [comment]
ah, ok. Thanks! :)
