### ISSUE TITLE
Unknown revision

### ISSUE THREAD

**Issue by stangwsn** [kwsch/NHSE#262]
Hello! I restarted my acnh save and when i try to edit the new one, i get the unknown revision error. However, when i try to edit my old save file it opened and didn't give any kind of error.

**Comment by kwsch** [comment]
Download the latest build and try again.

**Comment by stangwsn** [comment]
Sorry if I'm a bit ignorant but, two things:
1.- Must I download it through the dev-azure site or the github?
2.- In the github download, there isn't any kind of executable file. How can I generate it/Where can I find it?
Thank you so much for replying.
