### ISSUE TITLE
1.2.1 Offset

### ISSUE THREAD

**Issue by xCodingPotato** [kwsch/NHSE#267]
**Is your feature request related to a problem? Please describe.**
Cannot inject items due to the new version of ACNH 1.2.1

**Describe the solution you'd like**
Using the offset of version 1.2 gives me a bag of empty presents, thus with a new offset it should solve this problem.

**Comment by xCodingPotato** [comment]
I don't know, but after rebooting the switch 3-4 times, and trying to change the offset to another address it started to work again using the 1.2 offset...

**Comment by eligao** [comment]
Same here, any idea what's happening? The offset doesn't seem to have changed according to 1.2.1 cheat codes.

**Comment by xCodingPotato** [comment]
I removed EdiZon and it started to work properly.

**Comment by eligao** [comment]
I removed EdiZon and even Tesla, used sys-botbase 1.3, no luck. I made a clean minimal start from https://sdsetup.com/ and it worked. Strange it worked before.
