### ISSUE TITLE
Villager's Furniture Count

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#268]
# Villager's Furniture Count

### What i request is to increase the furniture count viewer to atleast 30 / 32.
![image](https://user-images.githubusercontent.com/55494819/83181967-e705cb80-a125-11ea-9e98-3dea77ec9ece.png)

**Comment by GreatMaestro** [comment]
@MirayXS Sorry for offtop, how did you add furniture images?

**Comment by MirayXS** [comment]
> @MirayXS Sorry for offtop, how did you add furniture images?

#197
