### ISSUE TITLE
Expand functionality of pattern editor and pattern editor pro

### ISSUE THREAD

**Issue by Possum80** [kwsch/NHSE#269]
**Is your feature request related to a problem? Please describe.**
Pattern editor can only import and dump patterns.  

**Describe the solution you'd like**
1) Expand function to enable changing design names

**Describe alternatives you've considered**
A full pattern editor is likely to be beyond the scope of the project

**Comment by DrakanShadow** [comment]
Right now there is a roundabout way to do it.  Dump the pattern and import over a pattern you created.  This will make you the creator of the pattern letting you rename and edit it.

**Comment by berichan** [comment]
I am closing this issue as stale. Slightly more complex pattern editing was added with the PR noted above.
