### ISSUE TITLE
Villager Swap, House and Clothes included

### ISSUE THREAD

**Issue by gibsonfan2332** [kwsch/NHSE#27]
**Is your feature request related to a problem? Please describe.**
When swapping a new character in, the old villager's house, clothes, and more stay the exact same. 

**Describe the solution you'd like**
Ideally when swapping a new character in, the new character's house should be swapped in as well as anything else. It should be as if that villager moved to town naturally. It is not very useful to swap in a different villager if it breaks the game like that.

**Comment by s-icidal** [comment]
suggestion- not sure if this is in the save editor, but if it is possible to put different animals at the campsite, and then adopted them from there, would this fix your issue? I'm not sure about the clothes, but their house should be changed to their base furniture. An extra step, but regardless should work if changing those at the campsite is implemented

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/25
