### ISSUE TITLE
Trigger or Find Meteor Shower Dates

### ISSUE THREAD

**Issue by RyanKasperCook** [kwsch/NHSE#270]
Would be wonderful if there was a way to trigger a Meteor Shower/Celeste, or a flag that we could set to trigger a meteor shower for that specific day.  Alternatively, if there is a way to find out what your particular meteor shower dates are already set to somehow, that would work as well as you could just time travel to those days.  Thanks for the consideration!!

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
