### ISSUE TITLE
add a player function to where to edit the mailbox letters 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#277]
a huge pain in AC is when you have to remove the letters from your mailbox since you have to open and delete all of them manually 

i would like a sort of menu that you can do multiple selection of what letters you want to remove

**Comment by MirayXS** [comment]
I made a issue similar like this, #255

**Comment by kwsch** [comment]
Feel free to implement it and submit a pull request.

I'm not interested in implementing cosmetic edits.

**Comment by GamerKarl** [comment]
> Feel free to implement it and submit a pull request.
> 
> I'm not interested in implementing cosmetic edits.

it really is not a cosmetic edit but okay...
