### ISSUE TITLE
Change Resident Representative

### ISSUE THREAD

**Issue by RDNachoz** [kwsch/NHSE#28]
**Is your feature request related to a problem? Please describe.**
Currently, only the first person to create an account is set as the resident rep. In my case, my fiancé created the island and doesn't play much rendering me useless unless I go on her account which is not ideal.

**Describe the solution you'd like**
The ability to change who the Resident Representative is.

**Describe alternatives you've considered**
The only other way to fix this would be to restart the whole island which is not ideal.

**Additional context**
N/A. Will gladly help do any data digging if you want, would just need the files to dig through :)

**Comment by RDNachoz** [comment]
Granted I'm sure you've received requests for this already, but let me know if you need any help digging for the answers!

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by Hassiopeia** [comment]
Hey @RDNachoz, sorry for replying to an old issue, but I just found that Player Flag 45 is responsible for setting the in-game Resident Representative. I'm sure there are other Player Flags that would also need switched if you're truly changing Representative from one player to another. I'm working on doing that now, but in the end I think I may just dump the Player Flags for my two villagers and then just swap them when I load them back in.

**Comment by odinskyyy** [comment]
> Hey @RDNachoz, sorry for replying to an old issue, but I just found that Player Flag 45 is responsible for setting the in-game Resident Representative. I'm sure there are other Player Flags that would also need switched if you're truly changing Representative from one player to another. I'm working on doing that now, but in the end I think I may just dump the Player Flags for my two villagers and then just swap them when I load them back in.

Hello there i started playing on a new profile and i'm not the representative, i'm searching everywhere a way to change it without being able to find any answer.
You seem to know how to do it, could you help me with that ?

**Comment by kwsch** [comment]
> You seem to know how to do it, could you help me with that ?

Did you not read the message you quoted?
