### ISSUE TITLE
Villager Furniture Editing

### ISSUE THREAD

**Issue by strawpedro** [kwsch/NHSE#283]
**Is your feature request related to a problem? Please describe.**
The current villager editor supports villager furniture & outfit inventory editing, thought it would be really neat if we can edit the layout of the villager's interior.

**Describe the solution you'd like**
Similar to the map editor, edit the interior of the villager by adding/removing/modifying different default furniture markers that each villager has. The relevant information can be found here: https://nookstop.ssmvc.org/house.html?id=cat23

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
The default method to alter villagers' interior is by gifting them items that are eligible for display daily, but certain rules need to be followed in order for this to work. This method also does not offer a lot of freedom because all default furniture markers are fixed.

**Additional context**
Here is the additional info on villager furniture replacement rules: https://docs.google.com/spreadsheets/d/1Iql5J5BXG-SuJvtw_duLZzjIw5myGcFnEL-I3BSR_CE/edit#gid=1080710934

**Comment by 1davi** [comment]
Any news on that?

**Comment by berichan** [comment]
I am closing this issue as stale. It seems like the position info isn't in the structure itself, which lead me to believe items are placed based on wherever there is space in an order whenever a house is entered. If anyone does any further research on this and wants to discuss further then feel free to post here and I'll reopen this issue.
