### ISSUE TITLE
Nook's Cranny Item Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#285]
# Nook's Cranny Item Editor

## There should be a nook's cranny item editor to edit daily items.

**Comment by Corgano** [comment]
Depends if these are stored or random, but it could be cool.

**Comment by berichan** [comment]
I am closing this issue as stale. I do not believe there is a structure for this, it likely is a daily rerolled seed or is obtained from some other seed. If anyone does want to do further research for this then please let me know and I will reopen the issue.
