### ISSUE TITLE
Suggestion [Tried finding a different contact]

### ISSUE THREAD

**Issue by StudioVulcan** [kwsch/NHSE#288]
Hiyo, apologies that i'm sending this through an issue ticket. I tried hard to find you on a different platform.

Great updates, LOVE the new named listings now instead of just having to rely on IDs. 
One suggestion is that when searching, you have it search in a way that it searches for the exact term you type.

If you type. "Table", it'll only show anything that STARTS with Table. I'd love to be able to type "Table" and have it search /with in/ the names of items, and not exact spelling from the first letter and onward.

No idea if this is in the words, but I thought there's no harm in putting the suggestion out there, I know most people would be using the search feature this way and would become stumped and frustrated they can't find what they're after. <3

**Comment by kwsch** [comment]
Unfortunately, the ComboBox control provided by System.Windows.Forms (the GUI kit for NHSE) only supports a `StartsWith` filter-suggestion, not a `Contains` / `EndsWith` / Regex style.

I can add in something sneaky like a hover tooltip (hover over the dropdown arrow and it'll show item names that contain the entered string).
