### ISSUE TITLE
Posters and photos

### ISSUE THREAD

**Issue by Limera1n** [kwsch/NHSE#29]
**Is your feature request related to a problem? Please describe.**
Unlocking villagers posters and photo doesn"t work throught "Received item list editor" features.

**Describe the solution you'd like**
Be able to buy them with the Nook Shopping app

**Additional context**
Tried removing them and scanning a new amiibo on Harvey island but it change nothing

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/30
