### ISSUE TITLE
Terrain editor Selecting multiple tiles, copy/paste/flip/rotate selection

### ISSUE THREAD

**Issue by Corgano** [kwsch/NHSE#290]
I know this would take a lot of effort, but it'd make the terrain editor very powerful in what it can do. It'd be cool to be able to select an area, and be able to copy/paste/flip/rotate a set of tiles all at once. Mostly useful for making large builds that are symmetric but has lots of other little uses as well.

**Comment by kwsch** [comment]
Probably more appropriate to just use click+key modifiers similar to the existing ones:

view: ctrl click
set: shift click
reset (base): alt click
rotate: ctrl-shift click?

Multi-select isn't really useful when you can just use the click modifiers to quickly copy paste.

**Comment by Corgano** [comment]
Unless you want to copy a 10x10 chunk section, flip it, and put it on the
entire opposite side of your island. Say i have a section of cliff and
river that perfectly fits a bridge and a ramp, and i want the same setup on
the opposite side of the map, there can be dozens of different tiles in
that area.

Copying them one by one is extremely tedious even with shift click to set.

**Comment by kwsch** [comment]
> Copying them one by one is extremely tedious even with shift click to set.

Implementing something like this is also extremely tedious, especially when most people won't even use it. I'm not going to implement anything beyond a click-rotate; others can always implement new features!
