### ISSUE TITLE
Export data as JSON for easy comparison/manipulation

### ISSUE THREAD

**Issue by mbirth** [kwsch/NHSE#295]
**Is your feature request related to a problem? Please describe.**
Dumping data like e.g. villagers or flags dumps them in raw binary format. This is not useful if you're trying to research game behaviour.

**Describe the solution you'd like**
I'd love a way to export objects in JSON format, so we can easily compare different revisions and see differences in a text editor. Also changing things and importing the changed JSON would be awesome.

Exported JSON should have labels resembling what you see in the app, e.g. for flags something like:

```
"Map": {
  "Flags": [
    { "TodayCreateVillage": 0 },
    { "TodayPlayerEmigrate": 0 },
    { "TkkFirstLive": 1 },
      ...
  ],
  "some_unknown_binary_data": "01 23 45 67 89 ab cd ef",
  ...
}
```

Also it should be pretty-printed (like above) for easier use of diff tools.

**Describe alternatives you've considered**
Working with the existing binary format, but comparing those only gives changed bytes and it's hard to find the actual values in NHSE that are encoded in those bytes.

**Additional context**
This would be an awesome feature for doing research, e.g. easily comparing changes between two different days.

**Comment by kwsch** [comment]
Keep in mind that the save file does not store flag names; they're externally provided via embedded resources derived from the game's BCSV files. Everything is serialized into bytes :\

For navigating the binary data -- check out [Ninji's repo which has generated `c` headers](https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_131080_131078_pseudoC.h).

Stuff like this falls outside the scope of NHSE, as very few people will end up using the information relative to the amount of code required. If one were to make a simple diffing tool, I think something that uses the above savedata schema would be the best approach. [Ninji has made a schema deserializer](https://cdn.discordapp.com/attachments/685656592774856725/705806047344066570/acnh_save_cs.zip) in c#, but labeling flag names / etc hasn't been handled automatically.
