### ISSUE TITLE
FYI: Fixing changed villager furniture / clothing

### ISSUE THREAD

**Issue by mbirth** [kwsch/NHSE#297]
I had the same issue like #211, #138, #112, #96, #95, #80,  #27, #25 and #17. After changing a villager, the new villager appeared, but had house, clothes and furniture of the previous villager.

The game seems to have fixed the building itself ... somewhat. The style is suddenly correct, but the colours are off.

To fix the furniture and the clothing, I found out that setting Flag "05 - MoveInCompletion" to "0" will fix this over night. On the same day after changing that flag, that villager was never at home ("I'm exploring the island.") and nowhere to be found. However, one day later, Isabelle told me we have a new villager and the villager appeared "in boxes" (=moving in) and the wallpaper, flooring and the clothes are correct now. I expect the furniture to be correct as well, tomorrow.

I'm now waiting for some plot to become free and some villager to "reserve" that plot so I can check what flags do what.

May I kindly ask you to keep this issue open so more information can be collected here and once there are working ways to fix the issues above, you can either make some convenience buttons in the app or at least transfer this information to a wiki page or a tooltip in the app.

**Comment by MirayXS** [comment]
Just change them manually?

**Comment by mbirth** [comment]
That's like buying a new car when your current one doesn't start. This way you'll never understand HOW it works.

**Comment by MirayXS** [comment]
ah ok

**Comment by mbirth** [comment]
So my villager currently moving in (in boxes) now has:

    05 MoveInCompletion = 1
    07 MoveRoomIndex = 0

where all other (already moved in) villagers have:

    05 MoveInCompletion = 1
    07 MoveRoomIndex = 10

Although I believe the clothing and furniture is set at this moment. So changing this can make a "moving in" villager a "normal" villager, but not fix the furniture/clothing.

**Comment by Possum80** [comment]
Importing an empty villager will reset the plot to pegged state and ready for villager to be invited

**Comment by mbirth** [comment]
@Possum80 Sadly, there doesn't seem to be a dump (house+villager) of the "empty" state in the collection mentioned by @MirayXS above. Can you provide one?

**Comment by Possum80** [comment]
Attached is an empty villager
[empty.zip](https://github.com/kwsch/NHSE/files/4744662/empty.zip)

**Comment by Weaselgrease** [comment]
Having similar problem as OP but there doesn't appear to be a way to simply make them "repair" their furniture once they've put down a crafting table.

I have Dobie and Apollo.  I loaded them in as my first villagers while everyone was still in tents.  Something happened and they never bothered upgrading their homes from tents (they never mentioned wanting to upgrade and the known triggers to get them to do so never influenced them) so I had to manually change their home types.  A few days later I entered their homes and noticed they had no furniture in their homes except a crafting table.  I tried changing the mentioned 'MoveInCompletion' and 'MoveRoomIndex' flags but no dice.  It just looks the same as before once they're declared as moved in.

My only alternative at this point is to backup my save, re-load them and rebuild my relationships with them.

I would really like to be able to just manually edit their furniture the same way you can with the player homes.

**Comment by kwsch** [comment]
NHSE added a built in database of villagers and their default (not initial) houses. Just reset the house.
