### ISSUE TITLE
Player name changing and Inventory Editor item counts

### ISSUE THREAD

**Issue by vehneez** [kwsch/NHSE#3]
When the player's name is changed, the villagers act as if the player is new to the island. 

Another issue I found is when maxing out inventory for wood, you have to put 29 instead of 30. 

Thank you for your hard work on this project!

**Comment by kwsch** [comment]
* The "Count" is extra stacks in addition to the default 1
  * Items are tricky as certain items use values differently; full metadata isn't documented yet.
* Villagers likely have a ledger of player names that they've met; when changing the player's name, you're no longer in their ledger. Maybe.

The item structure and villager structures are new and not entirely fleshed out yet; these may be made clearer in the editor when the community better understands how data is stored :)
