### ISSUE TITLE
Villagers poster

### ISSUE THREAD

**Issue by THOMZY** [kwsch/NHSE#30]
**Is your feature request related to a problem? Please describe.**
I added everything with "Edit received items" but i'm missing every posters and photos of villagers in Nook Shopping.

**Describe the solution you'd like**
Unlock everything in Nook Shop

**Describe alternatives you've considered**
I tried to remove everything, scanned an amiibo at Harvey house, but it's still the same, i only have the posters of amiibos i scanned.

**Additional context**
https://i.imgur.com/i1mOVuy.png

**Comment by kwsch** [comment]
They probably aren't purchasable, or require extra flags (requiring research).

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
