### ISSUE TITLE
Game crash when trying to add 41st item from storage to pockets

### ISSUE THREAD

**Issue by mbirth** [kwsch/NHSE#302]
I don't know what changed, we did multiple changes using NHSE and this problem didn't occur before. However, now this bug surfaced where the whole game crashes as soon as you try to add the 41st item from your storage to your pockets. Usually, a message "My pockets are full" should pop up instead.

We were using build #20200602.2 before to change villagers and money without this problem.  I've tried #20200606.2 as well - same result.

After editing a save (only changed money, nookmiles; replaced a villager, added flowers to field) there now is this bug in the save. Everything else seems to be fine, changes showed up and that. But for some reason, it now gives this bug.

Any ideas?

**Comment by mbirth** [comment]
As it turns out, my wife set her pocket money to some ridiculous amount (800k) and that broke the game. Maybe NHSE should impose a limit to 99.999 here? Or at least show a warning/turn the field red or something like that?

**Comment by kwsch** [comment]
Pocket Count (not money) values shouldn't really be modified. They are at most 20 and 20, each.

**Comment by mbirth** [comment]
She didn't touch the pocket count (both values still at 20), but the pocket money which can only go up to 99.999 Bells.

**Comment by kwsch** [comment]
There isn't any Pocket Money field. Bank Bells is a 32bit value.

**Comment by mbirth** [comment]
Oh, I'm sorry, it's called "Wallet" in your app.
