### ISSUE TITLE
Import cheat from clipboard bugs

### ISSUE THREAD

**Issue by charlisepahina1** [kwsch/NHSE#303]
NHSE has a really really useful funtion,Hold control when clicking Load to instead read a cheat code from clipboard.

But I used cheats like:

08100000 AC4723D0 00000000 00000E25
08100000 AC4723D8 00000001 00000E25
08100000 AC4723E0 00000002 00000E25
08100000 AC4723E8 00000003 00000E25
08100000 AC4723F0 00000004 00000E25
08100000 AC4723F8 00000005 00000E25
08100000 AC472400 00000006 00000E25
08100000 AC472408 00000007 00000E25
08100000 AC472410 00000020 00000E25
08100000 AC472418 00000021 00000E25
08100000 AC472420 00000022 00000E25
08100000 AC472428 00000023 00000E25
08100000 AC472430 00000024 00000E25
08100000 AC472438 00000025 00000E25
08100000 AC472440 00000026 00000E25
08100000 AC472448 00000027 00000E25
08100000 AC472450 00000040 00000E25
08100000 AC472458 00000041 00000E25
08100000 AC472460 00000042 00000E25
08100000 AC472468 00000043 00000E25
08100000 AC472318 00000044 00000E25
08100000 AC472320 00000045 00000E25
08100000 AC472328 00000046 00000E25
08100000 AC472330 00000047 00000E25
08100000 AC472338 00000060 00000E25
08100000 AC472340 00000061 00000E25
08100000 AC472348 00000062 00000E25
08100000 AC472350 00000063 00000E25
08100000 AC472358 00000064 00000E25
08100000 AC472360 00000065 00000E25
08100000 AC472368 00000066 00000E25
08100000 AC472370 00000067 00000E25
08100000 AC472378 00000080 00000E25
08100000 AC472380 00000081 00000E25
08100000 AC472388 00000082 00000E25
08100000 AC472390 00000083 00000E25
08100000 AC472398 00000084 00000E25
08100000 AC4723A0 00000085 00000E25
08100000 AC4723A8 00000086 00000E25
08100000 AC4723B0 00000087 00000E25

It works well at atomsphere,edizon 4.0.  But when I use NHSE to import cheat,they only show 20 slot  in NHSE which are same color , How can I fix this error?

@kwsch

**Comment by kwsch** [comment]
It currently only handles the `04` prefixed codes, as sxos doesn't support the 8byte writes. I'll see how I can expand it
