### ISSUE TITLE
German: wrong label for empty field in inventory

### ISSUE THREAD

**Issue by MZ-4** [kwsch/NHSE#305]
German: When editing player's inventory you get the term "(Green)" when on an empty field instead of "(None)" (or something like "(leer)" if you would translate it).

It's somewhat confusing but no error, if it's simply a translation- and no pointer-issue.

Last good version in my archive: 20200526.3
Appears in 20200526.8 (I have no version in between of them).

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/blame/master/NHSE.Core/Resources/text/de/text_item_de.txt#L1
