### ISSUE TITLE
Advanced island editor

### ISSUE THREAD

**Issue by Pigii** [kwsch/NHSE#308]
usually i have to make a lot of maps and edit them like 1/3 times / day. there are some things i suggest for the next version, have a good day!

1) Multi selection, to erase or replace more items faster

2) the line, circle and box selection, just like paint
![image](https://user-images.githubusercontent.com/54852275/84530620-8230a080-ace3-11ea-8e66-c68802367d39.png)

3) a way to see more of the map (not limited by a 16 x 16 box) possible solution: you can press shift + drag to select a bigger area / just a slider on top

4) if possible the possibility to edit the beach and rocks

have a good day!

**Comment by kwsch** [comment]
1. Don't forget about the hotkeys already present (ctrl/shift/alt to view/set/clear).

2 & 3. This isn't a high budget island simulator. NHSE draws the map and 16x16 view pixel by pixel. If someone wants a more fancy way of rendering the map, they can implement it and submit a pull request :P

4. You can already swap the beach acres via the corresponding tab. You can't move those rocks as they're premade acres.

**Comment by berichan** [comment]
I am closing this issue as style. What is requested is essentially complex winforms extensions, which were already beyond the scope of NHSE. If someone finds a library or wants to develop further then please let me know and I will reopen this issue.
