### ISSUE TITLE
Multiple Documentations

### ISSUE THREAD

**Issue by swampatha** [kwsch/NHSE#309]
All hex values are in the decrypted save file.
## Wisp & Celeste
Under the visitors tab, `_e2484556` is what day Wisp will appear, and `_753479b1` is what day Celeste will appear on. 0 is Sunday, 1 is Monday, 2 is Tuesday, etc.

## Weather Seed
In the decrypted save, from 1D70D8-1D70DB is your weather seed. Subtract 2147483648 from that uint32 to find your weather seed which can be used in Ninji's weather tool.

## Island Score
Also in the decrypted save, from 4F98CC-4F98CF is the float32 for the Nature Points. 4F98D0-4F98D3 is the float32 for the Life Points. 

## Shops
The Unique ID is the item ID. I'm not quite sure what System Param or Additional Param are but they seem to always be 00. The Free Param is the alternate color it uses. It is usually 00000000, but if it is Variant ID 1_0, it would be 01000000. I'm not quite sure how patterns work, but I would assume the first two digits are the body ID and the last six are the pattern ID.
### Saharah
Saharah's items change weekly.
|            | Unique ID     | System Param | Additional Param | Free Param    |
|------------|---------------|--------------|------------------|---------------|
| Large Rug  | 40F594-40F595 | 40F596       | 40F597           | 40F598-40F59B |
| Medium Rug | 40F59C-40F59D | 40F59E       | 40F59F           | 40F5A0-40F5A3 |
| Small Rug  | 40F5A4-40F5A5 | 40F5A6       | 40F5A7           | 40F5A8-40F5AB |
| Wallpaper  | 40F5AC-40F5AD | 40F5AE       | 40F5AF           | 40F5B0-40F5B3 |
| Flooring   | 40F5B4-40F5B5 | 40F5B6       | 40F5B7           | 40F5B8-40F5BB |
### Able Sisters
Able Sisters follows the same pattern as before starting at 40F5C0. In my data, it has data for 16 total items, although it has support for up to 128. Able Sisters items change daily.

### Kicks
Kicks follows this same pattern starting at 410890. In my data, it has data for 10 items, although it has support for up to 32. Kicks items change weekly.

### Daily Selections
The Daily Selections follows this same pattern starting at 4120A4. In my data, it has data for 9 items, although it has support for up to 64. The Daily Selections items change daily.

### Leif
Leif follows this same pattern starting at 412328. In my data, it has data for 9 items, although it has support for up to 32. Leif's items change weekly.

### Redd
Redd follows this same pattern starting at 412428. In my data, it has data for 6 items. Redd's items change daily, even if he is not present that day or at all that week.

### Nook's Cranny
Nook's Cranny is very interesting. At the start of every week, the entire week's worth of Nook's Cranny's items are predetermined.
Nook's Cranny follows this same pattern. In my data, it has data for 40 items, although it has support for up to 64. 
Each day's first item starts at the following:
* Sunday - 410990
* Monday - 410B90
* Tuesday - 410D90
* Wednesday - 410F90
* Thursday - 411190
* Friday - 411390
* Saturday - 411590

## Daily Crafters
Each day you have three set crafters that cycle on a 3 hour cycle starting with the first time you log on. Villager #1 is 1D6E63, Villager #2 is 1D6E64, and Villager #3 is 1D6E65. The raw value is the villager ID.

I hope this helps. All of this was found with the help of Ninji.

**Comment by kwsch** [comment]
Weather Seed: [_3bb101ca within `struct GSaveWeather`](https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L868).

Nature/Life Points: Probably re-calculated by the game and won't persist via editing. Stored within [GSaveVillageScore](https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L1367-L1373).

Shops: [All are contained by a parent struct - GSaveShop](https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L1328-L1341). Currently, only GSaveKabu is exposed for editing (Turnip Prices).

DIY Villagers: [Stored within GSaveNpcVillager](https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L906).

**Comment by swampatha** [comment]
In commit 025f37c1da5e9a1cc95d9106f191671a51311bdc, flag 4 is still Wisp. It appears that Wisp is guaranteed to show up at least once during the week (Monday-Friday), but will sometimes show up on the weekend and be scheduled in this visitors section instead of his own section.

**Comment by MirayXS** [comment]
`...`
> Nature/Life Points: Probably re-calculated by the game and won't persist via editing. Stored within [GSaveVillageScore](https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L1367-L1373).

You could make a box to read-only the values and not edit it, your choice though

**Comment by berichan** [comment]
I am closing this issue as stale. It seems like the feature requests were partially implemented, if anyone else has more information to add then please let me know if you plan on developing further and I will reopen this issue.
