### ISSUE TITLE
Received Items: Furniture Variations Support

### ISSUE THREAD

**Issue by igniscitrinus** [kwsch/NHSE#31]
In its present state, checking certain items (most notably furniture) in the Received Items Editor will only unlock the item's first form if it's not already unlocked. 
Presumably, the bitflags for which variants of each item have been received are also stored inside personal.dat.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
