### ISSUE TITLE
Normal and Pro Designs | Sets Import and Dump

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#310]
# Normal and Pro Designs | Sets Import and Dump

## NHSE should have a option to import and export sets of normal designs and pro designs

**Comment by MirayXS** [comment]
For sets I mean all the normal designs or pro designs*

**Comment by sir1st** [comment]
there is a dump all option when you click the dump button, pressing the shift key. but import button doesn't support this function, it doesn't show in the patternEditor.cs code.
