### ISSUE TITLE
Features Request for Field Item Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#312]
# Features Request for Field Item Editor

## 1. Bulk-Remove placed DIY furniture 
> Options to bulk-delete placed DIY furniture

## 2. Bulk-Remove Buildings
> Options to bulk-delete bridges and inclines

## 3. Bulk-Remove Furniture 3 blocks wide
> Options to bulk-delete furniture at least 3 blocks wide

## 4. Bulk-Remove placed DIY Furniture 3 blocks wide
> Options to bulk-delete placed DIY furniture at least 3 blocks wide

## 5. Bulk-Remove outdoor furniture
> Options to bulk-delete placed outdoor furniture
> "Outdoor is an internal value assigned to many furniture items."

## 6. Bulk-Remove furniture that cost 2k bells or more
> Options to bulk-delete furniture that cost 2k bells or more

## 7. Bulk-Remove furniture that cost 20k bells or more
> Options to bulk-delete furniture that cost 20k bells or more

**Comment by berichan** [comment]
I am closing this issue as stale. As before, there doesn't seem to be any interest in arbitrarily grouping items into sets, themes or sizes for anyone to want to have done this over the years.
