### ISSUE TITLE
Request for easy use the Field Item Editor

### ISSUE THREAD

**Issue by Soopoolleaf** [kwsch/NHSE#313]
Hi I'm your Sponsor, and I using NHSE. It's useful. 
but for more easier to use I request some change things.

![20200618_140150](https://user-images.githubusercontent.com/59555129/84981104-b803d800-b16e-11ea-93e3-a1c5e4384c2c.png)
![20200618_140128](https://user-images.githubusercontent.com/59555129/84981105-b9350500-b16e-11ea-9d6a-aeff4a7e651f.png)
![20200618_140111](https://user-images.githubusercontent.com/59555129/84981108-b9350500-b16e-11ea-87f2-909a97c03e32.png)
I'm every  animal crossing game fan and I'm used animal crossing new leaf editor very a lot. The reason I say it, It's really great to use and comfortable editor. under the paragraph is just explain this AC:NL editor using. because this editor use comfortable. besides If you using little bit you can found how to use more comfortable your NHSE program. 

How to using AC:NL editor
1. download this game file.
https://drive.google.com/file/d/1Jb2alZiaQu1Wv_gvowshs_C-PT4VLFLq/view?usp=sharing
2. go to the this site and upload download game file. 
https://www.marcrobledo.com/acnl-editor/
3. just look around and using the editor. 

**REQUEST**
Map menu-> Edit Map->Edit field Item

 This is uncomfortable using. Because It's not allow item drag. 
It's mean If I click the field using with left mouse button and not take away finger from mouse, and drag any field way, and the Items full the field mouse moving. I don't know you can get 'cause I'm not good at English. 

I know using mouse drag on the field item editor, than moving the Island field. 
but I think drag item full function It's more better for comfortable. 
field moving function just click and that's change. that's enough.

This NHSE program provide double click is select item, right click is provide View, Set and Reset. 
It's need change things for more comfortable. 
left click is set item, right click is select item, for reset the item just using right part and writing (None) then select this and set this. 

Thank you for programming this.

**Comment by berichan** [comment]
I am closing this issue as stale. This level of complex UI functionality sadly doesn't have much interest for how much work is required. If someone wants to do this with the winforms project then please let me know and I'll reopen this issue.
