### ISSUE TITLE
Changing native fruit... doesn't?

### ISSUE THREAD

**Issue by kaolincash** [kwsch/NHSE#316]
From what I can tell, the only things that changing the native fruit actually affects are:
-the physical fruit sold in nook's cranny
-the name of the fruit listed on your passport

your villagers continue to refer to your original native fruit (e.g. Ken and Butch just had an argument about the mouthfeel of our "local" apples--unfortunately, I didn't think to capture this conversation in a screenshot or clip), and the fruit costs 2000 bells in nook's cranny.

i've tried playing with the flags, but i can't find any sort of combination that changes any of the above.
![EbKxSybU8AEIAUQ](https://user-images.githubusercontent.com/15176180/85359394-02d67480-b50e-11ea-9bb0-91e007f19218.jpg)

**Comment by MirayXS** [comment]
Doesn’t the option to change native fruit ON the passport only works on the passport and not in game real fruit?

**Comment by sneedfeedseed** [comment]
I'm all for this addition, hope this gets added. But as a substitute for this method try backing up your current save maybe through jksv, start a new game then keep resetting for an island that has the fruit you want, wait until you get to a part you can save, then back up that save and then just import the flags/villagers/island everything to that save with the fruit you want!

**Comment by ceynomore** [comment]
There's actually two places town fruit needs to be changed, it turns out. Map flags 245-249 have to be changed in addition to the fruit type ID, as seen here:

![localislandfruitflags](https://user-images.githubusercontent.com/83928895/117590447-7b7df980-b0fd-11eb-8289-e9a5c9b15aa1.PNG)

You'll need to change the current town fruit (the one you're getting rid of) to "0" for false, and change the new town fruit you want to replace it with, with "1" for true. In the example above, oranges are the town fruit. To change it to cherries, you'd need to change it to 1 after flag 249 (cherries), and 0 after flag 246 (oranges).

**Comment by ceynomore** [comment]
Here are the screenshots from my testing, as well. For this town, the original fruit was oranges, and it has been changed to cherries, and this shows how cherries are both available at Nookling's at the proper price post change, as well as reflecting the proper sale prices for native and non-native fruit. Oranges now sell at premium, while cherries do not.

![2021051016011200-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/83928895/117591963-b172ac00-b104-11eb-995c-6ecf94981656.jpg)
![2021051016042300-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/83928895/117591965-b172ac00-b104-11eb-9672-419c41aa72d2.jpg)
![2021051016044600-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/83928895/117591966-b20b4280-b104-11eb-9363-b677e44dbd89.jpg)

I don't have a screenshot for the villager conversation re: town fruit I saw prior, myself, either, but I'll remember to grab it next time for documentation as needed.

**Comment by ceynomore** [comment]
I'm so sorry, I was pretty sleepy this morning and forgot a pretty integral part of my screenshots/process. There's an additional Map edit you need to do, under Field Goods:

![nhse-townfruit](https://user-images.githubusercontent.com/83928895/117601592-c22f1c00-b11c-11eb-9b34-8c8911b5e012.JPG)

SpecialtyFruit is your native fruit, SisterFruit is the secondary "rare" fruit that shows up on Mystery Islands for your island. Make sure you change these values to match the fruit IDs of your Passport. So, three steps altogether, if I'm counting properly this time.

**Comment by HamelMoric** [comment]
So what if your 245-249 isn't about island fruit?  I've gone up and down the flag editor at least 5 times and cannot find this section. It's almost like it doesn't exist on mine. I did just update to the latest version of the program, I don't know if that was taken out of the flag editor?

![image](https://user-images.githubusercontent.com/88097838/127772682-7248f0c9-c0e4-4117-a3eb-495567253fe3.png)

**Comment by kwsch** [comment]
@HamelMoric 
> It's almost like it doesn't exist on mine.
> ![image](https://user-images.githubusercontent.com/88097838/127772682-7248f0c9-c0e4-4117-a3eb-495567253fe3.png)

Edit the land (map) event flags, not player specific event flags.

**Comment by berichan** [comment]
I am closing this issue as stale. Though it seems as if it was resolved with the additional flag research. Thanks to everyone who contributed.
