### ISSUE TITLE
Item Categories in Selection Menu

### ISSUE THREAD

**Issue by miniblick** [kwsch/NHSE#317]
Sometimes while editing my save, it's a pain to have to scroll through every item in the game to find specific things. For instance, I was attempting to add all the different types of clothing items into my storage, but it took very long due to the fact that I had to constantly scroll through unrelated items.

I would suggest adding some sort of setting to the menu to allow you to only see an item from a specific category, e.g:
-Clothing
-Tools
-Fences
or

-Lovely Set
-Cabin Set
-Antique Set
etc, etc.

I understand that this program isn't supposed to be extremely complex and fancy, but I do believe implementing categories for items would most definitely be a quality of life improvement for anyone who needs to gather specific items and doesn't want to spend too much time digging through the list.

It would definitely make this program a lot easier and user friendly if each respective item was grouped into one section for easy access and quick navigating

**Comment by berichan** [comment]
I am closing this issue as stale. There doesn't seem to be any interest in arbitrarily grouping items into sets or themes for anyone to want to have done this over the years.
