### ISSUE TITLE
Data Field needed for record

### ISSUE THREAD

**Issue by jhun911** [kwsch/NHSE#319]
for some reason, I found the original ACNH installment ID like cartridge ID or online download ID is quite useful.
Like the original game initial date in NHSE, it should saved in the package.

**Comment by kwsch** [comment]
https://github.com/Treeki/CylindricalEarth/blob/c1ac18ec3c4bbc8916634da0751ba3b0bbaa6d89/savefile/save_schema_131080_131078_pseudoC.h#L615-L622

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
