### ISSUE TITLE
Hitting "Write" in the item injector causes inventory to fill with random junk

### ISSUE THREAD

**Issue by tzAria** [kwsch/NHSE#32]
I'm not sure if this has to do with the Offset text box, but when I made changes to my inventory, connected via sysbot, and hit inject, the top 2 rows of my inventory filled up with random glitched furniture and presents containing other random furniture.

**Comment by kwsch** [comment]
> I'm not sure if this has to do with the Offset text box

it has everything to do with the offset box ;)

Your RAM is displaced. 

Ensure that you have disabled all Atmosphere cheats (holding L while booting up the game works temporarily) and you have not opened any apps such as CaptureSight/Edizon. Reboot your Switch and try again.

**Comment by kwsch** [comment]
If you refer to the various cheat codes:

```
Any infinite item in slot 1 (1.1.2a)
04100000 AC3B90C0 0000xxxx
04100000 AC3B90C4 00000000
20000000
```

You'll see that the offset in SysBotUI matches the cheat code's offset (for the first pocket slot).
![image](https://user-images.githubusercontent.com/6393368/78279888-148b1b80-74cd-11ea-94aa-7f2ea2b3c1e5.png)

**Comment by tzAria** [comment]
I've gone through and experimented a bit. I've found 2 things:
- In response to what you said, I don't have any cheats running. I have the Edizon overlay installed, but no cheats are loaded. 
- When I hit "Read" with an empty inventory, it only clears the top 2 lines in the editor. Then when I hit write with an empty inventory screen, it fills the top 2 rows of the inventory with furniture with no name.

**Comment by kwsch** [comment]
Injecting only modifies the top 2 rows of items.

Edizon being active interferes with sys-botbase's ability to r/w the RAM.

You can always peek at the RAM layout with the main editor window's hex edit stuff, which uses sysbot to let you edit RAM directly. Double check that the RAM that it returns matches what you are expecting to be there (array of items).

**Comment by tzAria** [comment]
Thanks - disabled the Edizon overlay and the editor works perfectly.

**Comment by piapple1** [comment]
Hi, I do not have any cheats or overlays enabled and I am holding L when the game launches to be sure on atmosphere 10.4. It can read my inventory fine but when I go to write to it it FailValidates and fills inventory with "empty" items.

**Comment by kwsch** [comment]
@piapple1 use sys-botbase v1.3 [as per the wiki](https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection).

**Comment by piapple1** [comment]
@kwsch thank you, I must have missed that paragraph the first time.
