### ISSUE TITLE
When editing the river mouth (to remove), it leaves behind a river block that cannot be terraformed. 

### ISSUE THREAD

**Issue by MadisonFM** [kwsch/NHSE#320]
When I edit the acre using the terrain tool in NHSE, all of the options for the Southern beach leave at least one block of water that cannot be terraformed or covered. How can I fix this?

**Comment by MadisonFM** [comment]
I've also been trying to edit the Terrain (UnitModel, Variation, LandMakingAngle) but I can't quite figure out how to "save" it...they just stay river blocks. 

https://gyazo.com/aacd9d8e5536987dab16721c8333efae

**Comment by kwsch** [comment]
For others: The exterior acres are fixed layout and cannot be customized.
