### ISSUE TITLE
Trouble connecting to Online Services. 

### ISSUE THREAD

**Issue by miniblick** [kwsch/NHSE#322]
after using the save editor to edit my island, i'm no longer able to use the kiosk or visit islands, etc. online works on every other game, can visit eshop just fine, but for some reason i just can't connect online specifically ACNH

EDIT:
after reverting to my old save, i can connect to online services with no issue. I'm not sure why this is, maybe its because my newer save is a different island? but i'm not sure why that would matter when it comes to online services. I deleted my old game data before starting the new island, so no overlap i could think of.

**Comment by Lusamine** [comment]
What happens when you try to connect?
What all did you edit?
Does loading up an old save allow you to go online?

**Comment by miniblick** [comment]
> What happens when you try to connect?
> What all did you edit?
> Does loading up an old save allow you to go online?

It gives me error code: 2219-3003, which has no information online. I contacted Nintendo directly and they said it might have something to do with modifying the save file or using custon firmware to mess with the save file. I started essentially from a fresh save game, dumped all of my flags and other components to load into the new save, added in villagers, items, etc. 
I don't believe i actually have an older save. I'll have to look and get back to you on that.

**Comment by architdate** [comment]
Did restarting the game on a fresh save fix the issue?

**Comment by miniblick** [comment]
> Did restarting the game on a fresh save fix the issue?

I actually didn't check, I didn't know this issue was going to happen so i didnt think to check first. I'll restart the game again and check

**Comment by Lusamine** [comment]
Just wondering, did starting a new game fix it?

**Comment by miniblick** [comment]
> Just wondering, did starting a new game fix it?

I believe starting a new game is what caused it. I'm genuinely not sure, there's several factors i'm sure could come into play. All I know is that after reverting to an old save, everything worked fine.

**Comment by HijackHornet** [comment]
I'm getting the same error code after making a new save and importing my island and villager on it :(

**Comment by MsPhantom** [comment]
Similar issue except my old file won't connect to online services. My new file works perfectly fine.
With my old file, however, I can send and receive letters, and get notifications when someone's online, but that's it as far as online goes.

**Comment by berichan** [comment]
I am closing this issue as stale. Some unknown or illegal flag edits may cause your savefile to become unable to connect online, we don't know know what these flags are so please just load a backup if this happens to you.
