### ISSUE TITLE
Sable Patterns Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#325]
# Sable Patterns Editor

## When you build able sisters, you can talk to Sable everyday.
> If you do, she will give you patterns like normal patterns that can be used on some furniture.
> It would be nice to edit these patterns so you don't have to talk to her everyday

**Comment by berichan** [comment]
I am closing this issue as stale. If someone does the research for this then please provide any further information and I will reopen this issue, but this doesn't seem like it's simply a matter of finding a structure or single flag to turn on.
