### ISSUE TITLE
 Go through furniture or items

### ISSUE THREAD

**Issue by freddyrv** [kwsch/NHSE#326]
Hello, I wanted to comment since I have a couple of problems when I inject items into my saved file. 

1-Most items that I add to my game have no limits and can be physically tras passed, for example this prevents me from sitting in a chair or bed.

2-When I throw an item on the floor inside the house or put it, there is a star on the floor like when there is something buried.

Thanks in advance,

**Comment by kwsch** [comment]
Don't set flags on the item that it wouldn't normally have.
