### ISSUE TITLE
1.3.0 support request

### ISSUE THREAD

**Issue by Tairex777** [kwsch/NHSE#327]
Feature request:
Trying to open 1.3.0 saves gives Unknown revision, and I don't want to lose my work I did since I updated to 1.3.0

Solution
Add 1.3.0 support

Alternatives
A save data downgrader

**Comment by Tairex777** [comment]
Closed because I don't know how to remove tags.

**Comment by kwsch** [comment]
The program already supports 1.3

**Comment by Tairex777** [comment]
thanks

**Comment by beefvision** [comment]
how can i download NHSE for 1.3.0

**Comment by beefvision** [comment]
i need this one  thanks boss
