### ISSUE TITLE
Game keeps saying the Save is damaged.

### ISSUE THREAD

**Issue by lvlann** [kwsch/NHSE#329]
My process prior to the new update has been the following:

save game -- shut down game -- album -- JKSV -- backup -- restart switch to hekate launch screen -- remove sd -- insert sd in pc -- open save using nhse -- edit -- save -- remove sd and insert it in switch -- launch -- sysmmc -- album -- jksv -- restore -- open game -- play.

Now upon restoring when i open the game it says save data is damaged. Could someone tell me what i should be doing different? Why all of a sudden the data keeps being damaged? Please help

**Comment by kwsch** [comment]
If the save file loads fine in the latest NHSE build, and the hashes are verified, then this isn't an issue with NHSE.
