### ISSUE TITLE
Add Building Names Instead of Having to go off BuildingIDs 

### ISSUE THREAD

**Issue by VanishingTacos** [kwsch/NHSE#33]
Not sure if this is possible but editing buildings seems nightmarish since there is no way to tell the difference between buildings besides their buildingid. It would be a lot more user friendly if the building list had building names (ex: Museum, Nooks Cranny, Able Sister, so&sos house

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
