### ISSUE TITLE
Critterpedia sea creatures section blank after tampering with received items.

### ISSUE THREAD

**Issue by SpongeyBubby** [kwsch/NHSE#330]
So whenever I edited the received items for sea creatures in my critterpedia, the whole section appears blank. Not even the grid shows up. I tried marking every sea creature except one as captured but even when I catch that specific creature I marked as not captured, it still appears blank. Any fixes on this sort of bug would be appreciated.

**Comment by MirayXS** [comment]
why are you closing and re-opening? just asking

**Comment by SpongeyBubby** [comment]
> why are you closing and re-opening? just asking
Because I realized that the camera mod I had on was making the list not load so I kinda solved this on my own. Plus, it wasn't the editor that was causing trouble.

**Comment by MirayXS** [comment]
ah ok :D good that you fixed the issue yourself
