### ISSUE TITLE
Wrap all items in inventory to presents with one button.

### ISSUE THREAD

**Issue by sadboys2001** [kwsch/NHSE#333]
**Is your feature request related to a problem? Please describe.**

I find it easier to edit in the items I need before wrapping them in presents. It's frustrating to edit in the items I need then go back to all of them manually and wrap them.

**Describe the solution you'd like**

I would like a simple button that would wrap all items in your inventory and you could choose the color (for all of them) there so they would all be wrapped. 

**Describe alternatives you've considered**

While it is possible to add wrapping paper to items after they're in your inventory it's much more time consuming.

**Comment by SquirrelKiev** [comment]
I'm pretty sure if you select wrapped for the first item it carries over for the next item you edit in.

**Comment by berichan** [comment]
I'm closing this issue as stale. As above, selecting the checkbox will carry over to all future items.
