### ISSUE TITLE
Storage Editor doesn't show all items in-game.

### ISSUE THREAD

**Issue by miniblick** [kwsch/NHSE#335]
While using the Storage Editor, I put a lot of clothes, materials, fences, etc. All of the items have the correct count and such, and in the bottom left where the total number of spaces is, it says i still have space, but the rest of my items don't show up.

**Comment by kwsch** [comment]
You're still bound by the maximum storage count accessible in-game.

**Comment by miniblick** [comment]
> You're still bound by the maximum storage count accessible in-game.

The issue still occurs when it isn't even close to the limit. It said i only had 400/1600 spaces, i went through everything and i clearly didnt have more than the maximum. it seems like if the items are lower down in the storage menu it wont show up in-game. this could probably be fixed by having a sort button that would bring everything up to the top and get rid of the empty spaces
