### ISSUE TITLE
Edit House Wallpaper and Flooring | Player House Editor

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#336]
# Edit House Wallpaper and Flooring | Player House Editor

## There's should be options to edit the wallpaper and flooring like the villager's house editor

**Comment by berichan** [comment]
I'm closing this issue as stale. While the structure exists, there has been no interest in figuring out how it behaves. This is also very easily solved by a few seconds of normal gameplay or much faster via live injecting the wallpaper you want to test the style.
