### ISSUE TITLE
Set All Villagers Friendship to 255 | Villagers Editor, Villager Memories

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#337]
# Set All Villagers Friendship to 255
> Villagers Editor, Villager Memories

## An option to bulk-set all villager the max friendship value (255) would be great.

**Comment by kwsch** [comment]
Already exists. https://github.com/kwsch/NHSE/commit/a8f111a8f1491acd65fd729aa753b52fa1ae2213

**Comment by MirayXS** [comment]
Ooh there it is, I didn’t read the description of that commit my bad.

While I was doing italian translation I noticed that there was a string to set all villager friendship but I couldn’t find it so I thought it was something you missed, my bad :/
