### ISSUE TITLE
Modify Villager Favourite Music 

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#338]
# Modify Villager Favourite Music 

## While doing somethings i noticed that the villager's favorite music can be changed. It would be cool if it could get modified in NHSE too

**Comment by berichan** [comment]
I'm closing this issue as stale. While the structure exists it doesn't seem like there is any motivation to learn how to edit it or how the value behaves. If there are any further development or research into this then please post it here and I will reopen this issue.
