### ISSUE TITLE
I need NHSE for 1.3.0

### ISSUE THREAD

**Issue by beefvision** [kwsch/NHSE#339]
HI boss 
i relly need NHSE for 1.3.0 
how can i download this one  
thanks very much

**Comment by Conan179** [comment]
https://github.com/kwsch/NHSE/wiki/Downloading-Compiled-Builds

**Comment by GriffinG1** [comment]
Thank you for contacting NHSE customer support! An agent will be with you shortly. You are 604th in line. Estimated wait time is 2 millennium.

**Comment by architdate** [comment]
as stated by @Conan179 follow the wiki instructions to download the compiled builds
