### ISSUE TITLE
Can't Edit Save Files; Animal Crossing New Horizons Version 1.1.2

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#34]
## <li> 3. Save File Update may be the issue </li> 

Screenshot Attachment Of When I Updated To Version 1.1.2 (italian)
![image](https://user-images.githubusercontent.com/55494819/78301454-5baef600-7539-11ea-9d32-98380df71d22.png)

Translated:

```
after updating the software, the save data will now be updated.
```

> I use an emulator, the save editor works on it too but rn it doesn't since i update my game to Version 1.1.2

**Comment by MirayXS** [comment]
Get the following _**ERROR**_

![image](https://user-images.githubusercontent.com/55494819/78300010-14c00100-7537-11ea-84b0-f525bb48a5b4.png)

Path of the save file folder is good, as i said, V1.1.2 edits/updates save files and it may be the reason this issue occurs

**Comment by kwsch** [comment]
Download the latest build of the program.

**Comment by MirayXS** [comment]
OK, i'll try.

**Comment by MirayXS** [comment]
Thanks you!

**Comment by MirayXS** [comment]
Resolved right after you replied, forgot to tell you.
You can now close this issue as resolved, if you want.
