### ISSUE TITLE
Posters

### ISSUE THREAD

**Issue by IceBear199** [kwsch/NHSE#340]
is not a big inconvenient but the posters only appear when you search then not on the section where they should be

**Comment by kwsch** [comment]
You'll need to elaborate.

Items can be searched just fine.

**Comment by MirayXS** [comment]
> You'll need to elaborate.
> 
> Items can be searched just fine.

He **maybe** means the harvey posters, they have a different section in the game.

It may be the same as #242

**Comment by starkless** [comment]
The villager/character posters no longer appear in your catalog when you search for them since update 1.5.0, even if you have received the item.

**Comment by berichan** [comment]
I'm closing this issue as stale. This is issue is caused by a change caused by a game update, not something NHSE can resolve.
