### ISSUE TITLE
Using the Azure REST API to grab the latest build/artifact.

### ISSUE THREAD

**Issue by berichan** [kwsch/NHSE#343]
If it's ideal that there was a way for someone to just grab the latest published pipeline build, I've made a quick and dirty website that pulls the latest build from Azure DevOps using the Azure REST API here: https://berichan.github.io/GetNHSE/ with the source here: https://github.com/berichan/GetNHSE (written in javascript)

It could be a possibility to add the two files (index.html, scripts.js) to the root of this project, then change project settings (Settings > Scroll down to Github Pages > change "Source" to master branch) which would turn this repo into a website (that you could view at kwsch.github.io/NHSE) and put a link to it in the readme.

Or you can just ignore all that and just put a link to berichan.github.io/GetNHSE in the readme.

If it's not ideal, then the current way works too :)

**Comment by kwsch** [comment]
tyty changed the link in About and on the wiki's download page

will consider the self-host gh page in the future; currently have low computing/internet access atm :P

**Comment by MirayXS** [comment]
EPIC
