### ISSUE TITLE
Cannot change Hemisphere past ACNH V1.3.0

### ISSUE THREAD

**Issue by LuciRa1n** [kwsch/NHSE#345]
While editing the save file of the latest version of Animal Crossing New Horizons version (1.3.0) using the latest NHSE I encountered an issue where I cannot change the Hemisphere of my save file, as when I save and open it back up in game it says "The save data is damaged. Would you like to delete the damaged save data and start the game over?"... If you can fix this issue that would be amazing!

**Comment by LuciRa1n** [comment]
Accidentally marked it as an enhancement! Sorry about that!

**Comment by kwsch** [comment]
Unable to replicate issue; the game structures (offsets) were not changed for WeatherArea from [1.2.x](https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_131080_131078_pseudoC.h#L867) to [1.3.x](https://github.com/Treeki/CylindricalEarth/blob/master/savefile/save_schema_262152_262146_pseudoC.h#L868).

**Comment by LuciRa1n** [comment]
This was fixed. Thank you.
