### ISSUE TITLE
Turnip Prices don't match real price at all.

### ISSUE THREAD

**Issue by Secmess** [kwsch/NHSE#347]
I wanted to use NHSE to see Turnip price. When I match it to my own manual TT data, I go this. (EDIT: The website is my own data which I input based on what I get in-game, not prediction result.)

![image](https://user-images.githubusercontent.com/24835551/87249109-5d1c8280-c487-11ea-963e-14237cf1df90.png)

As you can see, EVERYTHING is different except the buy price. It'll only match after I save the file (even without any modification). So, does NHSE use its own arbitrary value for initializing turnip prices for a save, or does it use actual seed from the save file? If it's the latter, does it mean the algorithm is wrong?

**Comment by Conan179** [comment]
NHSE and turnip.sp say the same.
I think the webseite are wrong.

![turnip_12072020a](https://user-images.githubusercontent.com/1906242/87249537-e8821d80-c45f-11ea-9928-d8929370e74c.JPG)
![turnip_12072020b](https://user-images.githubusercontent.com/1906242/87249603-54648600-c460-11ea-964c-3ef06d00543a.jpg)

**Comment by Secmess** [comment]
No, the website is my own data, not prediction result.

The prediction result for the website is further down, which I did not include in the screenshot.

**Comment by kwsch** [comment]
Time traveling or using save files that haven't been loaded on the current week (starting Sunday) will result in the game rerolling the stalk prices for the week.

**Comment by Secmess** [comment]
>  using save files that haven't been loaded on the current week (starting Sunday)

The original save is done on current Sunday, so there's def no rerolling happening. This can be easily proven by checking the same day again, and I got the exact same result each time.
