### ISSUE TITLE
DAL flight count

### ISSUE THREAD

**Issue by IceBear199** [kwsch/NHSE#349]
can i edit the total number of DAL's filghts?

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by MirayXS** [comment]
it may be a flag, i don't know. Try to use the flag editor
