### ISSUE TITLE
Can't load save? Error message

### ISSUE THREAD

**Issue by throwawaythingy** [kwsch/NHSE#35]
Can anyone help here? I've tried to both load an older file (first version) and the most recent update, both give me this error;
"Could not load file or assemble 'NHSE.core, version=1.0 0.0, Culture=neutral, Publickeytoken=null ' or one of its dependencies. File not found"
![Screenshot 2020-04-02 at 5 15 54 PM](https://user-images.githubusercontent.com/63075297/78300529-a4e55280-7505-11ea-8a21-33d45787ce7c.png)

**Comment by kwsch** [comment]
Download and extract the entire build, not just the executable.
