### ISSUE TITLE
Item list for German language mixed up

### ISSUE THREAD

**Issue by MZ-4** [kwsch/NHSE#350]
As an example, I use the inventory editor and put the (English) items: "pirate barrel" and "sideways pirate barrel".
When I save and switch to German, the objects are named "Piratenschatzkiste" and "Ungestümgemälde (links) (fälschung)".
Vice versa, when I put the German objects "Piratenfass" and "Piratenfass (liegend)", I get "handmade cape (Red)" and "pirate-treasure chest" in English.

**Comment by kwsch** [comment]
@berichan

**Comment by berichan** [comment]
I think I got off-by-one'd. I'll fix it in a sec
