### ISSUE TITLE
Some items are acting weird?

### ISSUE THREAD

**Issue by miniblick** [kwsch/NHSE#353]
Earlier I added several items into my storage to decorate my home with. While putting them down to decorate, under the item is the graphic of a buried item. For example, I went to go place down the small wooden garbage bin, right under it was that buried item graphic. This seemed to only happen to all of the "Wooden" series items, including the double bed, which for some reason was only showing a hitbox of a single space and clipping through the wall. This item also had the buried item graphic under it, and when you pick the item up, it stays there until you walk out of the room and walk back in. I have no idea what caused this, but i ended up just removing all of those items.

**Comment by kwsch** [comment]
Bad item flag values.
