### ISSUE TITLE
Select, Drag, Drop in Field Item Editor

### ISSUE THREAD

**Issue by JustWhelmed** [kwsch/NHSE#356]
Using the field item editor takes a lot more work than I think necessary. Just to move one item to a different spot requires you to click it, right click it, reset, right click a different spot, click set, Simply being able to click and hold to drag it and drop it to where you want to move it would be a huge QoL feature imo. 

If you want to go further, being able to multi-select (right click-> multi select-> click and drag to draw a rectangle around the area you want to select) and dragging/dropping that whole area to where you'd like to move would also be a great QoL feature. To add to this, right clicking that selected area could give an option to dump it as an nhi file. Importing it would just overwrite the amount of space the area took up and no more.

Just a few things I'd love to see. Thank you for all your hard work!

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/290
