### ISSUE TITLE
Edit Island Star Rating

### ISSUE THREAD

**Issue by hidethepainharold** [kwsch/NHSE#360]
is there anyway to edit the island star rating?

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

Calculated values (like Island Rating) are not really editable; you have to arrange your island to get the rating.
