### ISSUE TITLE
I can't access my save anymore!

### ISSUE THREAD

**Issue by Eener95** [kwsch/NHSE#361]
![Annotazione 2020-07-21 145647](https://user-images.githubusercontent.com/68597409/88057513-79dd4800-cb62-11ea-9fb4-fe7fc20422ee.png)

hello everyone, I write because since I backed up the save with the latest ACNH update, I can no longer access the save every face that I try to open it I get this screen.
I ask is not that there is a program update?

thank you all for your attention

**Comment by Conan179** [comment]
Download the last Version
https://berichan.github.io/GetNHSE/

**Comment by Eener95** [comment]
thank you so much!
