### ISSUE TITLE
Sysbot

### ISSUE THREAD

**Issue by Jpofin** [kwsch/NHSE#362]
Not sure if it is documented somewhere already.

The sysbot is used to edit your inventory live without needing to reload your savegame/edit your savegame directly, correct?

If so, would it work to do that while I visit someones island (locally?) to drop them alot of items without traveling all the time?

cheers and thanks

**Comment by kwsch** [comment]
Yes
Yes

**Comment by berichan** [comment]
The switch disconnects from the access point on local network play. NHSE supports [USB-Botbase](https://github.com/fishguy6564/USB-Botbase) for what you're trying to do that works over local network play.

Sys-botbase is unaffected by non-local network play.
