### ISSUE TITLE
New window, wiki entry or better description in flag editor for Tourney points

### ISSUE THREAD

**Issue by igromanru** [kwsch/NHSE#363]
**Is your feature request related to a problem? Please describe.**
My problem was to find flags which needed to be increased to get tourney trophies.

**Describe the solution you'd like**
I would like to see a new Window or a better place for Tourney related flags to edit.

I found out that there are at least 10 flags related to Fishing and Bug Tourney.
59 - CatchFishFesCount: This isn't the count of how much fish you caught, this are points that you are using to get Fish event items. 10 points cost one item.
60 - CatchInsectFesCount: Same as above for Insects.
445 - ChyEvent_TotalPoint: This are hidden points that you collect over all Bug-off tourneys. If you reach 100 points Flick will send you a Bronze Trophy over mail, for 200 Silver and for 300 Gold.
446 - BeyEvent_TotalPoint - same as above but for Fishing tourney.
447 - ChyEvent_GetThrophyGold - Is 1 if you received the golden bug-off trophy. 
448 - ChyEvent_GetThrophySilver - Is 1 if you received the silver bug-off trophy. 
449 - ChyEvent_GetThrophyCopper - Is 1 if you received the bronze bug-off trophy. 
450 - BeyEvent_GetThrophyGold - Is 1 if you received the golden fishing trophy. 
451 - BeyEvent_GetThrophySilver - Is 1 if you received the silver fishing trophy. 
452 - BeyEvent_GetThrophyCopper - Is 1 if you received the bronze fishing trophy. 

**Describe alternatives you've considered**
Or just make a Wiki page or add descriptions to Flag Editor, so people can find right flags easier.

**Additional context**
![Screenshot_2](https://user-images.githubusercontent.com/1902937/88480453-33b72880-cf56-11ea-8f73-2302316aba83.png)
![Screenshot_3](https://user-images.githubusercontent.com/1902937/88480455-3580ec00-cf56-11ea-96e0-7aa0a97cd5ee.png)

**Comment by kwsch** [comment]
Added Wiki page.
https://github.com/kwsch/NHSE/wiki/Player-Flags

I've also changed the Wiki's permission so that anyone can edit it; hopefully that makes it easy for people to chip in info without any malice :P
