### ISSUE TITLE
Edit Received Items "Give All" Option for Furniture only.

### ISSUE THREAD

**Issue by Jacien** [kwsch/NHSE#364]
When editing Received Items, there's no option to Give All to Everything and not affect the bugs/fish/deepsea lists. I want to complete the catalog, but I want to collect the bugs/fish myself.  Is it possible for a Give Everything for furniture items only instead?  Basically it's the Everything option, but excluding bugs/fish/deepsea ones.

**Comment by Jacien** [comment]
To clarify, everything BUT bugs/fish/deepsea. So furniture, clothes, art, music, etc. I'd love to be able to unlock them all in one click.

**Comment by Hamondorf** [comment]
I would also like this feature
