### ISSUE TITLE
Villager 4 & 5 building - position swapped

### ISSUE THREAD

**Issue by R3dLyc4n** [kwsch/NHSE#365]
There seems to be an issue with the order of the villager buildings.

The index number is aligned to the building number;
Villager index 0 = Building - Villager 1
Villager index 1 = Building - Villager 2 etc..

Even thought the island map shows the buildings in the correct order/position, when you compare the buildings on the in game Island, Building - Villager 4 & Building - Villager 5 are swapped. Both the building and villager.

This is not a major issue, just though you'd like to know.

**Comment by berichan** [comment]
Villager buildings are not guaranteed to be a linear list in the savefile, see which house corresponds to which villager in the NPC1 property of each house and edit accordingly.
