### ISSUE TITLE
need 1.4.0

### ISSUE THREAD

**Issue by beefvision** [kwsch/NHSE#367]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**

**Additional context**

**Comment by berichan** [comment]
NHSE already supports 1.4.0. Download the latest build https://berichan.github.io/GetNHSE/
