### ISSUE TITLE
Offset error

### ISSUE THREAD

**Issue by Darkganymede** [kwsch/NHSE#369]
Can someone please help me on how to resolve this error!!??
![61E28049-4FC0-46FC-82F7-D5572F4FCF2E](https://user-images.githubusercontent.com/69020832/88985673-e8c34b00-d29e-11ea-8c72-9fbf69280030.jpeg)

**Comment by zyro670** [comment]
You're using the wrong offset

**Comment by Darkganymede** [comment]
> You're using the wrong offset. Read the wiki.

Whats the wiki?? Im new on this. :(

**Comment by Lusamine** [comment]
> 
> 
> > You're using the wrong offset. Read the wiki.
> 
> Whats the wiki?? Im new on this. :(

![image](https://user-images.githubusercontent.com/30205550/88987571-fc20e700-d29b-11ea-9091-b0a7296a9401.png)
Try to find it here without a red circle to guide you.  I believe in you.

**Comment by kwsch** [comment]
Use the latest commit, not one from when support was being added.
