### ISSUE TITLE
1.4.1 ver.

### ISSUE THREAD

**Issue by mozz1** [kwsch/NHSE#373]
1.4.1 The update is not working.

**Comment by Conan179** [comment]
Have you download the last Version from https://berichan.github.io/GetNHSE/ ?

**Comment by aljorai** [comment]
Hi, same issue. it says Unknown Revision! Already downloaded latest build but it seems that it was updated way before v1.4.1

**Comment by mozz1** [comment]
That's right. That's the problem for me, too! Is there any solution yet?
