### ISSUE TITLE
Import NHI on field item editor suggestion

### ISSUE THREAD

**Issue by Wolfling1** [kwsch/NHSE#376]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
"Import NHI" on field item editor. I would like an option to import NHIs (one or multiple) to the field item editor to spawn those items. Just like how spawning all DIYs works.

**Describe alternatives you've considered**
??

**Additional context**

**Comment by cpurules** [comment]
@Wolfling1 are you suggesting (a) a button in the 'items' tab to import, or (b) an option in the bulk spawner?

Mockup Option (a):
![image](https://user-images.githubusercontent.com/52503242/93250459-dcb51f00-f760-11ea-9850-1604ce41d6de.png)

Mockup Option (b):
![image](https://user-images.githubusercontent.com/52503242/93250620-171ebc00-f761-11ea-8c4f-01d906a46473.png)

Or are you talking about something else altogether?

**Comment by Wolfling1** [comment]
Yes. I'd like an option to import NHis directly onto the map. Not into inventories.
