### ISSUE TITLE
Mass Map Editing?

### ISSUE THREAD

**Issue by Jpofin** [kwsch/NHSE#377]
Hey

Is there a chance to instantly set your whole island to a giant grass pile and edit all fields at once?
I wanted to do a free gold/nmt/items island for people.

I‘ve seen alot of people doing similar stuff with clothing lately and can‘t think of them doing it manually for hours. Is there a way of doing this or is there a map editor that can?

Thanks:)!

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/commit/a1cc4de61160a9d3b6eae809a7f89208a37349dc
