### ISSUE TITLE
Nook Milestone Achievement

### ISSUE THREAD

**Issue by Tsuchan21** [kwsch/NHSE#38]
**Is your feature request related to a problem? Please describe.**
I had this problem that every time I time traveled, the date that I started which it used to be 03/23 when I edit the miles; the date keep changed such Clam and Collected or Cast Master now its 03/28. Also the fish milestones kept changed back to original which it was 30; It was supposed to be 33 which I edited for three March fishes.

**Describe the solution you'd like**
I really like to keep the cast master and clam and collected on the dates that I originally edited on or stop on that date. For fish milestones, I like to stick the edited count on.
![2020032709275400-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/17149289/78317522-7cbf1900-7530-11ea-9be5-affdd6684a12.jpg)
![2020032709280000-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/17149289/78317527-8183cd00-7530-11ea-843e-1030f343933a.jpg)
![2020032809321300-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/17149289/78317532-83e62700-7530-11ea-8320-f8702929228b.jpg)
![2020032809321700-02CB906EA538A35643C1E1484C4B947D](https://user-images.githubusercontent.com/17149289/78317537-86488100-7530-11ea-9e44-2e4bb097d830.jpg)

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
I saw that someone have alternative for hxd editor, but I don't know how to do it.

**Additional context**

**Comment by kwsch** [comment]
Requires documentation.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
