### ISSUE TITLE
not working on Mac 

### ISSUE THREAD

**Issue by radmax37** [kwsch/NHSE#382]
im on the latest update blu sur beta and I've tried downloading mono to get it to work to no avail mono keeps crashing when try to open nhse.exe pls help thank u

**Comment by kwsch** [comment]
Not an issue with NHSE. Install the correct wine components (.NET framework stuff)

**Comment by berichan** [comment]
Mono's WinForms implementation is 32-bit only. OSX no longer supports any 32-bit execution so it'll no longer work, and Apple have been vigorously and extensively removing anything that workarounds this limitation. WinForms won't work with mono at least while this issue is open: https://github.com/mono/mono/issues/6701

**Comment by FezVrasta** [comment]
> Mono's WinForms implementation is 32-bit only. OSX no longer supports any 32-bit execution so it'll no longer work, and Apple have been vigorously and extensively removing anything that workarounds this limitation. WinForms won't work with mono at least while this issue is open: https://github.com/mono/mono/issues/6701

Any chance NHSE could migrate to a cross platform solution?

**Comment by kwsch** [comment]
> > Mono's WinForms implementation is 32-bit only. OSX no longer supports any 32-bit execution so it'll no longer work, and Apple have been vigorously and extensively removing anything that workarounds this limitation. WinForms won't work with mono at least while this issue is open: [mono/mono#6701](https://github.com/mono/mono/issues/6701)
> 
> Any chance NHSE could migrate to a cross platform solution?

Sure, do you volunteer to rewrite the GUI project?

**Comment by FezVrasta** [comment]
If there was some kind of REST API or socket communication to easily talk with the "backend" I could see myself writing an Electron frontend. But as far I see everything is pretty Windows specific right now 🤔

**Comment by berichan** [comment]
> If there was some kind of REST API or socket communication to easily talk with the "backend" I could see myself writing an Electron frontend. But as far I see everything is pretty Windows specific right now 🤔

Nothing is "Windows specific" besides the GUI project. All core NHSE logic can be compiled to cross-platform .NET standard libraries, and Electron.NET allows for linking of .NET libraries. If you must use native Electron you may use Edge.js
