### ISSUE TITLE
Something you aren't aware of yet

### ISSUE THREAD

**Issue by nickyo1011** [kwsch/NHSE#387]
Hello, so this isn't an issue but maybe something you aren't aware of! There is this server that I realized the developers of NHSE aren't in yet, some of the contributors are but not all. [Click Here To Check Out Our Top.gg page](https://top.gg/servers/705645517044056134) here it is, you should really join as it was the first-ever ACNH hacking server to exist, some other ones exist but this one has more features and we are trying to get more developers. Please consider joining as it would be an honor to have you on our server. We have special things that other hacking servers don't provide as well! I won't spoil it though, on joining I will give all the developers of NHSE the Developer role!

**Comment by architdate** [comment]
Please do not advertise unofficial discord servers on the GitHub repository. There already exists a server for NHSE development. Another one is redundant.
