### ISSUE TITLE
fish print wrong Variation. Black-White is not exist

### ISSUE THREAD

**Issue by Soopoolleaf** [kwsch/NHSE#388]
not exist 'Black-White'

![20200826_115452](https://user-images.githubusercontent.com/59555129/91250117-372b1300-e793-11ea-9cbc-54e55da8d7fc.png)

**Comment by berichan** [comment]
This was also fixed 5 days ago in cba0abda72164ce6234a15893d811db691b3a585 so please use the latest version before creating github issues.

![image](https://user-images.githubusercontent.com/66521620/91444613-e851ac00-e86c-11ea-9877-fe105388647e.png)
