### ISSUE TITLE
crest doorplate 'Colorful' color not exist.

### ISSUE THREAD

**Issue by Soopoolleaf** [kwsch/NHSE#389]
![20200826_121549](https://user-images.githubusercontent.com/59555129/91251268-04364e80-e796-11ea-89ae-a6b9e5c0e4ac.png)
![20200826_121532](https://user-images.githubusercontent.com/59555129/91251270-04cee500-e796-11ea-85e5-e28c9fa71d62.png)
![20200826_121703](https://user-images.githubusercontent.com/59555129/91251291-0f897a00-e796-11ea-88da-401874b0728a.png)

**Comment by berichan** [comment]
Colorful does exist. Please make sure you are using the latest version of NHSE.

![image](https://user-images.githubusercontent.com/66521620/91444048-1682bc00-e86c-11ea-8105-ed84db98d041.png)
