### ISSUE TITLE
HOW TO GET DIY RECIPE?

### ISSUE THREAD

**Issue by Yokixio** [kwsch/NHSE#39]
NOT FOR THE GAME, THE DIY CECIPE, OBJECT

**Comment by Yokixio** [comment]
I REALLY DONT'T KNOW THE FLAG2

Kurt <notifications@github.com> 于2020年4月3日周五 下午12:37写道：

**Comment by architdate** [comment]
You can just check the flag in the source code

**Comment by Yokixio** [comment]
Thank u.发自我的华为手机-------- 原始邮件 --------发件人： Archit Date <notifications@github.com>日期： 2020年4月3日周五 13:15收件人： kwsch/NHSE <NHSE@noreply.github.com>抄送： Yokixio <whitenightyuki@gmail.com>, Author <author@noreply.github.com>主    题： Re: [kwsch/NHSE] HOW TO GET DIY RECIPE? (#39)
You can just check the flag in the source code
