### ISSUE TITLE
Allow to copy/paste terrain or items areas

### ISSUE THREAD

**Issue by FezVrasta** [kwsch/NHSE#395]
**Is your feature request related to a problem? Please describe.**
I'm trying to cover an island with a specific road pattern but at the moment the tool forces me to manually set every single cell.

**Describe the solution you'd like**
It'd be useful if one could select multiple cells and copy/paste them on a different position.

**Describe alternatives you've considered**
Having a way to apply a specific terrain or cell props to a selected area in one click would be a good alternative.

**Additional context**

**Comment by kwsch** [comment]
There already are hotkeys to perform actions on the cell. Read the wiki.

Multi-select is not implemented, and is not something I'm interested in implementing.

**Comment by FezVrasta** [comment]
Reading your answers it seems like you’d be open to PRs to implement it. If this is correct then keeping this issue open with a “Help Wanted” badge would help signaling possible contributors about what work they could undertake
