### ISSUE TITLE
Flower Genetics differ from checked boxes

### ISSUE THREAD

**Issue by agentkk00** [kwsch/NHSE#397]
It's a minor issue, but I placed purple mums and checked the boxes for r1, y1, and y2. The field item I placed after that indicated that they had w1 and w2 checked as well, but when I viewed the flowers I placed, the check marks stayed the same as when I initially placed them. I checked online for the differences in flower breeding to see if I could find something remarkable that would prove either one was correct. Sure enough, the w1 and w2 I had not checked were present in the flowers, because they produced a red flower in-game instead of a green one. I'm not sure if this is the same for other flowers or if it's just the mums, but I thought it might be worth bringing up. I tested the editor to see what would happen if I checked the boxes for w1 and w2, and it seems to have fixed the issue--the flowers' genes in the field are now r1, y1, and y2 without the genes for white flowers, despite having the box indicating the gene as present. It should be noted that taking only one of the white genes away results in one still being present, and the issue only arises when both or neither are checked. Whether this is something that needs to be fixed or not, I do hope this will remind others to always check the field item's genes before proceeding. Thank you for your time.

I will also note that I checked the issue with roses just now, and the issue does not appear to be specific to mums. When a box for a white gene is unchecked, it gets marked as present in the field, while a checked box will appear as a missing gene. This does not hold true for red, yellow, or special genes, as those all function as expected.

![Illustration](https://user-images.githubusercontent.com/51296164/93830976-a6cfd900-fc3f-11ea-895b-a58cc93fbc24.png)

**Comment by kwsch** [comment]
Related: https://github.com/kwsch/NHSE/commit/ed53d331d9e0e2840332b53a84702c16da2fa411

**Comment by berichan** [comment]
I'm closing this issue as stale. It seems to be solved in any case as of kwsch's comment above
