### ISSUE TITLE
EncryptedInt32

### ISSUE THREAD

**Issue by pakojch** [kwsch/NHSE#400]
I just update NHSE and try to use in a savefile with the new Animal crossing update (halloween) and when i put the folder, an error "Failed to verify the EncriptedInt32 at offset" is showing. If I use an old savefile folder works finel.

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/94637820-52ef7080-028d-11eb-8f3f-00e481e3a81f.png)
