### ISSUE TITLE
1.5.0 NHSE Villager 'Moving Out' Function is not working

### ISSUE THREAD

**Issue by Soopoolleaf** [kwsch/NHSE#405]
1.5.0 NHSE Villager 'Moving Out' Function is not working. 
If I Villager's check moving out box, the Villager is got boxes but I talked the Villager's not saying about they moving out message. 
and Other people can't get the Villager. even people talked the Villager. 
It's error.

**Comment by kwsch** [comment]
Be sure you're using the latest commits; the Villager format was fixed a few commits ago to use the new offset layout.

![image](https://user-images.githubusercontent.com/6393368/94715880-e747ea80-0302-11eb-82db-2b7b17868084.png)

Also,

```cs
        public static string MsgMoveOut { get; set; } = "Are you trying to make the Villager move out?";
        public static string MsgMoveOutSuggest { get; set; } = "If so, set the Event Flag (024 - ForceMoveOut) to 1 so that the Villager is removed by the game.";
        public static string MsgMoveOutAll { get; set; } = "This will check the 'Moving Out' box for all Villagers.";
```
