### ISSUE TITLE
Max Item Count broken by 1.5.0?

### ISSUE THREAD

**Issue by beanythemusicalfruit** [kwsch/NHSE#410]
The functionality of setting the max count of an item stack by double clicking count is not working as of the newest ACNH update 1.5.0.  
On the latest version of NHSE.  
Manually setting the array count for the item does work at this time.

**Comment by cpurules** [comment]
This functionality is still working on my end... what item are you trying to max stack?

**Comment by beanythemusicalfruit** [comment]
Various fencing.  Maple leaves and cherry blossom petals.  A few various items that it worked for before the last update.

**Comment by cpurules** [comment]
These are all working fine on my end so I'm not sure what the issue could be here but it doesn't appear to be code-related.
