### ISSUE TITLE
NHSE = InvalidArgument

### ISSUE THREAD

**Issue by Darkganymede** [kwsch/NHSE#412]
NHSE _"InvalidArgument = The value ‘238
![9ADF1C54-9381-4331-B5EF-46D78B3FE72B](https://user-images.githubusercontent.com/69020832/95503359-42b84f00-0979-11eb-9fd0-589fe1de417c.jpeg)
' is not valid for 'SelectedIndex'
Parameter name: SelectedIndex

Can someone help me!! I’ve try all but all i find is this erro with value 0 and mine is value 238

**Comment by kwsch** [comment]
You can still hit continue.

You've likely used a bad cheat code which damaged part of your save file.

**Comment by Darkganymede** [comment]
And how can i fix it? It keep messing up my game.

**Comment by Darkganymede** [comment]
> You can still hit continue.
> 
> You've likely used a bad cheat code which damaged part of your save file.

And how can i fix it? It keep messing up my game.

**Comment by kwsch** [comment]
Again, you can still hit continue and try to change whatever didn't load correctly.

Restore a backup save file before you cheated, or just ignore this error window and hit continue any time you want to edit the save data.
