### ISSUE TITLE
Save Transfer Issues

### ISSUE THREAD

**Issue by Aerogizz** [kwsch/NHSE#417]
It has come to my realization that if you have Nintendo transfer a game save from a different switch, onto your CFW switch, you can no longer using NHSE properly. Using the inject fails, inventory numbers are wrong, various other things. I even noticed that transferirng the save via FTP takes way longer than it normally does for a non-transferred save. I'm not sure if this use-case scenario has been run into yet. I have a save file of a transferred save if it is needed. I did test this between my 2 CFW switches. 1 of them had a nintendo switch lite save transferred onto it. That save file no longer works properly with injection. My main CFW with my original save still works fine. I'm assuming however they transfer a save on top of another messes with the file in a certain way that NHSE doesn't account for.

**Comment by kwsch** [comment]
> Using the inject fails, inventory numbers are wrong

Refer to the wiki, not an issue with NHSE.

> transferirng the save via FTP takes way longer than it normally does

not an issue with NHSE.

>  That save file no longer works properly with injection.

Injection is not save file editing. Refer to the wiki section.

**Comment by Aerogizz** [comment]
Alright, if you don't want to acknowledge the save file being completely different. There is an issue with NHSE. Pocket count 1 should be 20 and so should pocket count 2. After the save file changing, pocket count is now 2147483647 on both of them. Red box because it isn't a valid count. Just saying, NHSE doesn't support whatever new save file this is. However Nintendo overlays an old save onto a new switch effects the data. NHSE is unable to properly read that specific part of the file(inventory), which in turn, causes issues when injecting. I realize FTP and injection is separate.

**Comment by kwsch** [comment]
There are different RAM offsets for each patch, listed in the wiki.

Using cheat codes or other applications without validation protection can result in corruption of your save data.
