### ISSUE TITLE
Wallet count is broken

### ISSUE THREAD

**Issue by Ekibunnel** [kwsch/NHSE#42]
**NHSE version** : commit deb4d5114979e0f1b7a1d6abef301803f4f3af27
**ACNH save version** :  1.1.0

Wallet is broken and display a wrong value, other such as bank bells or Nook miles work fine.

![Wallet don't match](https://i.imgur.com/AfQvPsh.png)

**Comment by AldoEmmerth** [comment]
I can confirm this mismatch. Game is 1.1.0 and NHSE is same

**Comment by kwsch** [comment]
```cs
        public override int Wallet => 0x11590; // +0x18 from v1.0
        public override int NookMiles => 0x11588; // +0x18 from v1.0
```

Please dump your Villager's personal data and post the 0x20 region from 0x11580 - 0x115A0.

**Comment by Ekibunnel** [comment]
```
 -> Decrypted save\Villager0\personal.dat

0x1570: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................ 
0x1580: 00 00 00 00 00 00 00 00 FE 46 42 3B D0 AD 06 94  ........þFB;Ð­.” 
0x1590: 8A C4 E3 CF 37 D5 1A D3 06 1B 04 00 00 00 00 00  ŠÄãÏ7Õ.Ó........ 
0x15A0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................ 
```
In this save I have `39 100` bells in the wallet.
###### If needed I can provide my save, just ask.

**Comment by kwsch** [comment]
Closed by https://github.com/kwsch/NHSE/commit/92959fba6a734b8c1ef4514fff885244f061827f
