### ISSUE TITLE
New Update missing color info

### ISSUE THREAD

**Issue by sapycola** [kwsch/NHSE#423]
Hi, 
new update missing color info. 

For example: count 1 for kid's tent pink, count 2 for black... etcc...

GREATTTT 👍

**Comment by kwsch** [comment]
Color info is already in the program:

https://github.com/kwsch/NHSE/blob/750d15f9039904a0a8579e9dd9ba0484d2f3332f/NHSE.Core/Structures/Item/Remake/ItemRemakeInfoData.cs#L695

**Comment by sapycola** [comment]
but on Gui don't see info label

**Comment by sapycola** [comment]
[![Cattura.png](https://i.postimg.cc/Fzfxnn9G/Cattura.png)](https://postimg.cc/YLHgvRLm)

**Comment by sapycola** [comment]
and give all diy not include last update. :D
thanks! @kwsch

**Comment by sapycola** [comment]
Confirm.

Closed. WORK.

GREAT kwsch
