### ISSUE TITLE
Can't open save as of most recent build

### ISSUE THREAD

**Issue by mn6** [kwsch/NHSE#426]
Hi, I just dumped my save and tried to open it with the latest build and it isn't working. Below is the error.

![Error](https://i.imgur.com/3B8pTED.png)

**Comment by klutch5398** [comment]
> Hi, I just dumped my save and tried to open it with the latest build and it isn't working. Below is the error.
> 
> ![Error](https://camo.githubusercontent.com/cafbb68aeaf55707f856a53f07132e1497fd786a7313e8f3d17edf6d06b73d19/68747470733a2f2f692e696d6775722e636f6d2f334238705445442e706e67)

Download the latest NHSE again or dump your save file after it's updated in game and try again. This is an error on your end, not NHSE.

**Comment by mn6** [comment]
I actually had to get the latest build straight from Azure. The one on the website was not latest.

**Comment by kwsch** [comment]
@mn6 "The one on the the website"

There is no "website" besides the azure downloads linked to from this repository. Other sites reuploading stale builds is not an issue with NHSE.

**Comment by mn6** [comment]
Yeah, I just meant the https://berichan.github.io/getnhse/ website. I figured it was official. I downloaded straight from there, tried out my save, and when it failed, went straight to Azure, downloaded that version, and it worked. I then made this issue.

**Comment by berichan** [comment]
> Yeah, I just meant the https://berichan.github.io/getnhse/ website. I figured it was official. I downloaded straight from there, tried out my save, and when it failed, went straight to Azure, downloaded that version, and it worked. I then made this issue.

The azure downloads and my github page you've linked both point to the same build. You'd definitely not downloaded the latest or had a stale build from when NHSE was updating when you made this issue.
