### ISSUE TITLE
Broken Reactions UI interface since Halloween Update and 1.6 Update

### ISSUE THREAD

**Issue by klutch5398** [kwsch/NHSE#427]
The current NHSE build still does not have the current Reactions available under Player --> Edit Reactions.

Even when you go to -->Give All--> It only gives up to 43 Reactions. 
The game now has a total of 54 Reactions. +2 New Halloween Reactions and the +9 from Update 1.6

I have attached a screenshot of the additional reactions that aren't showing up in NHSE.

Additionally, the UIlist shortcut screen does not display the current Reactions the player has on their character in the game. Even changing this through the editor and loading up the save does not change it for the character in game. 

Thanks for looking into this and hope there is a fix for it! :)
![reactions missing](https://user-images.githubusercontent.com/69431446/99883613-9499f900-2bf6-11eb-91ac-a3a1e700b74e.png)
![giveall](https://user-images.githubusercontent.com/69431446/99883614-95328f80-2bf6-11eb-94e5-3f24503de874.jpg)
![UIlist](https://user-images.githubusercontent.com/69431446/99883615-95328f80-2bf6-11eb-8f9b-16326cda66dc.jpeg)

**Comment by kwsch** [comment]
Reactions are defined here:

https://github.com/kwsch/NHSE/blob/3e689c95bfd5b51d6d000a57a60143bd69055eaf/NHSE.Core/Structures/Misc/Reaction.cs#L6

Someone would have to provide a list of the indexes for the new reactions, or just add them to this reaction enum in the correct way.

**Comment by kwsch** [comment]
Original structure:
```c
struct GSavePlayerManpu {                          /* 0x88 big, align 1 */
  u8                                ManpuBit[64];                           // @0x0 size 0x1, align 1
  u8                                UIList[8];                              // @0x40 size 0x1, align 1
  bool                              NewFlag[64];                            // @0x48 size 0x1, align 1
};
```

Current structure (revised in Halloween patch):
```c
struct GSavePlayerManpu {                          /* 0x208 big, align 1 */
  u8                                ManpuBit[256];                          // @0x0 size 0x1, align 1
  u8                                UIList[8];                              // @0x100 size 0x1, align 1
  bool                              NewFlag[256];                           // @0x108 size 0x1, align 1
};
```

Note how the size has ballooned from 64->256.

The current implementation has a hardcoded 64...
https://github.com/kwsch/NHSE/blob/821b9bf5e57215c6e4ff5bde8a9f36f74cccfaa7/NHSE.Core/Structures/Misc/GSavePlayerManpu.cs#L7-L11
