### ISSUE TITLE
No DIY Recipes

### ISSUE THREAD

**Issue by hooliganXI** [kwsch/NHSE#429]
Before the previous update, we were able to add DIY recipes to our inventories. Is there a new way to do this or was this taken out?

**Describe alternatives you've considered**

**Additional context**

**Comment by kwsch** [comment]
Parenthesis are around "DIY recipe".

![image](https://user-images.githubusercontent.com/6393368/100026010-ca79e180-2d9e-11eb-860a-ffd93ece60fb.png)
