### ISSUE TITLE
Dream Islands Flags

### ISSUE THREAD

**Issue by Ixaruz** [kwsch/NHSE#430]
[v1.6.0]
So recently I copied an entire dream island + their inhabitants into a blank save file template for archiving purposes.

Thing is, it still had some dream-specific flags enabled.
A couple of months ago I dumped my own island as a dream and compared the files (bc switch RE is not easy).
Only two flag differences in the dream were:
346 - IsDreamingBed = 1 instead of 0
354 - TapDreamEnable = 0 instead of 1

Problem is, when I apply the fixes, the dream bed and gyroid go away, but not the "Custom Design Portal".

I would like to receive some help on this, bc this is not only an eyesore, the game will crash when trying to 
"check out this dream provider's custom designs"

![Screenshot](https://user-images.githubusercontent.com/44379110/100089282-bb07a080-2e51-11eb-8d08-e7d0c39345e7.png)

also here a decrypted version of the save, before applying fixes and booting it up ingame.
[Template.test.zip](https://github.com/kwsch/NHSE/files/5589554/Template.test.zip)

**Comment by kwsch** [comment]
Replace bits and pieces of the savefile at a time to see what replacement causes the design portal to appear.

Closing since research requests are unrelated to NHSE.
