### ISSUE TITLE
Request for festive wrapping paper option

### ISSUE THREAD

**Issue by buttonh** [kwsch/NHSE#431]
**Is your feature request related to a problem? Please describe.**
I'd like to wrap a ton of things in the new festive wrapping paper but I don't see it as an option with the other colors.

**Describe the solution you'd like**
It'd be awesome to have it as an option in the drop down menu when wrapping items

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Wrapping items in other colors that aren't as cute, pouting.

**Additional context**

**Comment by kwsch** [comment]
There are only 16 permissible Wrapping paper types, as per the structure of the item.

https://github.com/kwsch/NHSE/blob/832a6717f88a45783df9af0ce6fcea7a0fa5805e/NHSE.Core/Structures/Item/Item.cs#L54

All 16 are documented here:

https://github.com/kwsch/NHSE/blob/084542d367b88056bc573d3ea01c7887762628d1/NHSE.Core/Structures/Item/ItemWrappingPaper.cs#L6-L23

If there is a different (newly added) wrapping type, then it would need to be researched.

> Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

I'm not going to investigate this myself, but the first place I would look is to see the raw data for the item with Festive wrapping, to see how it differs from other item data. [Suspect is Wrapping80, a currently unknown-bit.](https://github.com/kwsch/NHSE/blob/084542d367b88056bc573d3ea01c7887762628d1/NHSE.Core/Structures/Item/Item.cs#L77-L81)
