### ISSUE TITLE
My changes doesn't save 

### ISSUE THREAD

**Issue by JoanBlade** [kwsch/NHSE#432]
i had changed my save data but when i start the game it starts without the new objets, villagers, money... why? can someone help me? i use an emulator called Ryujinx. I had tried in game version 1.5 and 1.6

**Comment by kwsch** [comment]
Make sure your game loads whatever changes you've made by importing your modified save file correctly.

**Comment by JoanBlade** [comment]
i'm sure that's correct, maybe is due of the version 1.6 or the emulator?

**Comment by JoanBlade** [comment]
okey, it's working now, it was my fault. The images must be downloaded before change anything in tools > item images. Once it is done my changes are visible in the game.
Thanks, i hope this will be usefull for someone
