### ISSUE TITLE
Stackable item limit guide

### ISSUE THREAD

**Issue by Shyshypup** [kwsch/NHSE#434]
Currently when placing a stackable item with the editor you can set the amount for the item but if you go over the normal stack amount it reverts back to a single item. The main way to avoid this is to do a web search to find how many are in a stack. It would be nice to have a guide in the editor on what the stack limit is for each item (for those that stack of course). Perhaps make a stack limit guide and place it near the area where the color guide is for furniture.

**Comment by kwsch** [comment]
Already is a feature built into the program.

https://github.com/kwsch/NHSE/pull/396

(I searched "stack" within the repo).

There's also the wiki:

https://github.com/kwsch/NHSE/wiki/Item-Editing

* Items always have a default quantity of 1. 
    * Items that can stack use the "count" value to track how many *extra* the item has. If the `Count` of an item is 7 in NHSE, then you have a total of 8 of the item stack in-game.
    * For items with **color/variation**, the "count" value is instead used to denote the variation.

**Comment by Shyshypup** [comment]
Ahh. I never would have thought of hitting the word “count” for an auto count adjustment. Thanks so much for the info 🙂
