### ISSUE TITLE
Tool for encrypting/decrypting save files

### ISSUE THREAD

**Issue by Ixaruz** [kwsch/NHSE#435]
So I have a couple of decrypted save files for personal research purposes, but NHSE will only allow to load decrypted save files over an already opened (and encrypted) save file.

I assume the way it's currently implemented is for people who already have an encrypted file and just can dump and load a decrypted version over the encrypted file. In my case, I don't have an encrypted file to write my decrypted file over.

**Describe the solution you'd like**
A Tool option to just simply decrypt/encrypt an entire folders content or single files without having to have anything else open.

**Describe alternatives you've considered**
I used to use [HorizonCrypt](https://github.com/Cuyler36/HorizonCrypt) but Cuyler36 dropped support for this, so its not a viable option for 1.6.0 save files.

It's also possible to just use a random encrypted Save File (it must have the same amount of Players tho) and load my decrypted Save over it, but it is far from ideal imo.

**Comment by kwsch** [comment]
The header files are required for encrypting save files. Importing a decrypted save into NHSE does not require these original header files, as it uses the currently loaded save file's headers.

All of the business logic for NHSE is in `NHSE.Core`. Anyone can reuse this library (like is done for other apps like ACNHMobileSpawner or SysBot.AnimalCrossing) to reuse the public methods/types as an API.

The following method is what you'd want to use:

https://github.com/kwsch/NHSE/blob/c027a2cb44614c4ced64c9f5b657ed5b26d16743/NHSE.Core/Encryption/Encryption.cs#L61-L80

Pass in your decrypted data, `DateTime.Now.Ticks`, and the header file, and it'll return the encrypted save file parts.

https://github.com/kwsch/NHSE/blob/c027a2cb44614c4ced64c9f5b657ed5b26d16743/NHSE.Core/Encryption/EncryptedSaveFile.cs#L3-L6

You can then save it the same way the program does, if you want to provide the paths yourself.

https://github.com/kwsch/NHSE/blob/c027a2cb44614c4ced64c9f5b657ed5b26d16743/NHSE.Core/Save/Meta/EncryptedFilePair.cs#L44-L46

**Comment by Ixaruz** [comment]
that's a big help, thanks man.
