### ISSUE TITLE
Bulk Edit Terrain/Adding Items, Cliffs, and Zooming In/Out

### ISSUE THREAD

**Issue by LadyHaywood** [kwsch/NHSE#436]
I understand there are already 2 ways to bulk edit the terrain, they're both pretty extreme. Unless I'm missing something in the options, but it would be nice to be able to "draw" so as the mouse moves when holding shift the item/terrain that is selected continue with it. I hope that makes sense.

Another way I feel would be helpful is highlighting an area. This one I'm really unsure how to explain well enough, but basically like making a solid square of grass or trees to quickly go over a thing of water. Or making a square that isn't filled (so, like a border) that'll go around an area instead of taking over it.

I would also like to see a better explanation of how the placing cliffs work. I know there are the numbers to go by but I've found myself placing cliffs that I think should work only to see an open void on the side or, if it's in the middle where I can't see the voice, it's still there and I can't break the middle piece. Just having that description in the editor or just a ref sheet would be fine.

Finally, being able to zoom out of the map would be nice to be able to see more.

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/308
