### ISSUE TITLE
Unknown revision when opening main file

### ISSUE THREAD

**Issue by junhaw** [kwsch/NHSE#437]
I have downloaded the latest version oh nhse but after I used it and I tried opening it again and it said unknown revision major = 0x0, minor 0x0, HeaderRevision = 0, Unk1 = 0, SaveRevision = 0, Unk2 =0. Pls reply the solution as quick as possible

https://user-images.githubusercontent.com/71067896/102677049-73b7ca00-41db-11eb-85ca-94775beef989.png

**Comment by klutch5398** [comment]
> I have downloaded the latest version oh nhse but after I used it and I tried opening it again and it said unknown revision major = 0x0, minor 0x0, HeaderRevision = 0, Unk1 = 0, SaveRevision = 0, Unk2 =0. Pls reply the solution as quick as possible
> 
> https://user-images.githubusercontent.com/71067896/102677049-73b7ca00-41db-11eb-85ca-94775beef989.png

It's because....you definitely indeed, do not have the latest NHSE. 
That, or you are using an edited save file that wasn't updated in AC first. 
If that's the case, update the save file, then extract it with JKSV to be edited in NHSE. 

^^Do those first

**Comment by junhaw** [comment]
> > I have downloaded the latest version oh nhse but after I used it and I tried opening it again and it said unknown revision major = 0x0, minor 0x0, HeaderRevision = 0, Unk1 = 0, SaveRevision = 0, Unk2 =0. Pls reply the solution as quick as possible
> > https://user-images.githubusercontent.com/71067896/102677049-73b7ca00-41db-11eb-85ca-94775beef989.png
> 
> It's because....you definitely indeed, do not have the latest NHSE.
> That, or you are using an edited save file that wasn't updated in AC first.
> If that's the case, update the save file, then extract it with JKSV to be edited in NHSE.
> 
> ^^Do those first

then where can i find the latest ver i thought the latest ver is on dec 8?

**Comment by junhaw** [comment]
and now when i open animal crossing my file is corrupted

**Comment by junhaw** [comment]
I need to start over

**Comment by junhaw** [comment]
or is there anyway to fix a corrupted file?

**Comment by Lusamine** [comment]
Use a backup file.

And if you don't have a backup before you started editing, well... live and learn?
