### ISSUE TITLE
Flags to stop villager from moving out?

### ISSUE THREAD

**Issue by MapleStoryPSN** [kwsch/NHSE#438]
If one accidentally tells a villager to move out, is there a way to undo the action via NHSE? Not sure which flags are used to prevent a move out. Thanks in advance!

**Comment by klutch5398** [comment]
> If one accidentally tells a villager to move out, is there a way to undo the action via NHSE? Not sure which flags are used to prevent a move out. Thanks in advance!

Yes, just untick the moving out box in NHSE under the villagers tab. Also, even if they did move out, just inject a new one?

**Comment by MapleStoryPSN** [comment]
> > If one accidentally tells a villager to move out, is there a way to undo the action via NHSE? Not sure which flags are used to prevent a move out. Thanks in advance!
> 
> Yes, just untick the moving out box in NHSE under the villagers tab. Also, even if they did move out, just inject a new one? Also, this isn't an NHSE issue or question. You can ask this in the server next time.

I was clearly asking which flags undoes a move out and it was NOT unticking the move out box, as that was already unticked when loading my file.

I found the fix already, which was to edit player memories of said villager and set "NextMoveOutTalk = 0" (it was set to 1) which allows the villager to ask you again if you want them to move out or not. I already have all the villagers I want, the issue was that a secondary profile initiated the move out when it was done on accident.
