### ISSUE TITLE
Unable to edit a newly generated DIY object

### ISSUE THREAD

**Issue by dockysan** [kwsch/NHSE#441]
I'm not sure when this started happening because I have always copied and edited pre existing DIY objects, but I wanted to start a new island and clear everything up. When I tried spawning in a DIY recipe the input box didn't appear for some reason, and I can't use an older object because there are no items on the ground on my new island.
![image](https://user-images.githubusercontent.com/77553101/104823290-139b5e80-5841-11eb-9f83-c8a59ef78c37.png)
I just want you to be aware of this error. An alternative fix for me is that I can always go back and dump/import one of my old acres with a DIY on it, but just keep this in mind please 😊

**Comment by kwsch** [comment]
`DIY for Beginners` isn't the same item as `(DIY recipe)`
