### ISSUE TITLE
Villagers in Boxes

### ISSUE THREAD

**Issue by PokemonTKB** [kwsch/NHSE#444]
I am trying to put 10 villagers in boxes.

 I load the villager and add the nhv file I save it.
Then I load the house and nhvh file i save it.
Then I click the villager in boxes and change line 24 to a 1 to move them out.
Then file save, then save.
But, when I load the game all of their houses are not there.  Their houses have the big green and white fence outside like they are being built.
What am I doing wrong?  Any help would be appreciated! 
Thank You

**Comment by berichan** [comment]
Ensure all villagers are unique, MoveInCompletion (flag 5) is set to 1, and AbandonedHouse (flag 9) is set to 0.

**Comment by klutch5398** [comment]
> I am trying to put 10 villagers in boxes.
> 
> I load the villager and add the nhv file I save it.
> Then I load the house and nhvh file i save it.
> Then I click the villager in boxes and change line 24 to a 1 to move them out.
> Then file save, then save.
> But, when I load the game all of their houses are not there. Their houses have the big green and white fence outside like they are being built.
> What am I doing wrong? Any help would be appreciated!
> Thank You

Additionally, on top of what Berichan mentioned, you do NOT need to set flag 24 to 1. You are misreading the prompt. Setting it to 1 will make them force moved out and they won't be in boxes. You just click Ok when you get that message. No need to change the flags.

![image](https://user-images.githubusercontent.com/69431446/105643437-d85ee800-5e5d-11eb-87d8-6b2d9339aaee.png)

Also, there is a box all villagers function built-in
