### ISSUE TITLE
Tell me about pocket is full but it doesn't.

### ISSUE THREAD

**Issue by goee222** [kwsch/NHSE#45]
I got an issue.
The game keep telling me my pocket is full  when my first two rows from top (slot 1 ~ 20) posing items.
In this situation , I can't buy anything . Sure I can put my items down to  last  20 slot(21~40) , but it just inconveniences.
If I put my tool on last  20 slot(21~40) , they can't be detect by tool ring .
It bother me so much .

I am not a english user actually , hope my poor english desen't bother .

**Comment by kwsch** [comment]
Set the UpgradePocket30 and UpgradePocket40 flags in the player's data.

**Comment by goee222** [comment]
> 
> 
> Set the UpgradePocket30 and UpgradePocket40 flags in the player's data.

I already tried it , but the condition has not improved.
Maybe I need to buy the pocket stuffing again with normal way ?
But I don't know which flag I need to cancel .

**Comment by HijackHornet** [comment]
Same issue, upgrade didnt fixed. This shouldnt have been closed

**Comment by berichan** [comment]
> Same issue, upgrade didnt fixed. This shouldnt have been closed

This is a documentation/research request, which isn't related to the development of this program.
These have already been documented if you did a little searching;
Set flags 669, 670 and 672 to '1' then change Pocket Count 2 to 20.

**Comment by HijackHornet** [comment]
> Set flags 669, 670 and 672 to '1' then change Pocket Count 2 to 20.

This didnt work. I had to remove the diy from my recieved list, change pocket count 2 to 0, and 669, 670 & 672 to '0'
This above post explains how your solution isnt working. You actually have to remove it and rebuy it with miles for it to work correctly. Else you have "bugged" pockets

**Comment by ominemon** [comment]
Hey HijackHornet, I had the exact same issue as you and your method actually helped me fix it, Thanks for the heads up sorry the dev isnt listening

**Comment by berichan** [comment]
This isn't a case of "the dev isn't listening"

Both of you edited your save incorrectly to attempt to unlock more pocket slots, and did what I told you to do in reverse to revert back to the state before you made any edits.
The message I posted is the correct way to unlock all item slots on a unedited save.

**Comment by HijackHornet** [comment]
Doing your method is what got me the bugged pocket. So yeah my solution is to do it in reverse and unlock them through vanilla means as the save editing doesnt seems to work.
I'm not saying its a case of dev not listening.
All i'm saying is that your method got me large pockets but that would be bugged and behave stranggely when picking up items (they wouldnt stack on the 3rd and 4th line).

Anyway, if my comment helped someone, it was worth posting.

**Comment by Justerbelmont** [comment]
> > Set flags 669, 670 and 672 to '1' then change Pocket Count 2 to 20.
> 
> This didnt work. I had to remove the diy from my recieved list, change pocket count 2 to 0, and 669, 670 & 672 to '0' This above post explains how your solution isnt working. You actually have to remove it and rebuy it with miles for it to work correctly. Else you have "bugged" pockets

Hello, your comment really helped me a lot. However, I want to use a save file from others but the pocket upgrade has been sold. Even though I set the flags to 0 but I can’t buy them by miles again. Is there any way to fix it?

**Comment by plumprumps** [comment]
> > > Set flags 669, 670 and 672 to '1' then change Pocket Count 2 to 20.
> > 
> > 
> > This didnt work. I had to remove the diy from my recieved list, change pocket count 2 to 0, and 669, 670 & 672 to '0' This above post explains how your solution isnt working. You actually have to remove it and rebuy it with miles for it to work correctly. Else you have "bugged" pockets
> 
> Hello, your comment really helped me a lot. However, I want to use a save file from others but the pocket upgrade has been sold. Even though I set the flags to 0 but I can’t buy them by miles again. Is there any way to fix it?

I know this is 2 years late, but for anyone having this same issue:

Under 'received items', uncheck the Pocket Guides. They will then be available for purchase normally.

Editing the player inventory using flags in NHSE is still bugged. Items do not stack and villagers will tell the player their inventory is full, tools also cannot be registered if they are past the first 20 slots. The edited slots are usable but still bugged.
