### ISSUE TITLE
When I try to access the save, I get an error message, please help?

### ISSUE THREAD

**Issue by NathanBork** [kwsch/NHSE#450]
I downloaded the save editor without issue, and JKSV without any problems. I made my backup and now I am trying to edit my save. The issue is that whenever I try to open the main.dat on the save editor, I get an error message saying "InvalidArgument=Value of '102' is not valid for 'Selectedindex'. Parameter name: Selectedindex". I don't understand what this means, and I would appreciate a guiding hand. Thank you in advance!

**Comment by kwsch** [comment]
Gotta be more detailed than that.

The program provides a stacktrace; oftentimes you can hit continue and ignore any errors, too.

**Comment by NathanBork** [comment]
I do apologize, but I do not know what a stacktrace is. There is no option to continue. Just "okay" to make the error message go away. I go on the switch to make the backup save data using JKSV, remove the SD card, put it in my computer, then I open the save editor and drag the main.dat directly from the SD card to the save editor. I then get the error message, and I cannot proceed beyond that. Again, I apologize that I can't give more details.

**Comment by kwsch** [comment]
Probably some corruption?

Please send your save file (here or on Discord) so that someone can debug why it's exhibiting the error.

**Comment by NathanBork** [comment]
Alright. Where might I send the file? I'm admittedly not used to the site, and made this profile with the intention of getting help with my issue since I could find no one who seemed to encounter something similar. I figured asking the people that made the application was the best course of action. Thank you for taking the time to help. Apologies for the late response, it just happened to be late yesterday, and I have to head off once more since it is late now.

**Comment by klutch5398** [comment]
If you have Discord, you can join here:

 https://discord.gg/tDMvSRv
 
 Go to the #general-nhse-acnh channel and post your save file there if you feel comfortable, but mention who you are and this thread if anything.

**Comment by NathanBork** [comment]
Set and done, thank you!

**Comment by 19992077** [comment]
I have the same issue, did you find a fix?
