### ISSUE TITLE
reaction and turnips

### ISSUE THREAD

**Issue by littlebigworld82** [kwsch/NHSE#451]
reaction feelin it doesnt show up in game.
and I setup turnips prices, but it dont show up te correct price
someone help me with that?

**Comment by kwsch** [comment]
You'll need to export your save file from the current day so that a weekly advancement doesn't reset the prices.

Be sure you are using the latest version of the program.

**Comment by littlebigworld82** [comment]
oh ok, thank you
what about the new reactions? it does work with all except 1 reaction, feelin it

**Comment by kwsch** [comment]
FeelinIt is there.

https://github.com/kwsch/NHSE/blob/339bb4f7c88ba830732a4b0bd6389473c0df259c/NHSE.Core/Structures/Misc/Reaction.cs#L84

**Comment by littlebigworld82** [comment]
Yes. But don't show up ingame 
I do turned it on. But not showing
