### ISSUE TITLE
Ease of use request

### ISSUE THREAD

**Issue by fuhsdrmcaptin05** [kwsch/NHSE#454]
I think it would help if you could expand the map editing screen to either make the squares larger or make the viewable area cover more of the map. I'm not sure if there are other parts of nhse that would be affected by this and would make it so you cant make more area viewable. I also think it would be helpful if you could use the scroll wheel on your mouse to navigate up and down within the map screen.

**Comment by kwsch** [comment]
You already can click-drag to move around the map.

NHSE has to be flexible enough to support different screen resolutions. It's not doing 3D rendering at all, so if someone wanted a custom renderer they'd have to make it themselves and add it via a Pull Request.

Duplicate with - https://github.com/kwsch/NHSE/issues/308
