### ISSUE TITLE
Show patterns in Map Field Editor

### ISSUE THREAD

**Issue by JKDos** [kwsch/NHSE#457]
Patterns aren't currently showing in the map field editor.

I've imported acres from a new town and this left patterns in places they shouldn't be.

**Comment by kwsch** [comment]
Patterns choices per tile are stored separately from terrain.

The GUI already allows you to import & export the pattern choices: 
https://github.com/kwsch/NHSE/blob/75c176c02818c3bf8e4e3c0ad198aaf97ac799d8/NHSE.WinForms/Subforms/Map/FieldItemEditor.cs#L957-L987

**Comment by JKDos** [comment]
Thanks. I missed that. Sorry for wasting your time.
