### ISSUE TITLE
Passport pictures

### ISSUE THREAD

**Issue by lynbutnot** [kwsch/NHSE#459]
Would you possibly consider adding an option to backup/load passport pictures? I deleted the default one (which is something I would normally avoid doing, I just like to keep it) thinking it was an option to restore it in the editor, and then today I found out that I couldn't, so I'm super bummed. If this could be looked into I would really really appreciate it.

**Comment by klutch5398** [comment]
This won't be implemented @lynbutnot 

Refer to https://github.com/kwsch/NHSE/issues/182

It can be a feature that would be abused.
