### ISSUE TITLE
Edit Villager's wear per occassion / Umbrella

### ISSUE THREAD

**Issue by strawpedro** [kwsch/NHSE#462]
**Is your feature request related to a problem? Please describe.**
Some of the villagers have mismatching active / rain / snow wear, but gifting them the items you intend for them to wear does not make them wear it in aforementioned occasions. So an option to edit what they wear during exercise / rain / snow would be fantastic

**Describe the solution you'd like**
An option similar to "Edit Wear" under villager tab to edit Villager's default outfits per case
the background details can be found here: https://docs.google.com/spreadsheets/d/1Hg9RM8t-wfJWBOhRyqQAbsQN-gv_qLLA2JalqNE-B2U/edit#gid=441855967 in the "Villagers' Default Tempcreate Outfits"

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by kwsch** [comment]
> Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Where is this data located in the structure?

**Comment by strawpedro** [comment]
> > Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
> 
> Where is this data located in the structure?

to quote the Answer in the FAQ tab of the sheet:

""In ItemParam, a lot of clothings have weird values
in the columns AITagBitRankA, AITagBitRankB, AITagBitRankC (all empty in this one), and AITagBitRankS.
These are bit fields, where each bit represents a different group of clothing,
this is a list of every group and every clothing that's in a group.""

**Comment by strawpedro** [comment]
edit: just asked the author of the sheet ,

it seems like only tops, RainWare, RainHat, and Umbrella are in NmlNpcParam, and the other wears are affected by AITagBitRankA-S, so probably it's easier to implement the rainware/hat and umbrellas

**Comment by kwsch** [comment]
Again, where is this data in the save file?

**Comment by strawpedro** [comment]
sorry for confusion, it seems like these parameters are controlled by the game rather than stored in the save file
