### ISSUE TITLE
Save file sizes appear to be incorrect v1.9.0

### ISSUE THREAD

**Issue by strawpedro** [kwsch/NHSE#463]
This error pops up when attempting to load a 1.9.0 save. It looks like 1.8.0 save is 10.8MB and 1.9.0 save is 10.9MB.

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/blob/fab60f95d9f2189bcfd4bcb2acd445e768a7b207/NHSE.Core/Hashing/FileHashRevision.cs#L450-L456

**Comment by strawpedro** [comment]
I am using the latest build, loading a 1.8.0 save doesn't prompt this error but with a 1.9.0 save it does
If I ignore the warning I can still get into the main menu and make changes but do not want to risk anything

**Comment by kwsch** [comment]
What are your file sizes, then?

**Comment by strawpedro** [comment]
my 1.8 save: 11,329,638 bytes
my 1.8 save: 11,475,382 bytes

**Comment by kwsch** [comment]
Each file is compared individually; total sizes are not used.

**Comment by strawpedro** [comment]
ok after comparing 2 saves i found 2 files that have different sizes:
1. Main.dat (**1.8:** 8,690,736 bytes; **1.9:** 8,836,448 bytes)
2. Villager0/Personal.dat (**1.8:** 409,920 bytes; **1.9:** 409,952 bytes)

**Comment by kwsch** [comment]
Thanks; I wasn't getting the popup, but I found some other areas that needed updating.

Hopefully everything works fine now :)

**Comment by strawpedro** [comment]
Thanks for the update! I am still getting the error msg upon loading the save, but i am able to verify the hashes after skipping this error.

**Comment by kwsch** [comment]
Only thing I could guess is that you didn't save in-game on the latest patch, and instead immediately quit after it migrated to the latest patch. That might result in having some files on `1.9.0`, and the other files still being on `1.8.0`.

Hopefully this behavior resolves in future save exports :D

**Comment by strawpedro** [comment]
i was able to make changes so hopefully this is just a false alarm :) I did save on the latest patch tho, so not sure what is causing the size discrepancy...
