### ISSUE TITLE
Mailbox Gone

### ISSUE THREAD

**Issue by tasteeglue** [kwsch/NHSE#465]
Hello there! I am currently facing a dilemma in which my mailbox has disappeared. It seems to have occurred when I was changing the location of my house and deleted my old mailbox. I am not sure if this could be fixed in any way but thought to ask just in case. Any help would be greatly appreciated, thank you.

**Comment by berichan** [comment]
Just add a new mailbox to your inventory and place that. This isn't an issue with NHSE.

**Comment by paristokyo36** [comment]
if im being completely honest this is an issue with nhse the mailbox shouldnt count as a field item. had there been a warning saying youd lose your mailbox when clearing all items it wouldnt be an issue. youre beings so rude and dismissive without giving any actual help. ive looked in items and didnt find a mailbox . the op isnt the only one having this issue. so if you werent going to help why did you comment in the first place. no need to be an ass. help or be quiet

**Comment by berichan** [comment]
> if im being completely honest this is an issue with nhse

Not an issue with NHSE, the program simply fetches item types as they are in-game. 

> ive looked in items and didnt find a mailbox

Mailboxes are present, along with every other item in the game.
![devenv_2022-04-12_01-52-32](https://user-images.githubusercontent.com/66521620/162856964-a7c60a24-f444-4a38-ab9c-cfeb000ec18a.png) 
![NHSE_2022-04-12_01-53-23](https://user-images.githubusercontent.com/66521620/162856981-76e64a9c-6e27-4290-8743-710b156fc92f.png)
