### ISSUE TITLE
Can't load any save files resulting in crash with 2 errors

### ISSUE THREAD

**Issue by 19992077** [kwsch/NHSE#469]
I can't seem to load any save files. I did import them (and re-import them) with JKSV and tried transfering using FTP and USB.

When loading the `main.dat` file from my save, I get a prompt saying "Save files sizes appear to be incorrect. Continue?" 

- Clicking on "No" gives me an error with this text

```
Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
```

- Clicking on "Yes" gives me an error with this text

```
InvalidArgument=Value of '52' is not valid for 'SelectedIndex', Parameter name: Selected Index
```

[Link to download my save file for reference (Google Drive)](https://drive.google.com/file/d/1j41oP2xPouIFGu5QKkaNqYbNDstJky3W/view?usp=sharing)

Also, if that helps. I can load everything properly using ACNH Mobile Spawner (which is based on NHSE)

**Comment by kwsch** [comment]
Program is working as intended. Your dumps are bad.

For the v1.9.0 saves, `main` is supposed to be 0x86d560 bytes, not 0x007ed560. Other programs may not crash immediately with your dumped data (NHSE presents more data within the main GUI than mobile spawner), but they will crash as your data is not a valid save file.
