### ISSUE TITLE
Item count and durability doesn't work properly

### ISSUE THREAD

**Issue by frac3r** [kwsch/NHSE#470]
Hi, when i put an item in my world, the count of the item is bugged, even if i put 30 for example, it gives me just 1 item, and even if i put the durability to an enormous number it breaks like after 2 uses. When i reload the save that i played after the edit the count of items and the durability is the same that i put in when i edited the first time, but in game it still count it as 1 and the durability is really low.
Could you fix that please? Or is it my fault, maybe i do something wrong...

sorry for my bad english :(

**Comment by berichan** [comment]
This isn't a bug, counts start from 0, consider [reading the instructions](https://github.com/kwsch/NHSE/wiki/Item-Editing).
