### ISSUE TITLE
Mailbox Gone

### ISSUE THREAD

**Issue by Sentry108** [kwsch/NHSE#476]
I know this has been brought up before, however, did not realize I deleted the mailbox from my Player 1 home. I do not have a back up dump as I didn't think that something like this was possible so there isn't a back up recovery. Someone mentioned adding it to your inventory, however, I do not see that as being an option. Please advise.

**Comment by kwsch** [comment]
You didn't look hard enough for adding any mailbox.

**Comment by Sentry108** [comment]
Yes I did. if you can tell me which item name it is, mailbox, player 1, mail box, player doesn't pull anything

**Comment by Sentry108** [comment]
I'm obviously not the only one having issues with this and there hasn't been an actual real answer from what I've found looking at other cases.
