### ISSUE TITLE
Mailbox

### ISSUE THREAD

**Issue by Sentry108** [kwsch/NHSE#477]
I'm obviously not the only one having issues with this and there hasn't been an actual real answer from what I've found looking at other cases. The mailbox is gone, there isn't a way that I can tell adding the mailbox back in, there is no dump file that has been backed up because I wasn't aware, as it sounds like many others, that the mailbox would go away when removing all field items. 

I have searched for a way of getting this back, went through the items, tried searching with "mail" nothing at all, "mailbox" nothing at all, "player" nothing at all. There has not been a real answer to anyone having this issue other than "You're not looking hard enough" or "just add it back to your inventory" 

Please advise where this function is or what the item is specifically called to add it back. I know I'm not the only one frustrated at the lack of real answers or help on this issue. Please give a real answer on how to get this back. Thank you very much.

**Comment by berichan** [comment]
#465 #476

This is spam, no one besides you is currently having this issue. Refrain from creating multiple GitHub issues asking to be spoonfed, the issue you are having is unrelated to the functionality of NHSE. 
If you are unable to use basic search functionality, consider working on this before using the application.
