### ISSUE TITLE
Well

### ISSUE THREAD

**Issue by Sentry108** [kwsch/NHSE#478]
Go ahead and mark it as spam, but there isn't any reason to be rude to someone or people asking for help on the functionality of the program. We all appreciate what you do on making this editing software available, but something that is supposedly a "basic function" when I'm not the only one according to the "closed" issues if you look at them, that are having an issue isn't asking to be "spoon fed", I've spent hours looking for where the mailbox is to add it and I've searched all over here looking for it. It's not that hard to be nice to someone who is having an issue. There hasn't been any actual answer, none. Zip. I looked through them. But whatever.

**Comment by Lusamine** [comment]
Mailboxes are not only named "mailbox". They have extra descriptors for color and style.  Look up the name of a mailbox and search for that.
