### ISSUE TITLE
Passport Image Edit

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#48]
**Is your feature request related to a problem? Please describe.**
Not really, i just want to change my save file passport image.

**Describe the solution you'd like**
There should be a button like "Passport" that opens a new tab and you can select if you want to change your passport image.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
I don't have any alternatives

**Additional context**
Else if you don't like the idea of the button, can add a function to right click the passport image on NHSE and you can change the icon alongisde saving the image
*(Would open a new tab to choose the image file to upload as passport image like the file-picker for save file)*
![Screenshot (2057)](https://user-images.githubusercontent.com/55494819/78461546-5af99980-76ca-11ea-8894-7c077f50ea89.png)

**Comment by MirayXS** [comment]
I'am sorry if you don't understand something, am not english

**Comment by kwsch** [comment]
The passport image is likely stored in profile.dat; the currently displayed image is the image from personal.dat.

profile.dat is not documented.
