### ISSUE TITLE
Setting for Left-Click to Set

### ISSUE THREAD

**Issue by JandJ8493** [kwsch/NHSE#480]
I have been using NHSE for a while now but I really want a setting to Left-Click to Set items instead of Right Clicking than moving the mouse down and clicking set. I think this could be a huge time-saver if this was possible.
It can also really help with the terrain editor and edit field-items tool.

**Comment by klutch5398** [comment]
This is already a setting. Just hold `Shift` as you Left Click. If you read the Wiki you would know this or if you watched the NHSE Tutorial for Noobs by me. Please make sure to read the wiki in its entirety or join PKHeX discord if you have additional questions. Use the #general-nhse-acnh channel. Good day!
