### ISSUE TITLE
Export/Import Flags to text or csv

### ISSUE THREAD

**Issue by Hassiopeia** [kwsch/NHSE#481]
**Describe the solution you'd like**
I would like to be able to dump/export Player Flags to text or csv in order to better search and sort for the flags I'd like to enable/disable. Then import the changes back using NHSE. It would be helpful to search for all Flags with "Announce" in the title to more easily identify the flag I would like to enable.

**Describe alternatives you've considered**
Scrolling slowly through the entire list within the NHSE window

**Comment by kwsch** [comment]
The list of event flags is easily browsable in the source code, along with the japanese debug strings as comments.

https://github.com/kwsch/NHSE/blob/7fe8bcb53ec3842ac7c663ded3c819ddc6f924f6/NHSE.Core/Structures/Records/EventFlagPlayer.cs#L23-L1118

I don't see why it's necessary to have CSV import/export when you can open up the source code page in parallel with the editor GUI. Moving flags between players is already possible with dump/load.

**Comment by Hassiopeia** [comment]
Thank you, I did not know that!

I did just try to dump/load flags from one player to another and it didn't update the player for me. It's likely user error; I'll keep trying.
