### ISSUE TITLE
NHSE Not Working on 1.10.0 Saves

### ISSUE THREAD

**Issue by TheLordLucyfer** [kwsch/NHSE#482]
A constant "unknown revision" error keeps popping up when attempting to edit my save. All of my files are up to date, is there an issue with NHSE and 1.10.0 saves? Please get this working ASAP, this is a big issue.

**Comment by SciresM** [comment]
1.10.0 came out a couple of hours ago. Updating the program with support for new save file formats requires looking at the update to see what's changed, which takes time.

The program will likely be updated soon, but there will always be a small time gap between an update releasing and support being added. 

This is an unavoidable consequence; please keep in mind, too, that NHSE is maintained/updated by volunteer developers.

**Comment by TheLordLucyfer** [comment]
Oh my lord that's my bad, it's been about 3 weeks since I last played and thought 1.10.0 was the version that came out for the Sanrio stuff! I'm so sorry about that!
