### ISSUE TITLE
Enhanced Acre dump/import function

### ISSUE THREAD

**Issue by Charles2048** [kwsch/NHSE#483]
**Is your feature request related to a problem? Please describe.**

The existing Arce Dump/Import only allows grid operation (6x7 area), and in daily use, I often encounter boundary problems (many islands are not built according to the grid). Therefore, it will appear during the Dump/Import process. The case where Arce does not match the map.

**A clear and concise description of what you want to happen.**

I hope that Dump/Import Arce can add freely delineated positions and sizes to Dump/Import based on the original grid Dump/Import, so that users can freely select the range, and it is convenient for users to splice different forms of Arce.

**Describe alternatives you've considered**

If this is a hassle, I'd like to know how to compile it myself through Visual Studio.

**Comment by berichan** [comment]
I'm closing this as stale. As far as I'm aware, the placement for these are fixed without running into issue related to clipping through the floor and the floor behaving like water. Feel free to post here if there are any further developments and I'll reopen
