### ISSUE TITLE
Unable to save files to their original location

### ISSUE THREAD

**Issue by SysAdmln** [kwsch/NHSE#490]
Index was out of range. Must be non-negative and less than
the size of the collection.
Parameter name: index

after they moved to my island from another island

[savefile.zip](https://github.com/kwsch/NHSE/files/6789013/savefile.zip)

**Comment by kwsch** [comment]
Not seeing any errors on the latest commit.

If you still experience errors, please list the steps to replicate whatever error you are encountering.

**Comment by SysAdmln** [comment]
reproduced this error two more times.
You can switch from one console to another console by any player. after that you cannot change the island.

**Comment by kwsch** [comment]
> please list the steps to replicate

**Comment by MarleyLua** [comment]
i'm getting this error now:c it was working perfectly before
