### ISSUE TITLE
System.IndexOutOfRangeException when open an updated save file v 1.11.0

### ISSUE THREAD

**Issue by xdinko** [kwsch/NHSE#493]
When i try to edit map on a save file update to v1.11.0 nhse go in error. 

![image](https://user-images.githubusercontent.com/4558627/127448342-10ead4d1-8daf-429e-8105-2b5f68cf12d5.png)

**Comment by kwsch** [comment]
Was fixed right before you reported it :)
https://github.com/kwsch/NHSE/commit/42a16ea35e8f8a8f33f981cbff5702dfa9083757

**Comment by xdinko** [comment]
<3
