### ISSUE TITLE
"save file damaged" error every single time?

### ISSUE THREAD

**Issue by rcascott97** [kwsch/NHSE#494]
Hi!  I'm new to NHSE, but I'm unable to launch ANY saves that have been altered via NHSE.  I backed up my save files using JKSV, and tested that multiple saves restored successfully with this program, as long as they hadn't been updated using NHSE.  Then I tried to alter the save; at first I tried multiple changes, but most recently I just tried changing the amount of money I own.

No matter what the changes are, I am unable to load the altered save.  Every time I try, it says that the save file is damaged.

Any ideas or help would be SO appreciated!  Thanks!

**Comment by kwsch** [comment]
Probably not restoring your modified data correctly.

Usual suspects are FTP options not being set to binary, or restoring files/data that isn't in the original save file (like `*.bak` or text files).

Nobody else reporting this issue after the patch implies it is something on your end, not the program.

**Comment by rcascott97** [comment]
thank you so much for the response!  I don't believe I've been restoring data that's not in the original save, but I'm not sure how to set the FTP files to binary... do you have any advice or other articles I could reference to figure this out?

**Comment by rcascott97** [comment]
Update: I solved the issue!
Instead of physically moving the sd card from the switch to the pc, I was using the function through Hekate that is supposed to allow you to access the sd without removing it every time.  Through process of elimination, I instead moved over the sd card the old fashioned way, and it worked!
Thanks for your time, hopefully this helps someone else in this position.
