### ISSUE TITLE
Feature Request: A Way to Turn on All Activatable Furniture (i.e. lamps, lights, fans) 

### ISSUE THREAD

**Issue by raikxou** [kwsch/NHSE#495]
I noticed when messing with the editor that there isn't a clear way to turn on and off activatable items such as lamps, etc. A clear cut option would be nice for items with that feature as well as a turn on and off all lamps/activatables in the map + the acre.

**Comment by kwsch** [comment]
Sure editors can do anything, but why can't you just toggle their active state in-game?

Determining if an item tile can be turned "on" would require someone to note which item IDs can be set as active in-game, and collate it into something the program can understand.

```c
struct GSaveMainField {                            /* 0xdaa2c big, align 4 */
  s_5b202da4                        ItemLayer0;                             // @0x0 size 0x54000, align 4
  s_5b202da4                        ItemLayer1;                             // @0x54000 size 0x54000, align 4
  s_8bac980d                        ItemSwitch0;                            // @0xa8000 size 0x1500, align 4
  s_8bac980d                        ItemSwitch1;                            // @0xa9500 size 0x1500, align 4
```
The item switching layers are after the item tile layers. They're stored separate from the item tiles.

NHSE does have unused logic to get the IsActive state of a given tile-layer. I don't think adding that complexity is worth the headache...

**Comment by raikxou** [comment]
I understand, I ask mostly because a lot of mapping in people's saves sometimes has items placed in spots you can't naturally reach without terraforming to the location. The headache is understandable though after your explanation, thanks for your quick response!

**Comment by Ixaruz** [comment]
a messy (but working solution) would be to just fill ItemSwitch0 and ItemSwitch1 with a buncho 0xFF, innit?

**Comment by kwsch** [comment]
> a messy (but working solution) would be to just fill ItemSwitch0 and ItemSwitch1 with a buncho 0xFF, innit?

Yes, but having "active" flags when the tile cannot be active is easily indicative of cheating.

I think the best solution is to have another right-click option (View/Set/Delete) to toggle the "active" flag.
