### ISSUE TITLE
Changing island and player name doesn't go very well.

### ISSUE THREAD

**Issue by etherela** [kwsch/NHSE#5]
I changed my name and my island name on the save editor, but on the Passport it didn't changed at all.
Went to talk to Tom Nook and he told me "Oh, so nice that you travelled all that way from another island to visit our island".
Tried to use the Nook Stop and it said "only ******* residents can use that device".
I edited the save file again putting the old island name, but still having the new player name, Tom Nook talked to me like I was a resident of the island, but not THE principal player and I went to a villager house and she said "Oh! You're new here, right? Let me introduce myself" like if I had created another player.
Then I edited the save file again putting the old player name and now everyone recognizes me and I am the principal player again.

I am mainly posting this issue here 'cause I don't know if another people has experienced the same, so it's something you should give a look at :)
**_Anyways, thanks a lot for your effort and keep up the good work!_**

**Comment by kwsch** [comment]
Yep, #3, #4 

Needs more research on what has to be changed.
