### ISSUE TITLE
Add item images, prices, etc.

### ISSUE THREAD

**Issue by dodocodes** [kwsch/NHSE#50]
I'm working on populating a database with every item, an image of the item, a description, prices, etc. It would be amazing if NHSE could pull this item information, including images, etc., to display when picking items for the inventory.

**Comment by kwsch** [comment]
Requires research & categorized dumped files, none of which I'm interested in doing.

**Comment by dodocodes** [comment]
I am fully able to do the research myself, just need to be pointed in the right direction on where to look. If you know anybody that can help point me in the right direction, that'd be great. I'm working on a pull request now for NHSE to import displacement maps for terrain generation...
