### ISSUE TITLE
Turkey day DIY recipes not spawning when I try to generate them in inventory

### ISSUE THREAD

**Issue by hellakitty** [kwsch/NHSE#500]
Title. I use my hacked switch to move DIY recipes over to my main switch. The other DIY recipes spawn just fine. For some reason all the Turkey Day DIY recipe cards will not spawn in my inventory. A fix would be greatly appreciated! Thank you!

**Comment by kwsch** [comment]
Are you on the latest game patch (`1.11.1`)?

**Comment by hellakitty** [comment]
Thanks for reading this so quickly! Yes, Animal crossing is updated to 1.11.1, and I'm also using the latest version of NHSE.

**Comment by berichan** [comment]
> will not spawn in my inventory.

Are you live injecting or saving & restoring your save? This DIY recipe is one that will disappear if you fly with it.

**Comment by hellakitty** [comment]
> > will not spawn in my inventory.
> 
> Are you live injecting or saving & restoring your save? This DIY recipe is one that will disappear if you fly with it.

I am saving and restoring. Its just straight up not appearing in my inventory at all. I'm checking as soon as I load in the game It's worth noting that every other DIY recipe, holidays included, works fine.

**Comment by berichan** [comment]
Confirming that these DIY recipes won't persist between play sessions. This is intended behaviour as of 1.11.0. A full list of affected DIY recipes are here: https://github.com/berichan/ACNHMobileSpawner/wiki/List-of-unflyable-DIY-recipes

> other DIY recipe, holidays included, works fine.

These aren't affected.

**Comment by hellakitty** [comment]
> Confirming that these DIY recipes won't persist between play sessions. This is intended behaviour as of 1.11.0. A full list of affected DIY recipes are here: https://github.com/berichan/ACNHMobileSpawner/wiki/List-of-unflyable-DIY-recipes
> 
> > other DIY recipe, holidays included, works fine.
> 
> These aren't affected.

Thanks for the clarification. So if I time travel to Turkey Day and try to generate the DIY recipes on turkey day will they generate?

**Comment by kwsch** [comment]
You can use injection via sys-botbase/usb-botbase to insert the item directly to your inventory, or try dropping them on the map.

Loading the game from the main menu or flying will remove any of the DIYs in your inventory.
