### ISSUE TITLE
Index Out Of Range

### ISSUE THREAD

**Issue by JKDos** [kwsch/NHSE#503]
I tried to get help from Discord, but they were stumped.

I started a new island in New Horizons, and when I try to save changes in NHSE, I get this error. Important to note, I will get this error even if I change nothing. I have game version 1.11.1 and NHSE version Build no. 4038

![image](https://user-images.githubusercontent.com/17679930/131221481-0da64e43-c405-42d4-8df7-fccc3cd09e45.png)

If I edit my old saves from my old island, I don't get this error.

**Comment by berichan** [comment]
Are your old saves in the same location as this one? It seems like a filesystem access issue, are you transferring them off your sd card before editing? No OneDrive or other cloud-based folder?

You can zip and send us the save folder and we can check if it actually is a savefile reading issue.

**Comment by JKDos** [comment]
> Are your old saves in the same location as this one? It seems like a filesystem access issue, are you transferring them off your sd card before editing? No OneDrive or other cloud-based folder?
>
> You can zip and send us the save folder and we can check if it actually is a savefile reading issue.

Yes. Someone on discord thought it was a read/write issue too. No other saves in the same location have this problem. I keep the saves on my second drive (D:\)  where I keep my Steam Libary or other games. Just for the sake of trying, I moved the save to the C:\users\<user>\Documents and that didn't help either.

I'll get you the file if I can remember after I get off work today.

**Comment by JKDos** [comment]
> You can zip and send us the save folder and we can check if it actually is a savefile reading issue.

Here is the save.
[save-2-082721.zip](https://github.com/kwsch/NHSE/files/7079568/save-2-082721.zip)

**Comment by kwsch** [comment]
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at NHSE.Core.EncryptedFilePair.Hash() in C:\Users\Kurt\Documents\GitHub\NHSE\NHSE.Core\Save\Meta\EncryptedFilePair.cs:line 55
   at NHSE.Core.HorizonSave.Save(UInt32 seed) in C:\Users\Kurt\Documents\GitHub\NHSE\NHSE.Core\Save\Meta\HorizonSave.cs:line 33
   at NHSE.WinForms.Editor.Menu_Save_Click(Object sender, EventArgs e) in C:\Users\Kurt\Documents\GitHub\NHSE\NHSE.WinForms\Editor.cs:line 70
```

![image](https://user-images.githubusercontent.com/6393368/131420855-b76ba4a0-87d3-4c91-ba00-8e49dc3245ce.png)

![image](https://user-images.githubusercontent.com/6393368/131420927-32b32f48-f7bf-4e56-a93a-33efa2510e3c.png)

Your `profile.dat` file appears to be invalid;
![image](https://user-images.githubusercontent.com/6393368/131421197-45950626-16b3-453e-bc6d-69b55c1ab3d2.png)

Try replacing the `FF FF` with `15 00` so that the SaveRevision correctly reads `21` in NHSE, to match the other file headers:
![image](https://user-images.githubusercontent.com/6393368/131421247-534a1606-0291-420d-b068-010e7f1b1ef1.png)

**Comment by JKDos** [comment]
>  I'm not sure how you've managed to get your header data to misbehave

After speaking with someone again on Discord, I think we've determined this can happen because I used the Resident Move feature Nintendo added to ACNH, which lets you move any non island rep from one save to another. When starting my new island, I had moved one of my characters to my other Switch so I'd start the game which some things already unlocked.

**Comment by JKDos** [comment]
> Try replacing the two instances of `FF FF` with `15 00` in a hex editor

No more error after that. I'm good to go. Thanks for your help.

**Comment by kwsch** [comment]
Thanks for the update!

I don't think I want to have any handling for this in the program, as you're the first to report it after so long. Maybe if others have the issue, I can make the program ignore that FF FF :)

**Comment by dennyrgood** [comment]
I had this same issue, and my main villager was moved from another island ... changing the FF FF to 15 00 at offset 0E and 0F fixed the index save error.

Thank you!!!
Denny
