### ISSUE TITLE
Inject issue: FailValidate

### ISSUE THREAD

**Issue by DeadSix27** [kwsch/NHSE#505]
After removing Tesla/OvlLoader/Holding L to start the game, i still can't get the injection to work...

**Comment by berichan** [comment]
Is the offset correct for your update version and the amount of players on your save? https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection

**Comment by DeadSix27** [comment]
I tried AED22840, I have 1 player (just me) and it didn't work.

**Comment by kwsch** [comment]
Then you need to troubleshoot it on your end using the steps on the wiki.

The offsets are finem your setup likely is not.
