### ISSUE TITLE
How do I use the batch editor?

### ISSUE THREAD

**Issue by Santiav90** [kwsch/NHSE#506]
First of all, I'd like to apologise as this is probably not the correct way to ask a question but I couldn't find an answer in the wiki.

How can I use the batch editor? I placed a lot of items and forgot to make them be dropped so I tried the batch editor but couldn't get it to work.

I tried ".IsFieldItem=IsDropped" or ".IsFieldItem=Flag0=20" but didn't work either. Is there a way to make that happen?

**Comment by kwsch** [comment]
It's numerical/values only

Use filters to narrow down the list, then afterwards the modification commands.

**Comment by Santiav90** [comment]
> It's numerical/values only
> 
> Use filters to narrow down the list, then afterwards the modification commands.

Thanks for your answer kwsch. Could you give me an example of how can I narrow the list and input the modification commands? I'm not very good at programming yet and it's a bit confusing to me.

**Comment by kwsch** [comment]
[Refer to the commit message that added the feature](https://github.com/kwsch/NHSE/search?q=batch+editor&type=commits):

https://github.com/kwsch/NHSE/commit/0798aa5a97f2b2e95f95a832836bfd6df1a535e2


Example to unbury all items:
```
=IsBuried=True
.IsBuried=False
.IsDropped=True
```

Each command is a logical step. First we only want to process buried items. Then, we want to make those items not buried. Then, flag them as dropped.

You're wanting to do something that takes 1 filter line, and 1 command line. I won't write the answer as it should now be obvious how to enter it :P
