### ISSUE TITLE
Moving Out checkbox, instantly gone.. 

### ISSUE THREAD

**Issue by ethanccss** [kwsch/NHSE#509]
I'm trying to have the villager boxed up. But when checking "moving out" they are instantly gone when loading the save. This is with the flag 024 "forcedmoving" set to 0 as it should be, but it's acting as if it's set to 1. Thus I can't talk to villagers before they move to invite them to other islands.

**Comment by berichan** [comment]
Are you saving and restoring on the same in-game day?

**Comment by ethanccss** [comment]
Yes. Should I move a day ahead or back?

**Comment by berichan** [comment]
If your edits and restore happen on the same day then it should put them in boxes. Could upload the save and send a link here?

**Comment by ethanccss** [comment]
Oh.. it was the same day. Yea sure I'll upload.

**Comment by ethanccss** [comment]
https://drive.google.com/file/d/1yObAOR8sRPhC4IJvK9Nr4pYVMKraPJ0U/view?usp=sharing

Ive had no problem editing saves for months, this island is not my main, just my hacky item and villager island I use to transfer stuff. I cannot get Pekoe to pack her stuff, she just disappears if you check "moving out". Thank you very much.

**Comment by berichan** [comment]
I changed my switch date to a few minutes after your save stamp (2021-09-08 22:37:14) and loaded it without any modifications; Pekoe was in boxes. Can you try doing the same and see if the issue persists for you?
![obs64_2021-10-04_13-07-26](https://user-images.githubusercontent.com/66521620/135848856-9f2f347a-b11a-4ac3-8266-d1f6f9ecbdcd.png)

**Comment by ethanccss** [comment]
It worked! So changing the time to something like 5 minutes ahead seems to be required now? Thank you so much for your help.

**Comment by berichan** [comment]
You need to be on the same day and not have travelled back in time.
