### ISSUE TITLE
Inject doesn't work after latest commit - 1db185151d17d73a464e23a2193116e7510cc9e9

### ISSUE THREAD

**Issue by codemartin** [kwsch/NHSE#52]
when using inject feature, I can connect and I get the offset but when hitting read, I get "fail"
![failerror](https://user-images.githubusercontent.com/2740089/78466806-8c269980-76cb-11ea-85af-ef5650348ca2.PNG)

**Comment by kwsch** [comment]
Can you disable validation (new checkbox) and try again?

**Comment by kwsch** [comment]
Works for others with the new bypass. Closing.
