### ISSUE TITLE
Add support for new 2.0 structures

### ISSUE THREAD

**Issue by xmrmeow** [kwsch/NHSE#524]
With the 2.0 update, a plaza area was added to Harvey's Island, and on it a number of Campers.

I was wondering if these Campers could be added to your island in some fashion like as a building similar to how Harvey's Studio can be added to your island even though it doesn't normally belong there.

**Comment by kwsch** [comment]
From the issue template:

Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

The community has to document those shapes prior to them being able to be implemented in a program.
