### ISSUE TITLE
Setting the flag for having the 30 inventory slots leaves the extra slots unusable. 

### ISSUE THREAD

**Issue by CrazyBlues** [kwsch/NHSE#53]
I made a new character in my town, who I gave all recipes to, as well as filling his catalog. When I tried to purchase the inventory upgrade, it wasn't available in the Nook Stop (the character does have Nook Miles+). After noticing that, I went into the save editor again and set the flags for the 30 and 40 slot upgrades. At the same time, I also added the tool wheel, the hairstyle packs and the hair colors pack. 

When I checked, I saw that the 40 slots were visible in the inventory, but only the original 20 were usable. I went back in and turned off the 40 slot upgrade, but left the 30 slot one. That time, the 30 slots were visible, but still only the original 20 were usable. 

I'm not sure why this is happening, but I will attach the folder with the villager that's giving me problems. I'd attach the whole save, but it's too big to upload. 

[Villager2.zip](https://github.com/kwsch/NHSE/files/4433219/Villager2.zip)

for reference.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Event Flags are exposed for editing, but keep in mind that they are just the game's event flags -- the game might check other values when toggling / restricting features. Without knowing how the game behaves (research), nothing can be implemented in the program.
