### ISSUE TITLE
save corruption issue with diys and item catalogue

### ISSUE THREAD

**Issue by pixelstormy** [kwsch/NHSE#531]
hi idk if its bc i'm an absolute noob or not but when i tried to give myself a full item catalogue and all diys learned yesterday it corrupted my save file. i'd backed it up so its fine in the end but i figured i should report this anyway (sorry if this wasn't how i should go about this i've never done this before)

**Comment by kwsch** [comment]
Working fine for everyone else; you're likely restoring the save data incorrectly.
