### ISSUE TITLE
Player House Editor Broken

### ISSUE THREAD

**Issue by Draeon143** [kwsch/NHSE#537]
**Is your feature request related to a problem? Please describe.**
Editing player homes is broken, most likely due to data offsets being changed with the addition of new house styles and customization options from the 2.0 update

**Describe the solution you'd like**
Correct the offsets so I, and others, can import my old house into my new island

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
I have tried importing the entire house, and the individual floors, but the data offsets for the floors are probably affected by the new dlc house style data as well.

**Additional context**
Attempting to edit ANY player home results in ALL player homes breaking and becoming unusable or the causes the player who owns it to lose ownership of the house and enter it as if they were a guest, locking them out of storage and editing features.

**Comment by berichan** [comment]
Fixed in 2ed928e9612eefc52be529e4e522f175c2ffe33a
