### ISSUE TITLE
give reaction all?

### ISSUE THREAD

**Issue by poilkjno** [kwsch/NHSE#538]
**Is your feature request related to a problem? Please describe.**
I want to have all the reactions that include 2.0.1 updated ver. (like gymnastics achievement reaction, and happy home paradise), but when I click the give all the reaction and save and load the island, I don't have them.

**Describe the solution you'd like**
Could you make the reactions including new ones? like I describe above. 

**Additional context**
I even tried to edit the achievement pages that "109=Joinradiogymnastics" to 49, and do it one time for full achievement.
but no reactions were get.

I always appreciate for your work. thx.

**Comment by poilkjno** [comment]
nvm. I unlock it

**Comment by mbirth** [comment]
@poilkjno It would be nice if you could document how you've unlocked them.
