### ISSUE TITLE
How to Install it

### ISSUE THREAD

**Issue by KleinundGruen** [kwsch/NHSE#54]
Dear Reader,

I just dont know how to install the Saveditor is there a Manual for it ? 

I just found this Manual : 
   
1. Click the link and either clone or get a zip of the save editor the option is within a green button on     the right.

 2.After getting the folder download Visual Studio (I installed mine with default settings)

   3. Once you have it installed right click the NHSE-master folder and open it with VS. Once it's opened up look to the right for the "Solution Explorer" and click "NHSE.sln"

   4. Run the .sln by clicking the green triangle icon above (it's below where Analyze, Tools and Extensions are on the top most menu)

   5. After running the .sln you will see that the Solution Explorer changed, at this point I believe you  can just click on any of those (NHSE.core, NHSE.Injection, NHSE.Parsing etc) and run them to activate the Save Editor (green triangle button again).

   6.  Open up your Ryujinx and go to your New Horizon's save folder COPY it's contents and put all the contents in a new folder (this will be used for you test and edit) It is recommended that you always have a backup of your original save!

   7. Drag the new folder that contains your save into the application and from here you can start changing things within your game.

And when i try to debug the NHSE.sln File like in this Description is says it doesnt work

Thanks for reading i would be really thankfull for your helping

Greetings

**Comment by architdate** [comment]
Read the wiki (look at the home page specifically)
