### ISSUE TITLE
Give all reactions problem.

### ISSUE THREAD

**Issue by snailsimulator** [kwsch/NHSE#540]
Hey! I used the give all reactions function and no longer have access to my reactions? is there a way to remove them all to see if i can relearn them to fix this? couldn’t understand the reactions section of nhse

**Comment by berichan** [comment]
I am closing this as stale. A fresh save with these unlocked doesn't cause any issues, so I'm not sure why this happened. If this happens to anyone else reading this, please revert to a backup or if you find a way to solve this, the please provide further information and I'll reopen this.
