### ISSUE TITLE
New problem of player room.#20211120.8 Fix loading player house and room dumps

### ISSUE THREAD

**Issue by tallasd** [kwsch/NHSE#554]
it'so sad that still remain some problem.
the nhph and file is all new.
and .nhph is dumped by lastest NHSE.
<img width="516" alt="942faf6e5dfd1011bd4f43af13cf8b3" src="https://user-images.githubusercontent.com/17810762/142723742-544eeedf-9f06-47f2-9c65-a446bfc0d9be.png">

YOU CAN TRY IT
you can load the nhph it to the player,
and the error will appear
[loaderror.zip](https://github.com/kwsch/NHSE/files/7574415/loaderror.zip)

**Comment by tallasd** [comment]
all of these are  new player houses and rooms to the new format

**Comment by tallasd** [comment]
sorry older file!!!
my wrong!

**Comment by tallasd** [comment]
ok ！ my wrong !
i solve my problem!
tysm!
love u!
have a nice day!!!

**Comment by hp3721** [comment]
@tallasd Glad that you solved your problem. I went ahead and made sure downgrading player house formats works (#552) since that is an intended feature.
