### ISSUE TITLE
error code:2219-4301 two swtich can't use the same file.how can i change file in NHSE to obey this sitution !

### ISSUE THREAD

**Issue by tallasd** [kwsch/NHSE#555]
my another switch can't connect to the internet.
the error code is 2219-4301
how can i change file in nhse to solve this problem
how nintendo distinguish the unique game archive of acnh? can we have the chance to change that flag/mark to generate several different game archives from one game archive of acnh?
i think maybe it relate to player info?
Tysm!
love 
![be0fad2791fa429d67f90b32a7d3943](https://user-images.githubusercontent.com/17810762/142749661-767b0f85-6eb9-4a63-a5e0-23858b9754b0.jpg)
u!

**Comment by kwsch** [comment]
https://en-americas-support.nintendo.com/app/answers/detail/a_id/54289/~/error-code%3A-2219-4301

> If the error occurs in Animal Crossing: New Horizons after restoring your island backup data, make sure you are using the Nintendo Switch system that you restored the data on.
> If a resident has also moved to a new island on a different Nintendo Switch system, make sure that resident's player is using the Nintendo Switch system that they moved to.

**Comment by tallasd** [comment]
sorry i don't understand. 
all of my switch can't connect

**Comment by tallasd** [comment]
my Treasure island also can't connect

**Comment by kwsch** [comment]
Unrelated to NHSE.
