### ISSUE TITLE
Edit Villagers in DLC HHD

### ISSUE THREAD

**Issue by dudao2888** [kwsch/NHSE#559]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when i started the dlc and therea are so many villagers that I don't want [...]

**Describe the solution you'd like**
Option to choose the villagers in the DLC not only in the game base.

Thank You.

**Comment by berichan** [comment]
Please don't copy and paste this into multiple repos.

As I said before, all adoptable villagers are already injectable.

If you're talking about NPCs, these can't live on your island.
