### ISSUE TITLE
Move entire Town Centre

### ISSUE THREAD

**Issue by ratquaza** [kwsch/NHSE#56]
Currently, there is no way to move the entire Town Centre, only the Resident Services building. It'd be pretty neat to be able to move the entire Town Centre.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
