### ISSUE TITLE
wherearenHeader.dat missing?

### ISSUE THREAD

**Issue by Mango-Ray** [kwsch/NHSE#565]
Build 4409

NHSE could not find file 0/villager0/wherearenHeader.dat, and thus refuses load up the save. My save works just fine in-game though, is this file actually important?

**Comment by kwsch** [comment]
Related to: https://github.com/kwsch/NHSE/pull/564

The pull request will have to be revised to allow the non-presence of the wherearen (DLC) savedata.

Pull requests automatically generate builds, hence it replacing the latest downloadable zip.

**Comment by kwsch** [comment]
Please try the latest pipeline build, and let me know if it has resolved the issue :)

**Comment by Mango-Ray** [comment]
It loads up just fine now, great job.
