### ISSUE TITLE
Question about Load Villager 

### ISSUE THREAD

**Issue by keliling12** [kwsch/NHSE#566]
Hi, sorry for my bad english ..

If i do a load villager and save after that, then edit/load villager and save file .. can the villager have the same index like the villager replaced? Becase when i'm try , the villager on the map preview of game not on the same index (example replace 6th villager, but when load the edited save the replace one move to 1th villager).

Thanks

**Comment by berichan** [comment]
I'm closing this as stale. NHSE has raw value editing for the indexes, you can try playing with these values and see if it puts your villagers in the expected order
