### ISSUE TITLE
Program not responding after editing main.dat

### ISSUE THREAD

**Issue by KeisukexS** [kwsch/NHSE#567]
Hello i have a problem with NHSE, when i edit my save file the program stops working (not responding), i close the program and i retry to open the main.dat file but it says "failed to verify Encryptedint32 at offset". am i doing something wrong?

**Comment by kwsch** [comment]
Restore the backup and try again.

**Comment by KeisukexS** [comment]
i did that and now it says ssave data corrupted, the program fails at some point in the saving process but i do not know why.

**Comment by KeisukexS** [comment]
when i transfer the backup to my pc NHSE opens it, but when i click save it stops working and corrupts the save file
