### ISSUE TITLE
Please add A "In boxes" villager option

### ISSUE THREAD

**Issue by Newhorizionsuwu** [kwsch/NHSE#57]
Thank you so much for making such an amazing editor. I truly appreciate it and I know many others do as well! The previous Save editor had this option within the Villagers tab, and I believe It would be a good addition! Again Thank you!

**Comment by Newhorizionsuwu** [comment]
For further explanation An In Boxes Villager is a villager that is ready to move to another town, perfect for transferring villagers to friends towns and such!

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
