### ISSUE TITLE
Questions about Harv's island

### ISSUE THREAD

**Issue by amg-12** [kwsch/NHSE#573]
I understand that NHSE does not currently have support for Harv's island and that further research is needed.

However, do you have any insight as to whether the following things are possible in theory?

1. terraforming and placing items or buildings on Harv's island
2. taking amiibo characters from Harv's photo studio and placing them inside player homes
3. taking vendors from Harv's co-op plaza and placing them on the main island

**Comment by kwsch** [comment]
Unrelated to NHSE.

**Comment by amg-12** [comment]
Okay, sorry.
