### ISSUE TITLE
Plaza dirt vs brick

### ISSUE THREAD

**Issue by ohheplays** [kwsch/NHSE#574]
Hi! I was wondering if there is a way to change the plaza back to the dirt version from the beginning of the game? I'm able to change the building on the plaza, but cannot figure out a way to change the brick path back to the dirt from the tent version of the plaza. Thank you in advance!

**Comment by kwsch** [comment]
Probably an land flag value; not really related to NHSE.

**Comment by ohheplays** [comment]
but isnt the way to edit flags with NHSE? im sorry im new to this, and didnt know where else to ask.

**Comment by kwsch** [comment]
NHSE allows you to edit them yes, but nobody has taken the time to understand every single flag value for specific edits like you are requesting.

Figure it out yourself and document it for others, or wait for someone else to do it for you (potentially never).

**Comment by ohheplays** [comment]
adding here in case anyone else is trying to do this: 

I set 29 - EventPlazaBuilt to value 0 and the plaza turned back to the dirt
