### ISSUE TITLE
2.0.4 Save not loading 

### ISSUE THREAD

**Issue by 1davi** [kwsch/NHSE#576]
I've updated the game and I'm using the latest NHSE version, but it gives me this error message:

<img width="667" alt="Screen Shot 2021-12-16 at 15 56 59" src="https://user-images.githubusercontent.com/14959546/146432018-3ab202d3-a2fd-4339-b2de-8625ec7173d9.png">

**Comment by Aqua-Marie** [comment]
I'm having the same problem.

**Comment by berichan** [comment]
Unable to reproduce the issue. Ensure you're using the latest pipeline build instead of reporting issues with an outdated build: https://berichan.github.io/GetNHSE/

**Comment by Aqua-Marie** [comment]
> Unable to reproduce the issue. Ensure you're using the latest pipeline build instead of reporting issues with an outdated build: https://berichan.github.io/GetNHSE/

I had the newest version downloaded. Just to be sure I deleted and then completely redownloaded via the link you provided and I'm still getting the error message pictured above.

**Comment by jdroo** [comment]
Also having the same issue. checked the version twice, no change. 

https://i.imgur.com/oqm5hY5.png

**Comment by Lusamine** [comment]
Updated my game, freshly exported a save, and downloaded from the provided link.  Loaded without issue.
![image](https://user-images.githubusercontent.com/30205550/146461011-96f38d89-3565-4a79-a1bf-35a5c12a899e.png)

**Comment by jdroo** [comment]
That's strange, cause i've updated my game, made like 5 fresh exported saves, and it wont open at all, gives the same error every time.

**Comment by jdroo** [comment]
![explorer_XbZlQCDuZg](https://user-images.githubusercontent.com/13055804/146462113-4239a1aa-b492-4ceb-9946-418fde0182be.png)

Even checked if JKSE was updated

**Comment by jdroo** [comment]
![2021121617101300-57B4628D2267231D57E0FC1078C0596D](https://user-images.githubusercontent.com/13055804/146463387-8b80aae3-c100-4138-b49f-685cf825fa52.jpg)

on the latest update too.

**Comment by jdroo** [comment]
I'm taking the extreme route of uninstalling, and fully reinstalling acnh + updates and DLC, see if it fixes it. after this, if it still don't work, after updating everything... then I'd assume something else is wrong here.

**Comment by hp3721** [comment]
> I'm having the same problem.

Do you have the DLC?

**Comment by Aqua-Marie** [comment]
> > I'm having the same problem.
> 
> @Aqua-Marie Do you have the DLC?

Yeah, I have the DLC.

**Comment by 1davi** [comment]
I have the dlc too

**Comment by berichan** [comment]
I guess it could be dlc-related shenanigans, I'll check it with my dlc save in a min.

**Comment by jdroo** [comment]
@hp3721  I fully reinstalled, tried it without and with the DLC, still same error.

**Comment by castiiian** [comment]
i have the dlc and i have this same problem

**Comment by sosohangom** [comment]
Unknown revison!
FileHeaderInfo { Major = 524297, Minor = 524421,Unk1 = 2, HeaderRevison = 0, Unk2 = 2, SaveRevision = 26 }

animal crossing (+DLC) game ver.2.0.4
Same error after update!
NHSE latest update has been downloaded!
I want to use NHSE quickly

**Comment by berichan** [comment]
Please let me know if the issue persists on the latest build https://berichan.github.io/GetNHSE/

**Comment by jdroo** [comment]
all good now!

**Comment by Aqua-Marie** [comment]
Mine is working now too, thank you!
