### ISSUE TITLE
my edits to my save file do not appear within the game

### ISSUE THREAD

**Issue by skyl9r** [kwsch/NHSE#578]
i try increase the amount of bells in my wallet, save and load up my save in ryujinx and my bell count doesnt change. i tried to add a new villager to my island through nhse and i save and load of my save in ryujinx and there is no villager. i edit my inventory to add an item, save and load up my save in ryujinx and it doesnt appear in my inventory in game. am i doing something wrong??? im playing v2.0.4 acnh with all dlc and im using the latest version of nhse

**Comment by kwsch** [comment]
Export your save file correctly from NHSE and make sure your game's savedata is overwritten with the edited file from NHSE. Edits don't magically revert.

**Comment by skyl9r** [comment]
i double checked this and it is literally reverting for no reason i cannot put it simpler and thered be no reason for me to lie. 
i edited my initial save, saved the edits
![image](https://user-images.githubusercontent.com/50547000/146482029-299dc145-c16b-4567-a9a6-5e3b4daa28b2.png)
closed the editor, reopened it and opened my edited save to make sure it was edited and it was 
![image](https://user-images.githubusercontent.com/50547000/146482086-cf38802e-f453-4739-8261-b5e5a191b9e5.png)
close the editor, opened acnh, save that none of the things i have edited saved and that they reverted to my previous save even though it was overwritten, opened the save in the editor and saw that everything was reverted
![image](https://user-images.githubusercontent.com/50547000/146482231-ec152808-9b22-464b-a172-1b0b67abd151.png)
i am genuinely confused

**Comment by skyl9r** [comment]
ok so i loaded up the game and WATCHED CLOSELY at my SAVE and it literally replaced the save files before i edited them. i do not know how to put this any other way but it is MAGICALLY REVERTING
