### ISSUE TITLE
save is still MAGICALLY REVERTING

### ISSUE THREAD

**Issue by skyl9r** [kwsch/NHSE#579]
i literally do not know how to elaborate on this but my edited save files (WHICH ARE IN FACT OVERWRITTEN I HAVE DOUBLE CHECKED) keep getting REPLACED by my file before i edited it. i loaded up my DEFINETLY EDITED SAVE in my game and i looked at my files and it literally updated them and replaced them with all edits reverted. i checked. i do not know why this is happening. I have checked that i exported my files correctly. i edited my file. i saved it. i closed it. i reopened my edited save file in the editor and i saw that it is overwritten. i saved it again just to make sure. i closed it. i open my game in ryujinx. my game is loading. While it is loading i am looking at my save folder. I literally see and it is replaced. what the hell.

**Comment by kwsch** [comment]
Do not open duplicate issues. This does not happen on retail hardware; you're probably doing something wrong with your emulator.
