### ISSUE TITLE
Editing player house - save button outside displayed window

### ISSUE THREAD

**Issue by visintk** [kwsch/NHSE#582]
When I try to edit the player house, the "save" button on the far right is outside the displayed window, and I'm unable to scroll to it or to enlarge the displayed area.  

![player house editing issue](https://user-images.githubusercontent.com/96345226/146646185-50a20b4c-9d50-46ee-9237-dc8b22dfd277.JPG)

**Comment by berichan** [comment]
Update your OS, it's unlikely one of the collaborators is going to install an EOL version of Windows to move a button for you.

**Comment by visintk** [comment]
👍 Fair enough. Thanks!
