### ISSUE TITLE
Custom Designs Request and/or issue?

### ISSUE THREAD

**Issue by jdroo** [kwsch/NHSE#584]
**Is your feature request related to a problem? Please describe.**

_**Using NHSE does not give me edit rights to custom designs, it also names the files wrong, my name in game is Boop, the town name is BoopTown, and NHSE saves the imported custom designs as name Boop, and town as Boop.... bug?? seems to be just grabbing my name twice!**_ 

_**Trying to use the custom design export part of the NHSE to change ownership of the files I sent over via the phone app to my switch, because apparently the legit Nintendo owned app wont even give you perms to the designs you've made on websites like "acpatterns".**_

_**Requesting a button, that one simply clicks, to take ownership of any design and pro design.
Also a text box to fill in that info manually [if possible]**_

**Describe the solution you'd like**

_**A simple button and/or possible manual text entry, to take ownership of Designs and Pro Designs**_ 

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.**

**Describe alternatives you've considered**

_**I've tried many alternatives, even tried the Design Pattern Editor, but the person making it most likely does not have time to update that tool, being they said they don't even play the game much anymore.**_

_**Also tried the website "acpatterns", but simply saving the file after giving it my name and town name does not seem enough to make the game think I own the imported designs.**_

_**I also tried importing the design over an existing one I own, as was mentioned in a past request on this same issue page. XD does not work.**_

_**So far I've not found any recent tool, that is still updated regally that can do this one task! XD
[would be neat if there was a simple stand alone tool, that can just edit the ownership rights from the custom design files your tool exports...]**_

**Additional context**

_**Yeah I just want a way to get ownership of designs, so I can edit the custom designs I made on acpatterns in game**_

**Comment by lottehime** [comment]
Patterns are created/owned by the player default on import as of https://github.com/kwsch/NHSE/pull/634/commits/46f7017271f50de0b3d8eabed835b0b3c7f2c447.

On the broader topic: I _personally_ can't see a reason why someone wouldn't want ownership of them by default, **_but_** if users request that it be optional I can add a toggle at a later date - no problem.  👍

Ownership details are not changed on export, so you can still export and store designs from your files (or others) for storage or what have you.

If any users would like to request the enhancement above (new text inputs for single design pattern imports) please open a new issue.

Enjoy ✌️

**Comment by lottehime** [comment]
Patterns are created/owned by the player default on import as of https://github.com/kwsch/NHSE/pull/634/commits/46f7017271f50de0b3d8eabed835b0b3c7f2c447.

On the broader topic: I _personally_ can't see a reason why someone wouldn't want ownership of them by default, **_but_** if users request that it be optional I can add a toggle at a later date - no problem.  👍

Ownership details are not changed on export, so you can still export and store designs from your files (or others) for storage or what have you.

If any users would like to request the enhancement above (new text inputs for single design pattern imports) please open a new issue.

Enjoy ✌️

**Comment by MyShiLingStar** [comment]
The original creator spent time creating custom designs.
They share those designs for people to use but does not necessarily means that they want other people to change/edit/take ownership of those design.

Let's say I stole this design and claim that I created it myself. And then I sell it online to other people for money or peanuts.
![image](https://github.com/kwsch/NHSE/assets/816502/618431ac-097c-4678-b0c0-47f552c5e9aa)
What would the original creator think if they found out? There is a high chance that they might not share any more stuff afterward.

It's a moral dilemma. On one hand, you want the save editor to be able to edit everything. 
On the other hand, you don't want to hurt the player base because of their time and effort getting stolen.
On the third hand, it's a dead game anyway so I guess nobody cares.

**Comment by lottehime** [comment]
You're not wrong.  
As a professional artist myself, I understand and agree. The two values conflict at their cores.

The thing is you could always do this manually anyway and steal them - whether by editing the data block, or by just importing a .png of their work into design creation tools.  
I figure anyone who really wants to do this is going to do it anyway. It's why I find value in projects that catalogue these patterns with artists credits over enforcement of personal morals.  
But as I said, happy reassess options. 🙂
