### ISSUE TITLE
Wiki updates / Old Pattern Extract Method

### ISSUE THREAD

**Issue by Trinsid** [kwsch/NHSE#585]
The NHSE Wiki needs to be updated to include features like the map editor and pattern editor.

Additional information should be added to the wiki to include information on using all features featured in the tool. Patterns should be extracted as .acnh files instead of .nhd files. Patterns can be imported as .acnh files but cannot be used in other tools when extracted as .nhd files, such as ACPT (Animal Crossing Pattern Tool).

**Comment by berichan** [comment]
Anyone can edit the wiki, if someone wants to write a guide or feature usage instructions then they're more than welcome to. The map editor has a pretty extensive page on the wiki already under `Field Item Editor` but again, anyone is free to build upon/add to it if you feel like it needs more information.
