### ISSUE TITLE
Adding additional options to Acres?

### ISSUE THREAD

**Issue by purzer0** [kwsch/NHSE#588]
**Is your feature request related to a problem? Please describe.**
Under "Edit Map", "Edit Field Items", "Acres" there are options for changing portions of the map including even setting parts of your island to be like Harv's Island, but no other acre options such as the different acres seen in Kappn Islands or in the Happy Home Paradise DLC islands.

**Describe the solution you'd like**
It would be awesome if we could get the Acre options added in that could be selected to make our own islands have portions from the Happy Home Paradise DLC or Kappn Islands.  Are these possible to make selectable like the others?  Or is like the Museum and there's no way to put those pieces in as selectable acres?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

[EDIT] I think maybe the acres are there, I was just trying to use them without the Happy Home Paradise DLC so they were all invisible and intangible.  However, I did look through buildings in the map editor to see if DLC ones were selectable, and while you can put Studio (from Harv's Island) on your island, none from the DLC are selectable (they just say building 50, 55, 70, etc)

**Comment by purzer0** [comment]
Also on a similar note, I now wonder if it's possible to make the rooms in your house be as big as the ones in the DLC :)

**Comment by berichan** [comment]
I'm closing this as stale. Out of bounds acres seem to behave differently (unwalkable, behave like water) according to people who have tried assigning them. If anyone can document and provide information about getting these working then please post and I will reopen this, but for now this seems impossible.
