### ISSUE TITLE
Nook's Cranny upgrade

### ISSUE THREAD

**Issue by jedl1012** [kwsch/NHSE#59]
I wondering if its possible to trigger the nook's cranny upgrade with this editor. Its not cleared how its supposed to happen normally on the game.

Thanks in advance.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
