### ISSUE TITLE
DIY recipe and fish and bug

### ISSUE THREAD

**Issue by J133N** [kwsch/NHSE#590]
Some of the DIY Recipe no longer be able to display such as golden axe and golden can. also fish, bug and sea creature can no longer be set as present in the game like last time.

**Comment by klutch5398** [comment]
When was the "last time" for you? The updates that prevented this happened well almost a year ago.

You can't wrap bugs or sea creatures into presents and you can't fly out diy recipes like the golden axe and watering can.
