### ISSUE TITLE
2.0.4 Crashes

### ISSUE THREAD

**Issue by Coolcool4skool** [kwsch/NHSE#591]
2.0.4 Crashes every time I try to edit anything. May be me, may be a active issue. I'm not 100% sure.

**Comment by berichan** [comment]
What's the error it shows you? Are you using the latest build and can you provide the savefile that's causing the issue?

**Comment by Coolcool4skool** [comment]
> What's the error it shows you? Are you using the latest build and can you provide the savefile that's causing the issue?
Absolutely!
 It States the save is corrupted and prompts a restart of the island. 
Yes using [this link](https://berichan.github.io/GetNHSE/) 
And here is the save file:
[Treasure Island.zip](https://github.com/kwsch/NHSE/files/7966728/Treasure.Island.zip)

**Comment by berichan** [comment]
Your savefile has a header revision of 19 (0x13), 2.0.4 should be revision 26 (0x1A)
![HxD_2022-01-30_19-48-29](https://user-images.githubusercontent.com/66521620/151715172-ffb1685d-5a71-4877-af75-b832717e52b4.png)

Ensure your game is updated, save again, dump, then make your edits and restore.

**Comment by Coolcool4skool** [comment]
Okay I'll Try that and see if it works!

**Comment by Coolcool4skool** [comment]
I still don't know what program to use, but I have learned some more about what to do. 
so as a repeat of my last edit: "My last question is how do I decode the file(s) to change the value? (Or am I just being an idiot and there is a way that I don't see. ) Sorry If that sounds a little pushy, I don't mean to sound pushy.
(Sorry for being such a hassle though!)" Yeahhh Sorry about being so dumb about this, I only have had to do this stuff with older consoles so I don't know much about editing and stuff like that.

**Comment by Coolcool4skool** [comment]
> Your savefile has a header revision of 19 (0x13), 2.0.4 should be revision 26 (0x1A) ![HxD_2022-01-30_19-48-29](https://user-images.githubusercontent.com/66521620/151715172-ffb1685d-5a71-4877-af75-b832717e52b4.png)
> 
> Ensure your game is updated, save again, dump, then make your edits and restore.

Okay I have everything ready and loaded. Now Last Question and I will close the issue. 
Is there any specific way I need to change the files? 
Such as putting a specific hex value or some way through the console itself?
(PS Thank you for taking the time to reply to my questions.) (Much Appreciated.)

**Comment by berichan** [comment]
No, if this is your current savefile then you still haven't saved with 2.0.4

**Comment by Coolcool4skool** [comment]
> No, if this is your current savefile then you still haven't saved with 2.0.4
Ok this sounds really dumb but how do i save as 2.0.4? Sorry if that is dumb.

**Comment by Coolcool4skool** [comment]
OOOOOOKAY I REALIZED WHAT I NEED TP DO THANKS EVERYONE
