### ISSUE TITLE
When giving recipes, the "time obtained" recipe order becomes incorrect.

### ISSUE THREAD

**Issue by KPJoshi** [kwsch/NHSE#593]
I gave myself all recipes. They all show up in the DIY list. However, if I order them according to the date they were obtained, they appear at the bottom, below the flimsy axe recipe (which I believe is the first one you get in the game). This seems to suggest that the recipe date/order is not set when the recipe is given.

**Comment by berichan** [comment]
I'm closing this as stale. This is a relatively minor issue which doesn't seem to have any interest to solve. Feel free to post here and I'll reopen this issue if there are any further developments
