### ISSUE TITLE
(Bug) Cannot add A specific Villager to my Island

### ISSUE THREAD

**Issue by MewtwoFanz** [kwsch/NHSE#594]
I've been trying to add Kyle to my Island because I accidentally deleted him from my save file, but I've had no luck in getting him back. Even restoring previous save files with him in it do not work. What can I do?

**Comment by kwsch** [comment]
> Even restoring previous save files with him in it do not work. 

That should work.

You're likely not restoring your save file correctly. Save Data does not magically revert / erase changes.
