### ISSUE TITLE
Field Items remove results in floating furniture when placing new items

### ISSUE THREAD

**Issue by unspecifiedvolcano** [kwsch/NHSE#595]
Hi, 

I used the field items editor to remove furniture from my island but now when I place a gazebo some of the furniture I removed appears to be floating above the gazebo. This makes me unable to then remove the gazebo or move it. Could someone let me know how to fix this? Attaching Ryujinx logs and a screenshot. I used the remove all furniture feature for this area. Thanks
![2022022717033600-91F23AD0BEEFE8C9B2A45345B6E9116B](https://user-images.githubusercontent.com/100524977/155887838-9caf0ebd-18e8-44e5-9993-0762f259149a.jpg)
[Ryujinx_1.1.54_2022-02-27_17-00-47.log](https://github.com/kwsch/NHSE/files/8148864/Ryujinx_1.1.54_2022-02-27_17-00-47.log)
.

**Comment by kwsch** [comment]
Edit layer 2.
