### ISSUE TITLE
editing item quantity doesnt work

### ISSUE THREAD

**Issue by penguiin-12** [kwsch/NHSE#596]
title basically says it all. when i edit my save, right click the item to view, change quantity then right click and set the quantity, save inventory and save file, upon reloading save in ACNH new stacks can appear, but only as 1 item. modified quantity on existing stacks usually increments by +1 instead of selected stack amount

**Comment by kwsch** [comment]
You have to set the item back into the inventory prior to saving your inventory. The item editor does not edit item slots in-place.

Also, keep in mind that the item quantities start at 0 (for quantity=1). Refer to the wiki.
https://github.com/kwsch/NHSE/wiki/Item-Editing
