### ISSUE TITLE
Vague Item Editing Wiki 

### ISSUE THREAD

**Issue by Urbanxx001** [kwsch/NHSE#598]
I read the wiki and understand that certain items can use the "Count" value for editing color/variation, but some have 2 types of variation. After some save testing, I learned that to customize these items, you need to add both values together and put that in "Count". For instance, a magazine rack with yellow wood (5) and pink magazine (160) will be 165. Please add this to the wiki. Thanks.

**Comment by berichan** [comment]
Updated the wiki. In the future you may edit the wiki yourself, it should have public write access 👍

**Comment by Urbanxx001** [comment]
Thank you I appreciate it!
