### ISSUE TITLE
Add button to unlock all variations of received items?

### ISSUE THREAD

**Issue by Snowstar38** [kwsch/NHSE#599]
**Is your feature request related to a problem? Please describe.**
No; this would be an additional feature.

**Describe the solution you'd like**
I'd love it if there was a button to check/unlock all the variations of items without unlocking the items themselves. This way, the item and its variations will not show up in the in-game catalog until you actually obtain the item, reducing catalog clutter.

**Describe alternatives you've considered**
I did this once manually by checking every single box for every variation. It took hours, but it did work.

**Additional context**
This would basically make it so that every time you unlocked a new item for the catalog in-game, all the variations are instantly available for order.

**Comment by kwsch** [comment]
Use the Give All button at the bottom left?

**Comment by Snowstar38** [comment]
Ah, I mean without unlocking the furniture itself. The Give All button
unlocks all the items as well as their variants.

Basically: I don't want to fill up my catalog with every furniture item, I
want to discover them on my own. But I would like the variations to all be
available in my catalog once I DO get a new item, instead of having to
trade/customize for every single one.

The in-game catalog does behave like that when I check the variation boxes
manually (the ones on the right half of the Player Obtained menu) while
leaving the actual items (on the left half) unchecked; I'm just asking for
a button to do that to all the items on the right half, and not the left (a
"pre-unlock variants" button, basically). Doing them individually takes a
LONG time.
