### ISSUE TITLE
How does one launch this on PC ?

### ISSUE THREAD

**Issue by OvadaJester** [kwsch/NHSE#6]
I am not at all comfortable with coding, so I don't understand how I am supposed to launch this on my computer. I am already aware of the save extraction needed, and it is done, I just don't get it about NHSE.

**Comment by kwsch** [comment]
Download the compiled build from the Azure Pipeline linked at the top of the repo (or the checkmark next to each commit), then run the exe. Needs .NET Framework 4.6 (which pretty much everyone already has installed on Windows PCs).

**Comment by OvadaJester** [comment]
Here's the issue : I don't understand a thing. Consider that I don't get what you are talking about. What's obvious to you is a mystery to me...

**Comment by kwsch** [comment]
https://cdn.discordapp.com/attachments/677045461709881344/684127997451698333/sysbotnet.gif

If you're still confused, wait for someone to make a guide.
