### ISSUE TITLE
With the new update that came out today, what things on the save editors can definitely get you banned if going online

### ISSUE THREAD

**Issue by edfrick** [kwsch/NHSE#60]
I feel there is no information regarding this tool and today's patch and I feel like getting clarification for people who don't wanna get banned online for being detected on faulty saves is important, today I started a new island gave myself max miles and max bells in my savings account and all DIY recipes if I were to play online with friends could this get me banned? Also what are some things to stay away from if we were to go online while using this tool. thank you in advance

**Comment by kwsch** [comment]
This isn't relative to GitHub issues for NHSE. This isn't a place for discussion regarding save editing in general.
