### ISSUE TITLE
Unknown revision! Yes I do have the latest version of NHSE

### ISSUE THREAD

**Issue by pinkypie3611** [kwsch/NHSE#602]
Upon opening main.dat with NHSE I receive the error:

"Unknown revision!
FileHeaderInfo { Major = 115203594, Minor = 3655129928,
Unk1 = 55258, HeaderRevision = 54744, Unk2 = 54230,
SaveRevision = 3796 }"

My system has been recently updated with atmosphere and hekate, I also updated NHSE through this pipeline: https://dev.azure.com/project-pokemon/NHSE/_build/results?buildId=5020&view=artifacts&pathAsName=false&type=publishedArtifacts
I've checked and the last switch update was pushed April 18th, ACNH was pushed February 15th. This artifact was published April 24th. NHSE will still open older save files I have from jksv, but not the one I just started today. Please help

**Comment by berichan** [comment]
Considering the currect highest save revision is 27 and your save is showing 3796, your save is either corrupted, transferred or dumped incorrectly, or you're trying to open a save that is stored on some cloud drive and that is causing shenanigans.

Try redumping/transferring your save again and ensure you're not transferring to a cloud drive.
JKSV might also need updating if you haven't already done so.

This is not an issue with NHSE, it works fine with the latest ACNH update revision.

**Comment by pinkypie3611** [comment]
Could the issue be having multiple islands on one system?

**Comment by berichan** [comment]
No, switching between multiple islands/saves is usually fine
