### ISSUE TITLE
Injecting Inventory

### ISSUE THREAD

**Issue by moonknightCrescent** [kwsch/NHSE#603]
Hello all, I’m having issues connecting to my switch when I inject.

I get this message, can someone help, please?

Thanks in advance!!
![70BCFC99-771F-4BFE-A253-9CC77E1107F0](https://user-images.githubusercontent.com/105335813/167767513-7716b482-4bb0-4c83-aedb-37bb4987c1e8.jpeg)

**Comment by kwsch** [comment]
Double check you've installed custom firmware and the sys-botbase sysmodule. 

Refer to the wiki.

**Comment by Doctor-Pokemon** [comment]
I get this message sometimes when I have mods and/or codes running.

Have you tried holding L while booting the game?

**Comment by moonknightCrescent** [comment]
I followed the wiki and installed sysbot but now I see this FailValidate error
![729B6502-4066-473F-BEDD-4A79F289F0AB](https://user-images.githubusercontent.com/105335813/167847106-62bc9581-793e-4617-b027-f4f8e08c49c5.jpeg)
