### ISSUE TITLE
My villagers forgot who I was D: 

### ISSUE THREAD

**Issue by ablednt** [kwsch/NHSE#604]
I changed my name and it worked well / there didn't seem to be any issues but when i talked to my villagers who I was very good friends with they said they hadn't met me before and introduced themselves. Luckily I have a backup to the save already so nothing was lost but I was wondering if there's something I'm doing wrong or a way to change my name but keep my friendships intact?

**Comment by berichan** [comment]
This should've also changed the villager memories with your new name, but if for any reason it didn;t you can edit the memory name yourself. Edit Villager > Edit Player Memories
![image](https://user-images.githubusercontent.com/66521620/167942920-d70867b6-7ab8-469f-8490-dc96fa559e67.png)
