### ISSUE TITLE
An error occurred while trying to modify in real time

### ISSUE THREAD

**Issue by Ic-any** [kwsch/NHSE#605]
![image](https://user-images.githubusercontent.com/92638461/169690123-a2694e8d-5dfe-4edd-8311-f770466f2c53.png)
I have installed the required plug-ins, but I don't know why this appears in the software

![image](https://user-images.githubusercontent.com/92638461/169690154-6239418d-2f01-4395-a1d5-5e5ac2dc6199.png)
The IP is correct. I tried to connect my switch, but the game backpack was not modified successfully

**Comment by berichan** [comment]
`00000000` isn't a valid offset. Use the wiki to find the injector offset for your game update version, specifically https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection
