### ISSUE TITLE
NHSE Mailbox gone

### ISSUE THREAD

**Issue by Banto91** [kwsch/NHSE#606]
Hello, so my mailbox is gone. I have checked the house storage and the pocket and all the island but is nowhere. 

On the editor i upgraded the player house to 8 and after that i noticed it was gone. Them i tried to downgrade it back to level 1 to see if it would respawn but nothing. Can anybody hel?

**Comment by Lusamine** [comment]
This isn't an issue with the program.

https://github.com/kwsch/NHSE/issues/465#issuecomment-1095752510

Find a new mailbox and add it.

**Comment by Banto91** [comment]
Can you please tell me how to find a new mailbox and add it? I have searched through the issues and i saw a few people had the same problem but didn’t get an answer, is there a way to add a new one?
