### ISSUE TITLE
Missing inventory/storage/recycle bin flag0/flag1/uses/count fields

### ISSUE THREAD

**Issue by swablueme** [kwsch/NHSE#61]
Sometime between 11 hours to (more than?) 23 hours ago, a PR removed the fields for editing count/uses/Flag0/Flag1
Example of behaviour:
![image](https://user-images.githubusercontent.com/10569495/78744372-b8c90280-79a4-11ea-9f82-a1112a3bd93d.png)

Example of expected behaviour:
![image](https://user-images.githubusercontent.com/10569495/78744311-9931da00-79a4-11ea-8bd5-5ae3d1273c57.png)

**Comment by kwsch** [comment]
Are you using the .NET Core build, or do you have some different scaling happening?

![image](https://user-images.githubusercontent.com/6393368/78746248-2deff580-791b-11ea-8e2d-4e719e75782a.png)

**Comment by swablueme** [comment]
> Are you using the .NET Core build, or do you have some different scaling happening?
> 
> ![image](https://user-images.githubusercontent.com/6393368/78746248-2deff580-791b-11ea-8e2d-4e719e75782a.png)
> 
> (Compare the whitespace around the "None" items")
> 
> The commit that modified the item editor had put them in flow layout panels; if the controls are a tad bit too wide with your scaling, they'll pop down to the next row, which is not visible (since they're all on separate rows). I can update the sizing of things...
![2020-04-08_15-05-23](https://user-images.githubusercontent.com/10569495/78746517-6db1ee00-79aa-11ea-871a-8e5236df50fc.gif)

I am using the published artifacts supplied by azure

**Comment by kwsch** [comment]
Yeah it's probably the 125% scaling :)

**Comment by swablueme** [comment]
Just to add that this has been fixed, thankyou :)
