### ISSUE TITLE
Dream address change

### ISSUE THREAD

**Issue by purzer0** [kwsch/NHSE#610]
So I noticed something

Let's say you start on an island, develop it somewhat (i.e. unlock terraforming and get DIYs etc), copy this island to two Switches, and upload a dream address on each after finishing the island in different ways on each (even if neither one has uploaded before).

The dream address code it creates would be the same on each.  It seems to be remembering the "starting Switch" or some random key or something else from its original creation when making the dream address code.  That's not good, because then both switches are going to override each others' dream addresses from then on.

So then, what if we want it to be a different dream address code?  There must be a way, because restarting the island entirely (even on the same Switch) does let you get a different dream address code.

Whatever the flag or data is in the code that makes it give you the same dream address regardless of your Switch or whatever (even when neither switch has uploaded and then they both do at the same time), there must be some way to make the save data forget that starting point so that it can give your save file a new dream address code when you upload again.  Can you add a feature that makes sure it will create a new Dream Address code?

**Comment by kwsch** [comment]
> Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.
