### ISSUE TITLE
Ryujinx Item Injection

### ISSUE THREAD

**Issue by Mandydeth** [kwsch/NHSE#612]
I'm not sure if this is already a functionality of NHSE, but I haven't been able to get the inject item feature to work via Ryujinx. I do not get a notification of a successful connection. I made sure to open my gate, but it didn't seem to make a difference. Is there a special procedure I should be following for this, or is simply not compatible?

**Comment by kwsch** [comment]
Read the wiki. Item injection requires a sysmodule running on your console's custom firmware.

**Comment by Mandydeth** [comment]
I have installed sys-botbase but continue to have the same issue.

**Comment by Lusamine** [comment]
The program is made to connect to an actual console running CFW and sys-botbase. It is not made to work with emulators.
