### ISSUE TITLE
Issue can't add diy, axe or water can?

### ISSUE THREAD

**Issue by SpudGunMan** [kwsch/NHSE#613]
I added (DIY RECIPE) watering can, and axe, along with other stuff. 

Other stuff showed up, these didn't.

**Comment by berichan** [comment]
The game likely considers them event items as they are obtained as part of the tutorial in the game, and as such would not show up between saves. You can try [injecting them directly into your pockets](https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection) but they are obtained so early on that it's probably best to obtain via normal gameplay.

**Comment by SpudGunMan** [comment]
Sorry forgot to mention GOLD 

Gold items which are not
