### ISSUE TITLE
Issue can't add diy, GOLD axe or water can?

### ISSUE THREAD

**Issue by SpudGunMan** [kwsch/NHSE#614]
I cant seem to add "gold DIY Recipe for axe or water can".. everything else works fine.

**Comment by kwsch** [comment]
![image](https://user-images.githubusercontent.com/6393368/205476214-9173a1fd-dd5d-4701-baee-4aac141c3f84.png)

**Comment by SpudGunMan** [comment]
it dont work? haha whatever dude
