### ISSUE TITLE
Issue can't add diy, GOLD axe or water can?

### ISSUE THREAD

**Issue by SpudGunMan** [kwsch/NHSE#615]
to be very specific I can add all the other DIY recipes but when I add the AX or water can it never shows up in the game.

**Comment by SpudGunMan** [comment]
I won't be sponsoring this project so go ahead and close it as well!

**Comment by kwsch** [comment]
Do not spam GitHub issues. This is a free program.
#613
#614

Berichan already mentioned that the game has preventions for some DIY recipes; did you try searching for other issues to see if others have asked about DIY recipes?
#590
#500
https://github.com/berichan/ACNHMobileSpawner/wiki/List-of-unflyable-DIY-recipes
