### ISSUE TITLE
An error not findable via Wiki to fix

### ISSUE THREAD

**Issue by idktbhowo** [kwsch/NHSE#616]
![image](https://user-images.githubusercontent.com/121467483/209595585-d6f27e6f-ba58-4205-8201-c700bc9b0109.png)

**Comment by kwsch** [comment]
NHSE does not update when a new patch drops.

Re-download the program, this SaveRevision is supported on the latest update from over a month ago.
https://github.com/kwsch/NHSE/commit/fd6a6c086067339129117adae5985f406261f587
