### ISSUE TITLE
File size too big now after starting DLC

### ISSUE THREAD

**Issue by AzrouStone** [kwsch/NHSE#617]
I began hacking in money and completed the first half of the game with KK Slider, no issue and was just a few days ago. Then I did a lot of homes in the paradise planning but I didn't complete it when I noticed I have all food recipes yet I can't read this new one I got so I was going to edit a flag to say that I can (mistake on my part) but now I can't even open up my main at all.

**Comment by kwsch** [comment]
Are you using the latest build of the program?

**Comment by berichan** [comment]
Closing this as stale. It's likely your save simply wasn't dumped or transferred correctly as no one else has reported an issue like this.
