### ISSUE TITLE
[Bug] Black Bars appearing in Menus when using Wine

### ISSUE THREAD

**Issue by DraconicNEO** [kwsch/NHSE#618]
Hello, I noticed while using Wine to run NHSE on Linux that there is a bug which causes black bars to appear in certain settings menus which don't appear in the windows version.

here are pictures to show the issue in Wine:

![Menu 1 Wine](https://user-images.githubusercontent.com/44508470/221104584-214fa127-9a25-4ba0-8e0b-40b821d7fcb5.png)

![Menu 2 Wine](https://user-images.githubusercontent.com/44508470/221104602-10e45924-6a54-4f30-a872-f16a86f22540.png)

![Menu 3 Wine](https://user-images.githubusercontent.com/44508470/221104640-935f6d8a-dc09-4190-a1c5-bfc573a2ef54.png)

Compared to how it's supposed to look in Windows:

![Windows Menu 1](https://user-images.githubusercontent.com/44508470/221109435-69e92e68-f42a-4216-95bc-a80a3a3ab9d7.png)

![Windows Menu 2](https://user-images.githubusercontent.com/44508470/221109473-bc211272-4685-4238-bc0f-0e4b5399ed58.png)

![Windows Menu 3](https://user-images.githubusercontent.com/44508470/221109493-aef92174-42aa-4a5d-a74b-dbc84e1225af.png)

As you can see the black bars are present in the Wine version but not in the Windows version.

More Info:
----------------------------------

OS: Pop OS 22.04 (Ubuntu 22.04 Base)
Wine Version: 8.2
NHSE version: Build Number 5690
Net Framework Version: 7.0

**Comment by berichan** [comment]
I'm closing this as stale. This is something that would be need to fixed on Wine's side, it's not really possible for us to fix this on our side. If you are able to provide more information that could help on our side or if there any further developments towards a fix then please let me know in this issue and I'll reopen it.
