### ISSUE TITLE
How do you use this on a mac?

### ISSUE THREAD

**Issue by Gingerheim** [kwsch/NHSE#62]
I followed the guide to download this in #6  , but I have a Macbook Air and the .exe file won't run on here.

**Comment by kwsch** [comment]
Mono/Wine. Same as you would with PKHeX.

**Comment by Gingerheim** [comment]
Never used PHHex or any other type of save editor, even when I had a PC. I'm going into this completely blind. If there is a link to a tutorial for these kinds of things, I would greatly appreciate it.

**Comment by iMonZ** [comment]
> Mono/Wine. Same as you would with PKHeX.

Or could you compile this for Linux?
This would be great!
Then this could run everywhere

**Comment by iMonZ** [comment]
For Windows you can use it with WSL so everyone’s winning!
