### ISSUE TITLE
Unknown revision! error on new map backups?

### ISSUE THREAD

**Issue by FezVrasta** [kwsch/NHSE#620]
**Is your feature request related to a problem? Please describe.**

I started having issues with maps backed up using JKSV. I get this error on load:

```
Unknown revision!
FileHeaderinfo { Major = 524297, Minor = 524421, Unk1 = 2,
HeaderRevision = 0, Unk2 = 2, SaveRevision = 28 }
```

I didn't change anything on my Switch or PC so I'm not sure what it could be.

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by berichan** [comment]
Make sure you're using the latest build, support for this revision was added with https://github.com/kwsch/NHSE/commit/fd6a6c086067339129117adae5985f406261f587

**Comment by FezVrasta** [comment]
Thanks, could you update the https://berichan.github.io/GetNHSE/ website to point to the latest build? It still points to an old one.

**Comment by berichan** [comment]
It automatically links to the latest build, ensure you're not using an older build you have leftover on your PC 
![image](https://user-images.githubusercontent.com/66521620/222201524-2f76a12c-4d01-4765-ad37-9cc5976d9608.png)

If you're still getting issues with the latest build, post the savefile here.

**Comment by FezVrasta** [comment]
Oh sorry, I see, 2.0.6 wasn't a new release, my bad
