### ISSUE TITLE
item variants not in inventory editor

### ISSUE THREAD

**Issue by 29garps** [kwsch/NHSE#622]
I was testing out nhse for my animal crossing save, but I couldn't find a way to change item variants. Even if I go to DIY recipes, it won't let me choose which one. Is there a button to change this? I saw in a tutorial that there was a dropdown menu for this, but I couldn't find it. Is there a dropdown menu or could one be added?

**Comment by kwsch** [comment]
Please be more specific.

Some items have entirely separate item IDs, and other items use the multi-value combination to determine variant.
