### ISSUE TITLE
Villagers have blank text boxes when speaking to them

### ISSUE THREAD

**Issue by FirenLol** [kwsch/NHSE#624]
I love Wolfgang and I wanted him on my new island, but every time I speak to him. It gives me the greeting text and then I'll select the talk option and it'll come up blank
![Uploading 16814390701408295933746706011837.jpg…]()
![16814391006205971544820105458949](https://user-images.githubusercontent.com/84254536/231925849-13b30cf9-c070-45c7-9798-5fb6a6ce4816.jpg)

**Comment by kwsch** [comment]
Inject the full villager data to the save file, don't just change it manually.
