### ISSUE TITLE
Changing Airport color does not alter things that depend on airport color

### ISSUE THREAD

**Issue by LazyShyGuy** [kwsch/NHSE#627]
When changing the airport color, the various things that change dependent on the airport color do not.
The example that comes to mind is items in the Nook Miles store, I don't know how strict Ninty are but this might mean changing your airport color could make you candidate for a ban if you go online.

https://www.akrpg.com/upload/20211009/6376939229399680217531498.jpg

Here's an example of the differences in the Nook Miles store

**Comment by kwsch** [comment]
Correct, they're stored separately but initialized from the same value.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Comment by berichan** [comment]
Closing this as stale, it's unlikely there is a possible ban risk with this as this is one of the most common treasure island edits and hasn't gotten anyone banned.
