### ISSUE TITLE
Errors caused by modifying the save during the game: Game save repair request

### ISSUE THREAD

**Issue by 1350339182** [kwsch/NHSE#629]
Due to my use of NHSE to modify the save during the game, the game encountered an error reading the save:

The value of InvalidArgument='233' is not valid for 'SelectedIndex' Parameter name: SelectedIndex

Unfortunately, this is my girlfriend's game save. She felt very sad because she couldn't play this save anymore, so she wanted to abandon the game. I am very sorry for this, but I am unable to repair this archive myself. So I earnestly request someone to save this archive, in order not to make my girlfriend sad. If necessary, I am willing to pay for this.

**Comment by kwsch** [comment]
Any backup files next to the executable?

**Comment by 1350339182** [comment]
Only a backup from a month ago

**Comment by 1350339182** [comment]
> 可执行文件旁边有备份文件吗？

Only a backup from a month ago

**Comment by kwsch** [comment]
Oftentimes you can just "continue" from the errors, but if not, the only other option I would recommend is to run the program in debug mode and see where the exception is thrown, and either change the value manually or ignore the value entirely.

Usually, it's because your save file has an invalid (out of range) value trying to apply to a numeric-up-down control.

**Comment by 1350339182** [comment]
> 通常，您可以从错误中“继续”，但如果没有，我建议的唯一其他选择是在调试模式下运行程序并查看异常抛出的位置，然后手动更改值或完全忽略该值。
> 
> 通常，这是因为您的保存文件具有尝试应用于上下数值控件的无效（超出范围）值。

Thank you. I'm not very familiar with C #. I successfully entered Debug menu and found the location where the exception was thrown, but how can I modify the error value?

**Comment by 1350339182** [comment]
> Oftentimes you can just "continue" from the errors, but if not, the only other option I would recommend is to run the program in debug mode and see where the exception is thrown, and either change the value manually or ignore the value entirely.
> 
> Usually, it's because your save file has an invalid (out of range) value trying to apply to a numeric-up-down control.

Thank you. I changed all the Outlier to 0. Unfortunately, all the information in the archive is wrong. This archive is hopeless

**Comment by 1350339182** [comment]
Thank you. I changed all the Outlier to 0. Unfortunately, all the information in the save is wrong. The save  is hopeless to be repaired.
