### ISSUE TITLE
Enable/Disable Nookphone Apps? 

### ISSUE THREAD

**Issue by sneedfeedseed** [kwsch/NHSE#63]
Hello, love your work. Here's an enhancement idea I thought I'd just throw out there.
Is it possible to be able to enable/disable nookphone apps? For example multiplayer app, since I deleted another user from my switch that app is basically worthless and just takes up space and would love to disable it if possible, im sure maybe there's a flag option for that somewhere.

![nookphone apps](https://user-images.githubusercontent.com/62983327/78792628-5b6e8a80-797f-11ea-94f6-a6afa9d66726.png)

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by sarahlicity** [comment]
The apps on the phone _can_ be enabled or disabled through the Edit Flags function, although this process is a little opaque. For the example of removing the _Call Resident_ function, you'd want to disable flag `0x12F`; the other apps are prefixed with Mainmenu in [EventFlagPlayer.cs](../blob/master/NHSE.Core/Structures/Records/EventFlagPlayer.cs).
