### ISSUE TITLE
island water got cut off in map editor

### ISSUE THREAD

**Issue by ELY3M** [kwsch/NHSE#630]
I did first editing in acnhpoker via bulldozer.  I enlarged the island.    
I moved the resident services building and its ground part to NW corner.  

I saw that the radio box is off from the RS floor.   
I opened the save in NHSE and I cant access the whole island.  

see the screenshot.   cant access the whole RS.    

![cut-off](https://github.com/kwsch/NHSE/assets/10571497/3e633088-4ddd-4b52-a406-2ca935fedd3d)

**Comment by berichan** [comment]
Do you have a save backup prior from the issue happening? Edits from a different program may cause unintended issues that NHSE can't know how to deal with.

**Comment by ELY3M** [comment]
@MyShiLingStar    I am tagging ACNHPoker author here.

**Comment by ELY3M** [comment]
![2023060605060600-02CB906EA538A35643C1E1484C4B947D](https://github.com/kwsch/NHSE/assets/10571497/e759eaef-6817-453a-a8ba-6788b2029325)
![2023060605055700-02CB906EA538A35643C1E1484C4B947D](https://github.com/kwsch/NHSE/assets/10571497/08345733-d9bc-448a-9cf8-ff04aff68844)

**Comment by ELY3M** [comment]
ACNHPoker also have same issue in map dropper function.   I will have to fix that too.

**Comment by berichan** [comment]
I suggest starting over your edits with your backup, NHSE just pulls what it sees from your savedata and if multiple programs are seeing the issue then it's unlikely this is an issue with NHSE.
