### ISSUE TITLE
FLAG EDITOR

### ISSUE THREAD

**Issue by bam-p** [kwsch/NHSE#632]
Hi all, just wondering if anyone knows what flag unlocks Brewster to the museum? Looked through the list but can't seem to find anything😩

**Comment by kwsch** [comment]
Closed, this isn't an issue with NHSE.

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

If something can be obtained by regular storyline progression, it is recommended to just play the game and unlock it as intended by the developer. Doing hacky flag toggles can screw up things if there are other flags/values that need to be set as a result of that natural progression.
