### ISSUE TITLE
Items on layer 2 are turned off

### ISSUE THREAD

**Issue by dinaebh** [kwsch/NHSE#633]
I love NHSE but I would love to be able to set a lamp turned on in layer 2. I didn't find any option to do so, so when I put an item that usually you have to interact with to activate/turn on, it's turned off. Is there a way we get the items in layer 2 to turn on?
Sorry for my bad English.

**Comment by berichan** [comment]
It's a little late, but NHSE has an item flag to turn a light on/off. Different lights have different flag behvaiours (especially if they can be rotated) so it's best to turn one on manually ingame and view the changes in NHSE to see what change (compare before/after with screenshots of the program)
