### ISSUE TITLE
Profile ID?

### ISSUE THREAD

**Issue by x43x61x69** [kwsch/NHSE#64]
I did some tests and found that if I export saves and import it to another console, it will let me re-assigned to a new Switch Profile as the original one is gone.

However, if you try to LAN play with the same saves on 2 consoles, they can't seems to find each other (although both account have different Nintendo ID linked to them). I suspect that there's a profile ID or something in the save data that the game can identify the broadcasting player when LAN play. (It couldn't be the player's name or island name as they could be the same for anyone. But as changing them would cause problems in the game, it's possible they kept an ID or some sort for communication.)

Did you find something that could be used to identify the player?

Thanks for the great tool!

**Comment by kwsch** [comment]
> I suspect that there's a profile ID or something in the save data that the game can identify the broadcasting player when LAN play.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
