### ISSUE TITLE
Could not load file or assembly

### ISSUE THREAD

**Issue by iMonZ** [kwsch/NHSE#643]
I get the following error after opening my main.dat:

<img width="289" alt="Screenshot 2023-12-29 at 09 36 17" src="https://github.com/kwsch/NHSE/assets/11319871/fa9f41e7-7231-49ac-8ddd-0424612a4c7c">

**Comment by lottehime** [comment]
Hi, do you have the .exe in the same directory with all of its files (it's dependencies)?

**Comment by iMonZ** [comment]
> Hi, do you have the .exe in the same directory with all of its files (it's dependencies)?

All right good point!
Worked after I moved the folder into my bottle.
Just a hasstle binging with wine etc.
A tutorial would be so great so other people wont stub throught the wall like me haha.
But thanks
