### ISSUE TITLE
Editing Field Items Issue

### ISSUE THREAD

**Issue by Alucardaria** [kwsch/NHSE#645]
anytime i change the  field items, terrain,acres and or buildings and try to load the save on my switch, it always says that the save is damaged, any idea why? nothing is floating in nhse so im really confused what else it could be.
![E558E3F9-8CC6-421A-BCA1-A87ACD404831](https://github.com/kwsch/NHSE/assets/32625196/b3ae2af3-00d2-480c-a5ac-c2a497683771)
![6B3FBFCF-FD24-4CA6-85C7-997909309813](https://github.com/kwsch/NHSE/assets/32625196/27d996a0-8541-4861-9183-35e68846aa52)
save: https://drive.google.com/drive/folders/1Y4zoIkVJOyf2C1YlLqZP-bRlmz4uOIP_?usp=sharing

**Comment by kwsch** [comment]
Try restoring a backup, and also try restoring a save that you don't make any edits to (but export from the program).

**Comment by Alucardaria** [comment]
okay ty, restoring a backup helped, when figuire out why it corrupts then the fun can begin

**Comment by lottehime** [comment]
Stale, so closing this issue.
Please feel free to re-open with additional information and saves for repro if this issue persists.
