### ISSUE TITLE
native fruit and native flower won't change at all

### ISSUE THREAD

**Issue by delargenol** [kwsch/NHSE#646]
i followed all the steps to change the native fruit and the native flower, changed on my passport, on the field goods, map flags, etc. 

the new native fruit actually shows up on the shop with the correct price, it also shows on the DIY list of the starter houses furniture, and on my passport.

but the fruits won't change on the trees, and the flowers won't change on the island either.
i've tried time traveling, shaking the trees and waiting for the new fruits, but still, it just keeps showing the old native fruit and the old native flowers.

does anyone know what could be wrong?

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/316
