### ISSUE TITLE
dump dodo islands 

### ISSUE THREAD

**Issue by Albaa10** [kwsch/NHSE#649]
kwsch Please could you create an app like luna app to dump islands with the dodo  code created but with the dodo codes you really are a genius I think you could do it if it's not too much trouble

**Comment by kwsch** [comment]
Not sure how this relates to NHSE. The homebrew applet seems to work fine, just let it run and visit the islands from dodo code.

If you're wanting some program that works without a hacked switch, then unfortunately that's not possible. A hacked switch needs to interact with the official servers to pull the island data, so the best you'll get is borrowing someone's switch (remotely like a sysbot) and having it transfer files that way.

**Comment by Albaa10** [comment]
> Not sure how this relates to NHSE. The homebrew applet seems to work fine, just let it run and visit the islands from dodo code.
> 
> 
> 
> If you're wanting some program that works without a hacked switch, then unfortunately that's not possible. A hacked switch needs to interact with the official servers to pull the island data, so the best you'll get is borrowing someone's switch (remotely like a sysbot) and having it transfer files that way.

Thank you for answering me and for the information, I have a modified switch with atmosphere but I don't know the steps I have to follow. You can explain it to me in more detail if you want, of course, and good luck in your projects.
