### ISSUE TITLE
Restarting Save

### ISSUE THREAD

**Issue by TerpToke** [kwsch/NHSE#65]
The problem is that anytime I make any change using NHSE, after reimporting save I am restarted to the beginning of the game.

I would like to edit my save without it resetting my progress

**Comment by kwsch** [comment]
Not an issue with NHSSE, rather, an issue with how you are restoring the save file to the game (bad files / extra files).

**Comment by TerpToke** [comment]
Please explain? I am simply using JKSV to back up and restore. I drag the folder to PC. Edit save. Drag save back on the SD restore. If there are any extra files then they have been provided from NHSE. And as far as bad file, I have only use NHSE and JKSV so it is one of the 2.

**Comment by TerpToke** [comment]
I also wanted to add that I am not new to this. I keep my saves clean. Folders and whatnot even cleaner. I can restore any of the saves I have created. But the second I use NHSE to change even 1 bell, it restarts my save. I appreciate the work hence why I am baffled as to why its not working. I have found 2 other people with the same issue. Folder structure and files are exact. I plan to just let NHSE restart a save, play until I can edit something. And then see if the changes stick. But if it reverts even THAT save, I believe it to be on NHSE. My last resort is to format my SD but literally everything else on my switch works great.

**Comment by TerpToke** [comment]
Lastly I wanted to mention the AC Design Patter Editor works just fine. Reopening ticket.

**Comment by TerpToke** [comment]
The actual issue was : After updating JKSV, it now inserts a main.dat (decrypted). Being that there is no documentation out there stating to remove any files JKSV backs up, I had no way of knowing this was an added file that would negate the effects of your program and restart my save. Instead of closing the ticket for a 2nd time, this info could have been provided to resolve my issue and to resolve anyone else who has updated JKSV. Thanks.
