### ISSUE TITLE
Nooklink app passport shows island name before modification

### ISSUE THREAD

**Issue by Smxbsja** [kwsch/NHSE#651]
I changed the fruit and island name through nhse.
I turned on the nooklink app and checked my passport. The fruit appeared as modified fruit, while the island name was still before the change.
I wonder if there is any way to solve this problem!

**Comment by kwsch** [comment]
Probably they've cached your original data. If it never updates, then there's no way for a save editor to edit the cached data stored on their server.

**Comment by Smxbsja** [comment]
Thank you for your answer. May I ask you one more question? Local fruit was reflected in app passport as soon as i change it. I wonder if it was reflected immediately because it was not saved as original data.
