### ISSUE TITLE
What do I do when it says to put main.dat?

### ISSUE THREAD

**Issue by Ronizlo** [kwsch/NHSE#652]

**Comment by lottehime** [comment]
@Ronizlo Please describe the issue in more detail and provide a screenshot if possible.

**Comment by kwsch** [comment]
Do you have a hacked switch running custom firmware to dump your save file?

This program is a save editor, and `main.dat` is the primary component of the save file. You need to obtain it prior to using this program.

**Comment by Ronizlo** [comment]
I figured out how to get on the software but was wondering how to save my changes when I'm done.

**Comment by Ronizlo** [comment]
I was told to select "save changes" but nothing happens when I press it.

**Comment by kwsch** [comment]
Once you've saved your changes, transfer the files back to your console and import the save data with the same app you used to export it.
