### ISSUE TITLE
Not sure what main.dat file is.

### ISSUE THREAD

**Issue by Ronizlo** [kwsch/NHSE#654]
Unsure what the main.dat file is supposed to be. I have a file saved of my island from JKSV but don't know what to do afterwards. Further explanation can be given.

**Comment by lottehime** [comment]
It really doesn't need more elaboration; it's the main component of the save and it's inside of your save backup if you take a look inside (as long as the save dump worked correctly).

There are many resources out there on this available in the first few google search results. For instance: https://ac-modding.com/ACNH/NHSE.html

This isn't what the issues tracking is for.

**Comment by Ronizlo** [comment]
@lottehime It's the file named "main" correct? If so, then I have tried dragging that into the NHSE. I looked at the site you linked and even more and they all said the same thing: to drag the main into NHSE. And I understand that is what is meant to be done but it never works. I just need some assistance or advice, please and thank you.

**Comment by Ronizlo** [comment]
@lottehime

**Comment by lottehime** [comment]
Make sure your save backup is valid and that everything is properly up to date / version matching and try again.
Besides this, seek assistance in a modding forum, subreddit or discord and find someone who can step you through and troubleshoot your particular files if need be.
