### ISSUE TITLE
There is no way to get into an exe?

### ISSUE THREAD

**Issue by Zombieskeletorhobo** [kwsch/NHSE#655]
The only thing i get for the app is an sln file, even then i cant change it to a .dat file, or an exe because it wont open at all. 

If you can, please write how to actually set up the program instead of telling us to use the wiki, (the wiki doesnt give answers to my problem either)

I have tried the mobile spawner as well, but it cant connect to suyu due to it not being an actuall switch/

Please and thank you.

**Comment by lottehime** [comment]
It's literally two clicks from the readme... Wiki -> Downloading. It is on the second line of text on "downloading" in the wiki:
https://github.com/kwsch/NHSE/wiki/Downloading-Compiled-Builds

It's also linked **_directly_** on the top right of the repo.

It doesn't get much easier. 🤷‍♂️
