### ISSUE TITLE
Question about terrain editor

### ISSUE THREAD

**Issue by L0vesixx** [kwsch/NHSE#67]
In terrain editor; what is the unit model name for the gaps in the ocean that you can't build over? I sort of messed mine up and would like to revert it :/
![IMG_3611](https://user-images.githubusercontent.com/63492774/79038582-33557600-7b8f-11ea-99f3-d89a5f75367a.JPG)

**Comment by kwsch** [comment]
The wiki explicitly says to make a backup of your terrain before making any edits.

Just copy the values from the row above, or change the acre type so it doesn't have a river mouth.
