### ISSUE TITLE
Tourney points editor

### ISSUE THREAD

**Issue by igromanru** [kwsch/NHSE#70]
**Is your feature request related to a problem? Please describe.**
In ACNH they made thurneys to a grindfest. You have to make 300 points to get the gold trophy.  
For people who has only few hours per day to play the game, it's really annoying.

**Describe the solution you'd like**
Find where the game saves points for the current Tourney and add it to the editor.

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by igromanru** [comment]
Sorry, looks like I don't understand what exactly it means.  
Can I create a "require research" issue here  or doesn't it allowed?  
Where can I leave my idea?

**Comment by kwsch** [comment]
> Can I create a "require research" issue

No

> Where can I leave my idea?

Not here. I don't do research requests.

**Comment by CanoeHope** [comment]
Under Edit Flags, try selecting the one marked "059 - CatchFishFesCount" and make the value 300.
