### ISSUE TITLE
Add more language support to Villager Catchphrase?

### ISSUE THREAD

**Issue by neosong1103** [kwsch/NHSE#71]
**Is your feature request related to a problem? Please describe.**
Yes, the catchphrase is working in English, French and other languages but not support Chinese, Japanese, and Korean.

**Describe the solution you'd like**
Add language support for the villager catchphrase.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**

**Additional context**
My game language is in Chinese, so I tried to edit Catchphrase to Chinese and English, which didn't work.
But seems it work properly with English and French.

**Comment by kwsch** [comment]
Could you upload a screenshot showing the data for the catchphrase? It's currently set to read as a Unicode string.

https://github.com/kwsch/NHSE/blob/da4b2925888435c411d43f5cd76cbaff8af8aaf4/NHSE.Core/Structures/Villager/Villager.cs#L63-L83

Dump the villager, open in HxD, go to offset `0x10014`, and select 0x18 bytes (24d), then share the screenshot.

**Comment by neosong1103** [comment]
![image](https://user-images.githubusercontent.com/40328026/79148399-67998400-7d93-11ea-8890-aeb8850014c3.png)
I'm not really sure if this is the screenshot you need.

**Comment by kwsch** [comment]
Loads the Chinese string in the editor just fine for me... `你真是憨啊`
![image](https://user-images.githubusercontent.com/6393368/79149597-41b4b500-7d7c-11ea-8185-c9087b0a80ea.png)

Is the issue that it won't display in-game?

**Comment by neosong1103** [comment]
Yes, It reads in NHSE properly, but in-game the catchphrase never changed.
![image](https://user-images.githubusercontent.com/40328026/79150228-5f8f1380-7d96-11ea-9699-27eb3e595f57.png)
![image](https://user-images.githubusercontent.com/40328026/79150240-64ec5e00-7d96-11ea-9818-f678be769643.png)

**Comment by kwsch** [comment]
Might be an in-game limitation on string length? Not sure if 5 characters is allowed, causing it to fall back to a default phrase defined in the ROM.

So long as the data being restored is your edited copy, if the restored data no longer contains the values for the catchphrase in your screenshot, then there's nothing NHSE can do if the game is overriding your edits.

**Comment by neosong1103** [comment]
I tried only two characters but still not working.
After there is nothing changed in-game, I save the game, export the save,
and read it with NHSE again, the catchphrase remains what I edited, not
overridden by the game.
The only issue is its not showing in the game somehow.

**Comment by neosong1103** [comment]
It is so weird that even English catchphrase is not working for me.

**Comment by neosong1103** [comment]
I just changed my game language into English, and the catchphrase works properly!
Seems the problem is with the in-game language, is there a way to fix it?

**Comment by kwsch** [comment]
Dunno, maybe some languages do not respect custom catchphrases.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
