### ISSUE TITLE
Editing Acres Crash

### ISSUE THREAD

**Issue by Darkaim63** [kwsch/NHSE#73]
When editing an Acre and I either hit save or close out of it, then head to top left File>Save, it gives me "Unhandled exception occurred in your application, index was out of range" 

![image](https://user-images.githubusercontent.com/13300875/79182653-2b324c00-7dc4-11ea-9b18-c1972ec66acc.png)

**Comment by kwsch** [comment]
Can you Tools->Verify Hashes with an unmodified save file?

**Comment by Darkaim63** [comment]
When I click Tools>Verify Hashes, I get the same error, possible issue with my copy of the Editor? Let me re-download it and I'll get back to you.

**Comment by kwsch** [comment]
Bad dump; if you did a dump via ftp maybe the connection didn't transfer the full file.
