### ISSUE TITLE
How to get different colours decoration in received item flag？

### ISSUE THREAD

**Issue by limoonfeat** [kwsch/NHSE#74]
There are three 【give all】 in received item ，but only the last one is valid。
and decoration like beds、lights、pianos have many different colours，【Give all】 will get all the org colours' one.

Are there any ways to get the different colours ones？

**Comment by kwsch** [comment]
The items list is just toggling bitflags; for customization, it must be stored elsewhere / dynamically determined.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by limoonfeat** [comment]
OK，I see thank you very much！Nice work！
