### ISSUE TITLE
Field Items Problem

### ISSUE THREAD

**Issue by LunaryUStyle** [kwsch/NHSE#76]
Hello, 
I wanted to reform and I had a problem, I deleted all the field items, but it also deleted my mailbox... I don't know how to have it back because I didn't tried to place one ...
Please help ;-;

**Comment by kwsch** [comment]
Restore your backup save file / field data that you dumped before making any changes.

**Comment by LunaryUStyle** [comment]
I deleted it i think, and i did many changes before i noticed that, so i will lose anything
