### ISSUE TITLE
Changing island/player name now works just fine.

### ISSUE THREAD

**Issue by etherela** [kwsch/NHSE#8]
I am sorry, I don't know where else I could send you a feedback, so I am sending it here on "issues".
So, I've been stalking your github and saw that you made an update about the changing names problem. Now it is working!

Also, I would like to know if you're gonna implement something to change the birthday date and the island native fruit.

Anyways, thank you so much for your hardwork!

**Comment by etherela** [comment]
Aaand what about changing the hemisphere? :)

**Comment by P4RI4H** [comment]
Changing Island name MOSTLY works. When I did, it left it the old name in my passport and now all my neighbors treat me like a visitor. Lol

**Comment by etherela** [comment]
> Changing Island name MOSTLY works. When I did, it left it the old name in my passport and now all my neighbors treat me like a visitor. Lol
> 
> Awesome work. 

Did you download the latest update of the save editor? Because now changing player/island name works just fine, as I said in the title of the post.

**Comment by tr1age** [comment]
So there is still a small error with island name changes, it leaves it in the villager's player memories.

**Comment by DraconicNEO** [comment]
> So there is still a small error with island name changes, it leaves it in the villager's player memories.

Any update on this issue?
