### ISSUE TITLE
Old villager houses are the same for new ones??

### ISSUE THREAD

**Issue by Skyrainsprings** [kwsch/NHSE#80]
So I used the tool to edit the villagers on my island and while it did give them the ones I wanted, the houses for the old ones remained the same. (E.g kid cat’s house was used for Raymond). Is this simply a coding issue or is it more underlying within the game itself because I don’t want Raymond having my old villager’s house-

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/17
