### ISSUE TITLE
Just asking to edit birthdate date

### ISSUE THREAD

**Issue by kirner** [kwsch/NHSE#81]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**

**Additional context**

**Comment by kirner** [comment]
is it possible to add this ? 
Thx

**Comment by kwsch** [comment]
You're supposed to fill out the issue template after reading it.

Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.
