### ISSUE TITLE
Moveing Out Villagers

### ISSUE THREAD

**Issue by CompClash** [kwsch/NHSE#83]
I used the new "Moving Out" check box and it shows my villager moving out (in boxes) but everytime the new day comes, it says he will be moving out tomorrow. It repeats this and never kicks him out! Now I think my save file is messed up. Any help with this would be great!

**Comment by kwsch** [comment]
Refer to the [issue templates](https://github.com/kwsch/NHSE/blob/master/.github/ISSUE_TEMPLATE/feature_request.md): 

> Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Without knowing how the game behaves (research), nothing can be implemented in the program.

**Comment by PandaUnit-TWL** [comment]
I found the "024 - ForceMoveOut = 0" flag in "Edit Flags". I flipped that to 1 and that made the villager leave immediately. Empty plot and didn't have to wait a day. Save game from after opened in NHSE shows the villager slot is empty and all flags are zero.

**Comment by HijackHornet** [comment]
I can't seems to be able to get a new villager to move in afterward.. the plot stay "sold to xxxx" but they don't move in
