### ISSUE TITLE
Grids for better island editing

### ISSUE THREAD

**Issue by vehneez** [kwsch/NHSE#85]
If possible, I'd like the save editor to have grids on the edit buildings mode so that it's more accurate and easier to edit the island.

**Comment by kwsch** [comment]
Without the building sizes, it's not really accurate to edit. Usually, the building coordinate is the top-left coordinate and the rest of the building tiles are then occupied expanding outwards to the final dimensions.

Right now, the map scale has each "coordinate" as a pixel, upscaled 4x (4x4 per coordinate). When drawing a building, it places an 8x8 square on the map, 4px offset from the x,y coordinates. I could increase the scale to be 8x, but again, the representation of the actual building dimensions isn't accurate to their actual size.

For now, it's recommended to just compare coordinates in-game and move accordingly. You can place items on the ground (a bag of bells occupies a 2x2 grid, so just measure in-game to get your final coordinates).
