### ISSUE TITLE
Ram edit bug makes everything unknown items in inventory

### ISSUE THREAD

**Issue by Janer1** [kwsch/NHSE#86]
Whenever i try to add something it makes everything leafs with no names and i cant drop them

**Comment by kwsch** [comment]
[Refer to the Wiki](https://github.com/kwsch/NHSE/wiki/RAM-Editing-&-Item-Injection).

The offset that is used is not for v1.0 (it's for v1.1+), and you have to be using sys-botbase 1.3 with no other cheat/overlays loaded so that sys-botbase may work correctly (not an issue with NHSE).
