### ISSUE TITLE
I hava a question,can u answer it for me?

### ISSUE THREAD

**Issue by CScorpion-h** [kwsch/NHSE#87]
Hello, I'm a green hand in development from China. I want to translate English to Chinese, but my version of Visual Studio is 2010, it can't compile your source code. Therefore, I would like to ask if u can send me a copy of sln that is available in VS 2010.

**Comment by kwsch** [comment]
Use [Visual Studio 2019 Community](https://visualstudio.microsoft.com/downloads/).
