### ISSUE TITLE
Can't Remove Weeds

### ISSUE THREAD

**Issue by MirayXS** [kwsch/NHSE#88]
# Can't Remove Weeds
I have some actual weeds in my map, but when i go to 
`map > Edit Fields Items > Weeds`
When i press "weeds" which would bulk-remove all the weeds in the map, it says
`Nothing Removed (none found)`
As i said i have weeds in my map, but the editor doesn't remove them.

**Comment by kwsch** [comment]
It only applies changes to the currently viewed 32x32 view.

To remove from all, hold shift when clicking the button.

**Comment by MirayXS** [comment]
Thank you, it worked now.
`Removed 52 from the map.`
