### ISSUE TITLE
Add keyboard support! 

### ISSUE THREAD

**Issue by GamerKarl** [kwsch/NHSE#91]
**Is your feature request related to a problem? Please describe.**
It frustates when i have to set the item inside the inventory because i have to use the mouse everytime when i wanna duplicate Nook Miles Tickets 
**Describe the solution you'd like**
a keyboard support like with the arrow to select the slot and with ctrl+v and ctrl+c 
or even a button with: "fill the inventory"

**Comment by kwsch** [comment]
Read the wiki. There already are hotkeys (mouse usage still required). If you want to improve the experience, feel free to submit a pull request with your changes.
