### ISSUE TITLE
Ability to change dates on nook mile achievements?

### ISSUE THREAD

**Issue by Skyrainsprings** [kwsch/NHSE#92]
**Is your feature request related to a problem? Please describe.**
The achievement dates for nook miles stays the same day to day after adjusting achievements in the achievement flag editor and it bothers me so much. ex, “Angling for perfection!” Currently has two achievements, and the dates remain the same day to day, like it never stays the same from the day that achievement was filled out, the date changes with whatever date my switch has it down as. Second achievement was done on a different day, yet remains the same as the one the first achievement was done.

**Describe the solution you'd like**
The ability to change dates on when nook mile achievements were made (ex. first achievement made on 3/20/2020 and second achievement made on 3/30/2020, that way it doesn’t bother the ever living hell out of me how they don’t align correctly.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Maybe the ability to lock the current achievement dates registered on the game file so they don’t change.

**Additional context**
This is how it looks when the dates stay the same even though they were both done on completely separate dates. (Sorry if my camera quality isn’t the best-)
![image](https://user-images.githubusercontent.com/63622776/80044434-19d6f700-84ca-11ea-86eb-8254b1a35666.jpg)

**Comment by kwsch** [comment]
> Note: Requesting new editing features that require research are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

Can't implement things without sufficient community knowledge.
