### ISSUE TITLE
Editing the dates that Mook Miles Achievements were awarded

### ISSUE THREAD

**Issue by Pasteashe** [kwsch/NHSE#93]
**Is your feature request related to a problem? Please describe.**
[I know that someone has already brought up this issue to which the response was: "Can't implement things without sufficient community knowledge." I am curious if this issue can ever be resolved or where the appropriate place to discuss this would be. I've been seeing this issue multiply more and more, where people are extremely frustrated by the timeline of thier nook miles achievements. It's happening to players who don't even time travel and it appears that they have time skipped back and forth. Regardless of the in-game time, player's are obviously not going back in time and don't want it to appear that way. My "Active Island Resident" nook miles show that I've been playing for 50 days before the 50 day mark was even possible to be reached.

**Describe the solution you'd like**
I'd love to be able to fix these dates to when they were actually achieved in real life. In New Leaf, I was able to change the date that I started my town, the progression of the town tree, etc. using the Marc Robledo version of the acnl map editor, so I have hope that someday down the line, a similar ability can be added to the switch version. I know that more research is needed and this isn't considered a feature request but I'm honestly not sure where else to go, but I'd like to push the issue since it has affected a lot of players. To whoever this issue concerns, I hope they look into it.

Note: Requesting new editing features that *require research* are not Feature Requests. This is only for improving interactions and/or leveraging the current code in new/interesting ways.

**Describe alternatives you've considered**
Being able to restart a nook miles task instead of changing the dates around.

**Additional context**
This is an example of nook miles achievements made under an impossible scenario.
![IMG_2740](https://user-images.githubusercontent.com/64176958/80050250-16039e80-84e3-11ea-83b9-998ebc03ff76.jpg)

**Comment by kwsch** [comment]
https://github.com/kwsch/NHSE/issues/92
