### ISSUE TITLE
"A null reference or invalid value was found [GDI+ status: InvalidParameter]"

### ISSUE THREAD

**Issue by iomintz** [kwsch/NHSE#98]
Trying to open a 1.2.0 save file results in the error message "A null reference or invalid value was found [GDI+ status: InvalidParameter]".

**Comment by kwsch** [comment]
Not sure what causes your player image to fail to load... the offset in the decrypted Personal.bin is:

```cs
        public override int Photo => 0x117C4; // +0x3FC from v1.1
```

The size of the jpeg is the 4 bytes prior to that offset

**Comment by iomintz** [comment]
This is not fixed. I get the same error and nothing in the console. I can send my save file backup if necessary.

**Comment by kwsch** [comment]
Sure.

Are you using mono?

**Comment by iomintz** [comment]
Yes

**Comment by kwsch** [comment]
Try again with the latest commit, and double check that your mono isn't too outdated.

NHSE tries to create a bitmap from raw data, and it appears that mono doesn't like doing that (for your data in specific).

**Comment by iomintz** [comment]
Still the same error.
```
➤ mono --version
Mono JIT compiler version 6.4.0 (makepkg/fe64a4765e6 Sat 16 Nov 2019 04:59:42 PM UTC)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by kwsch** [comment]
I don't think it's related to v1.2.0; without seeing a more detailed stacktrace I can't provide any assistance. Something internal to the framework is failing to load the images that the program needs.

**Comment by iomintz** [comment]
Is there an environment variable or flag I can use to get a more detailed stack trace?

**Comment by kwsch** [comment]
You'd probably have to compile the debug build and see where the error is being thrown; there's no real logging in NHSE to indicate the exact point at which it failed.

It might be a bug with mono (issue # 13049) where it fails to get the width/height of the bitmap; dunno how exactly to troubleshoot as I exclusively use Windows OS's :|
