### ISSUE TITLE
House editor dumping issue

### ISSUE THREAD

**Issue by strawpedro** [kwsch/NHSE#99]
Hi ! 

First of all thanks so much for updating the house editor! I figured out why my house dumps were wrong, see below example:

![image](https://user-images.githubusercontent.com/34144805/80065358-d347c380-84ee-11ea-8e55-003304a0fe80.png)

So Carrie is the 2nd villager in the main view, whilst in the house editor, the second slot is Agent S' house.

![image](https://user-images.githubusercontent.com/34144805/80065551-2752a800-84ef-11ea-8166-8199aa491fbc.png)

The tool is assigning Carrie as the name of the .nhvh file, but the file is actually for Agent S' house.

Could you kindly look into this?

The current workaround is to manually change the name of the dump file back to the correct villager, but a fix on this auto generation in file name would be very convenient

**Comment by kwsch** [comment]
Keep in mind the `NPC1` value is "Which villager lives in this house". Since villagers move out, a house at index X might not be villager X; you have to refer to the `NPC1` value.

I assume that `NPC2` might be cohabitation (married villagers living in the same house? weddings were in the datamine & new items... lul).

**Comment by strawpedro** [comment]
> Keep in mind the `NPC1` value is "Which villager lives in this house". Since villagers move out, a house at index X might not be villager X; you have to refer to the `NPC1` value.
> 
> I assume that `NPC2` might be cohabitation (married villagers living in the same house? weddings were in the datamine & new items... lul).

Thanks for the tip, I tried injecting the villagers I dumped into another save and it worked perfectly :) 

The only thing is to make sure the NPC1 # ties with the villager index # after loading the house dump

**Comment by kwsch** [comment]
> The only thing is to make sure the NPC1 # ties with the villager index # after loading the house dump

yeah, the program does this automatically :)

https://github.com/kwsch/NHSE/blob/94c141393f05e69c880ba99312e58d454d1d7146/NHSE.WinForms/Subforms/Map/VillagerHouseEditor.cs#L115-L119

(importing the house copies the old NPC1 value to the imported house, to keep them the same as different saves don't have the exact same order of villagers)
